User-agent: *
Allow: *.js
Allow: *.css
Disallow: /success
Disallow: /Errors
Disallow: /*utm_expid=
Disallow: /*utm_source=
Disallow: /*utm_medium=
Disallow: /*utm_compaign=
Disallow: /*utm_content=
Disallow: /*utm_term=
Disallow: /*?
Disallow: */order/*
Disallow: /success/subscription-cancelled
Disallow: /success/subscription-success
Disallow: /components/htmlcomponents
Disallow: /services/vds-vps
Disallow: /services/iaas
Disallow: /services/windows
Disallow: /services/object-storage
Disallow: /services/vds-vps/minsk
Disallow: /services/iaas/minsk
Disallow: /windows/minsk
Disallow: /services/vps-vds/virtual-server-1c
Disallow: /services/hosting-server
Disallow: /services/virtual-server-linux
Disallow: /services/virtual-server-centos
Disallow: /services/virtual-server-freebsd
Disallow: /services/virtual-server-ssd
Disallow: /services/virtual-server-ubuntu
Disallow: /services/virtual-server-debian
Disallow: /company/online-payment
Disallow: /main
Disallow: /conditions/useragreement-2021

# Project Solutions
Disallow: /proektnye-resheniya
Disallow: /proektnye-resheniya/professionalnye-servisy
Disallow: /proektnye-resheniya/upravlenie-oblachnoj-infrastrukturoj
Disallow: /proektnye-resheniya/cloud-journey
Disallow: /proektnye-resheniya/audit-i-proektirovanie
Disallow: /proektnye-resheniya/migraciya-v-oblako
Disallow: /proektnye-resheniya/informacionnaya-bezopasnost
Disallow: /proektnye-resheniya/kompleksnye-infrastrukturnye-proekty
Disallow: /proektnye-resheniya/private-cloud
Disallow: /proektnye-resheniya/hybrid-cloud
Disallow: /proektnye-resheniya/sap-hosting
Disallow: /proektnye-resheniya/avtomatizaciya-i-orkestraciya-oblaka

Clean-param: utm_expid&utm_expid&utm_medium&utm_term&utm_compaign&utm_content
Sitemap: https://1cloud.ru/sitemap.xml

User-agent: Yandex
Allow: *.js
Allow: *.css
Disallow: */amp/*
Disallow: /success
Disallow: /Errors
Disallow: /*utm_expid=
Disallow: /*utm_source=
Disallow: /*utm_medium=
Disallow: /*utm_compaign=
Disallow: /*utm_content=
Disallow: /*utm_term=
Disallow: /*?
Disallow: */order/*
Disallow: /success/subscription-cancelled
Disallow: /success/subscription-success
Disallow: /components/htmlcomponents
Disallow: /services/vds-vps
Disallow: /services/iaas
Disallow: /services/windows
Disallow: /services/object-storage
Disallow: /services/vds-vps/minsk
Disallow: /services/iaas/minsk
Disallow: /windows/minsk
Disallow: /services/vps-vds/virtual-server-1c
Disallow: /services/hosting-server
Disallow: /services/virtual-server-linux
Disallow: /services/virtual-server-centos
Disallow: /services/virtual-server-freebsd
Disallow: /services/virtual-server-ssd
Disallow: /services/virtual-server-ubuntu
Disallow: /services/virtual-server-debian
Disallow: /company/online-payment
Disallow: /main
Disallow: /conditions/useragreement-2021

# Project Solutions
Disallow: /proektnye-resheniya
Disallow: /proektnye-resheniya/professionalnye-servisy
Disallow: /proektnye-resheniya/upravlenie-oblachnoj-infrastrukturoj
Disallow: /proektnye-resheniya/cloud-journey
Disallow: /proektnye-resheniya/audit-i-proektirovanie
Disallow: /proektnye-resheniya/migraciya-v-oblako
Disallow: /proektnye-resheniya/informacionnaya-bezopasnost
Disallow: /proektnye-resheniya/kompleksnye-infrastrukturnye-proekty
Disallow: /proektnye-resheniya/private-cloud
Disallow: /proektnye-resheniya/hybrid-cloud
Disallow: /proektnye-resheniya/sap-hosting
Disallow: /proektnye-resheniya/avtomatizaciya-i-orkestraciya-oblaka

Clean-param: utm_expid&utm_expid&utm_medium&utm_term&utm_compaign&utm_content
Sitemap: https://1cloud.ru/sitemap.xml