User-Agent: *
Disallow: /tmp/
Disallow: /*/undefined/*
Disallow: /temas-resultados/
Disallow: /temas-*/indice/
Disallow: /hemeroteca/*
Disallow: /elecciones/generales/resultados/
Disallow: /en-detalle
Disallow: /*/en-detalle
Disallow: /addineyeV2.html
Disallow: /DARTIframe.html
Disallow: /doubleclick
Disallow: /eyeblaster
Disallow: /images/
Disallow: /imag/
Disallow: /imagenes/
Disallow: /includes/
Disallow: /wp-admin/
Disallow: /*/wp-admin/
Disallow: /hoyinversion/ 
Disallow: /finanzas/ 
Disallow: /comunabc/Widgets/rss/
Disallow: /hoysport/
Disallow: /recortes/
Disallow: /recortes/*
Disallow: /summum/recortes/
Disallow: /summum/recortes/*
Disallow: /play/recortes/
Disallow: /play/recortes/*
Disallow: /teknologica/
Disallow: /Syd/
Disallow: /*.swf$
Disallow: /*.tif$
Disallow: /*.flv$
Disallow: /*.mp4$
Disallow: /*.avi$
Disallow: /*.inc$
Disallow: /*.ics$
Disallow: /*.json$
Disallow: /*.geojson$
Disallow: /*-ntps.html$
Disallow: /prensa-historico/200*
Disallow: /prensa-historico/2010*
Disallow: /RC/*.xml$
Disallow: /abc2010/nacional/noticias/*.xml$
Disallow: /includes_comun/modulos_automaticos/
Disallow: /premiogastronomico/mejor.asp?search=&page=*
Disallow: /*/1$
Disallow: /*/%3C$
Disallow: /wp-content/
Disallow: *//.html
Disallow: /temas-*%7C%7Chttp://resizer
Disallow: */home$
Disallow: /xml-sindicacion/
Disallow: /sindicacion/
Disallow: /c1m/menu/time/
Disallow: /4900/webm.ABC/
Disallow: /gl-d/
Disallow: /*/gl-d$
Disallow: /ht-d/
Disallow: /*/ht-d$
Disallow: /bb-d/
Disallow: /*/bb-d$
Disallow: /deportes/futbol/directos/*/2010-2011/*
Disallow: /deportes/futbol/directos/*/2011-2012/*
Disallow: /deportes/futbol/directos/*/2012-2013/*
Disallow: /deportes/futbol/directos/*/2013-2014/*
Disallow: /deportes/futbol/directos/*/2014-2015/*
Disallow: /deportes/futbol/directos/*/2015-2016/*
Disallow: /play/foro/*
Disallow: /archivo/buscador/*
Disallow: /archivo/periodicos/*-*-*-*.html 
Disallow: /fe-de-ratas/
Disallow: /el-sacapuntas/
Disallow: /loteria-de-navidad/comprobar-loteria-navidad/numero-*.html?*
Disallow: /gurme/*/busqueda/?
Disallow: */aggregate*
Disallow: /includes_comun/*
Disallow: /*?cartelera_cine
Disallow: /acd/
Disallow: /recetasderechupete/?s=

User-agent: 008
Disallow: /

User-agent: Twitterbot
Allow: *

User-agent: ChatGPT-User
Disallow: /

User-agent: GPTBot
Disallow: /

#CSV 925679
User-agent: Google-Extended
Disallow: /

User-Agent: PerplexityBot
Disallow: /
