user-agent: *
disallow: /showcase.php/
disallow: /SendMailToUser.php*
disallow: /report_item.php*
disallow: /events/clicks
disallow: /offer/
disallow: /ape
disallow: /payments
disallow: /recommendations/
disallow: /cart-aggregator/
disallow: /favourites/
disallow: /usertraits/
disallow: /mediation/
disallow: *snapshot=*
disallow: /language-dispatcher
disallow: *&source=allegro.com&welcome=1&shippingCountry=US*
disallow: /login/auth
disallow: /auth/oauth/authorize
disallow: /produkt/warianty/
disallow: /uzytkownik*&*
disallow: /opinie-produktowe/
disallow: /zglos-naruszenie/
disallow: /uzytkownik/*SHOP-TAG*
disallow: /magazyn-allegro/
disallow: /szukaj/multi?phrases*
disallow: /promowane/
disallow: /kampanie/*&*
disallow: *reco_id=*
disallow: *preco_id=*
disallow: /*?*=*&*=*&*=*&*=*&*=*&*=*&*=*&*=*&*=*&*=*&*
disallow: /kategoria/*?*=*&*=*&*=*&*=*&*=*&*=*&*
allow: /uzytkownik/notfound?string*
allow: /uzytkownik/*bi_s=archiwum_allegro*

user-agent: Mediapartners-Google
disallow: *origin_url=*
disallow: /transakcja/
