# For all robots...
User-agent: *

# Disallow backend and default controllers
Disallow: /backend*
Disallow: /yupe/backend*
Disallow: /*/default*
Disallow: /site/search*
Disallow: /article/waterfall*
Disallow: /news/waterfall*
Disallow: /apostv*
Disallow: /*News_page*
Disallow: /*ajax=lpclist*

Sitemap: https://apostrophe.ua/sitemap-google-news.xml
Sitemap: https://apostrophe.ua/ua/sitemap-google-news.xml
Sitemap: https://apostrophe.ua/sitemap-google-articles.xml
Sitemap: https://apostrophe.ua/ua/sitemap-google-articles.xml
Sitemap: https://apostrophe.ua/sitemap.xml
Sitemap: https://apostrophe.ua/sitemap_ua.xml
Sitemap: https://apostrophe.ua/sitemap_en.xml
Sitemap: https://apostrophe.ua/sitemap_index.xml

host: https://apostrophe.ua