Sitemap: https://www.athinorama.gr/sitemap/movies
Sitemap: https://www.athinorama.gr/sitemap/theatres
Sitemap: https://www.athinorama.gr/sitemap/music
Sitemap: https://www.athinorama.gr/sitemap/restaurantsandclubs
Sitemap: https://www.athinorama.gr/sitemap/allnews
Sitemap: https://www.athinorama.gr/sitemap/googlenews
Sitemap: https://www.athinorama.gr/sitemap/categories
User-agent: *
Disallow: 
Disallow: /Api/*
Disallow: /api/*
Disallow: /Search*
Disallow: /search*
Disallow: /Newsletter*
Disallow: /newsletter*

User-agent: msnbot
Crawl-delay: 120

#Block ChatGPT etc.
User-agent: GPTBot
Disallow: /
User-agent: CCBot
Disallow: /