Host: https://atolin.ru
User-agent: *
Disallow: /p/
Disallow: /anketa/messages/
Disallow: /?from=
Disallow: /?
Disallow: /anketa/index
Disallow: /m/
Disallow: /payments
Disallow: /rules
Disallow: /feedback
Disallow: /oferta
Disallow: /cities/moskow
Disallow: /anketa
Disallow: /profile
Disallow: /site
Disallow: /reg
Disallow: /register
Disallow: www.atolin.ru
Disallow: *.svg
Disallow: /payment
Disallow: /paystm
