User-agent: *
Disallow: /config/
Disallow: /data/
Disallow: /monitor/
Disallow: /wps/wcm/connect/bldsysteem/belastingdienst/foutmeldingen/
Disallow: /wps/wcm/connect/bldontwerp/
Disallow: /wps/wcm/connect/bldcontentnl/niet_in_enig_menu/toeslagen/
Disallow: /wps/wcm/connect/bldcontentnl/niet_in_enig_menu/redirects/
Disallow: /wps/wcm/connect/bldcontentnl/niet_in_enig_menu/proevenonlinedienstverlening/
Disallow: /wps/wcm/connect/bldcontentnl/niet_in_enig_menu/inloggen_op/
Disallow: /wps/wcm/connect/bldcontentnl/niet_in_enig_menu/bijzondere_situaties/
Disallow: /wps/wcm/connect/bldcontentnl/berichten/nieuws/rss/nieuwsfeed_actueel_douane.xml
Disallow: /wps/wcm/connect/bldcontentnl/berichten/nieuws/rss/nieuwsfeed_actueel_intermediairs.xml
Disallow: /wps/wcm/connect/bldcontentnl/berichten/nieuws/rss/nieuwsfeed_actueel_particulier.xml
Disallow: /wps/wcm/connect/bldcontentnl/berichten/nieuws/rss/nieuwsfeed_actueel_zakelijk.xml
Disallow: /wps/wcm/connect/bldcontentnl/berichten/berichten.json
Disallow: /wps/wcm/connect/bldcontentde/themaoverstijgend/nachrichten/rss/newsfeed_privatpersonen.xml
Disallow: /wps/wcm/connect/bldcontentde/themaoverstijgend/nachrichten/rss/newsfeed_unternehmen.xml
Disallow: /wps/wcm/connect/bldcontenten/themaoverstijgend/news/rss/newsfeed_individuals.xml
Disallow: /wps/wcm/connect/bldcontenten/themaoverstijgend/news/rss/newsfeed_business.xml
Disallow: /wps/wcm/connect/bldcontenten/themaoverstijgend/news/rss/newsfeed_customs.xml
Disallow: /wps/wcm/connect/bldcontentde/themaoverstijgend/programme_und_formulare/f_42.html
Disallow: /wps/wcm/connect/bldcontentde/themaoverstijgend/programme_und_formulare/g_42.html
Disallow: /wps/wcm/connect/bldcontentde/themaoverstijgend/programme_und_formulare/g_52.html
Disallow: /wps/wcm/connect/bldcontenten/themaoverstijgend/applications_and_forms/f_41.html
Disallow: /wps/wcm/connect/bldcontenten/themaoverstijgend/applications_and_forms/g_41.html
Disallow: /wps/wcm/connect/bldcontenten/themaoverstijgend/applications_and_forms/g_51.html
Disallow: /wps/wcm/connect/bldcontentnl/themaoverstijgend/programmas_en_formulieren/f_40.html
Disallow: /wps/wcm/connect/bldcontentnl/themaoverstijgend/programmas_en_formulieren/g_40.html
Disallow: /wps/wcm/connect/bldcontentnl/themaoverstijgend/programmas_en_formulieren/g_50.html
Disallow: /wps/wcm/connect/bldontwerp/bld/npg-next/video_data.json
Disallow: /wps/wcm/connect/bldontwerp/bld/npg-next-v1/video_data.json
Disallow: /wps/wcm/connect/bldcontentnl/berichten/berichten_uitgebreid.json
Disallow: /wps/wcm/connect/nl/ab/
Disallow: /wps/wcm/connect/nl/instagram/
Disallow: /wps/wcm/connect/nl/layouts/menu
Disallow: /wps/wcm/connect/en/layouts/menu
Disallow: /wps/wcm/connect/de/layouts/menu
Disallow: /wps/wcm/connect/nl/test_compleet
Disallow: /bibliotheek/handboeken/html/boeken/HD/
Disallow: /common/maa/
Disallow: /common/mkt/
Sitemap: https://www.belastingdienst.nl/wps/wcm/connect/bldsysteem/belastingdienst/seo/sitemap.xml