User-agent: *
Disallow: /app_data/
Disallow: /app_plugins/
Disallow: /bin/
Disallow: /config/
Disallow: /data/
Disallow: /umbraco/
Disallow: /views/
Sitemap: https://www.billit.eu/sitemap.xml
Sitemap: https://www.billit.eu/nl-be/billit-is-120-procent-fiscaal-aftrekbaar-slim-factureren-dubbel-profiteren/sitemap.xml
Sitemap: https://www.billit.eu/nl-be/e-facturatie-voor-kmo-s/sitemap.xml
Sitemap: https://www.billit.eu/nl-be/e-facturatie-voor-zelfstandigen-en-freelancers/sitemap.xml
Sitemap: https://www.billit.eu/de-be/sitemap.xml
Sitemap: https://www.billit.eu/nl-be/wedstrijdreglement/sitemap.xml
Sitemap: https://www.billit.eu/nl-be/e-facturen-versturen-via-peppol/sitemap.xml
Sitemap: https://www.billit.eu/nl-be/billit-is-120-procent-fiscaal-aftrekbaar-tot-eind-2027/sitemap.xml
Sitemap: https://www.billit.eu/fr-be/e-facturation-pour-indépendants-et-freelances/sitemap.xml
Sitemap: https://www.billit.eu/en-int/sitemap.xml
Sitemap: https://www.billit.eu/fr-be/e-facturation-pour-pme/sitemap.xml
Sitemap: https://www.billit.eu/fr-be/envoyer-des-factures-électroniques-via-peppol/sitemap.xml
Sitemap: https://www.billit.eu/fr-be/sitemap.xml
Sitemap: https://www.billit.eu/nl-nl/sitemap.xml
Sitemap: https://www.billit.eu/de-de/sitemap.xml
Sitemap: https://www.billit.eu/nl-be/sitemap.xml
Sitemap: https://www.billit.eu/fr-lu/sitemap.xml
Sitemap: https://www.billit.eu/de-lu/sitemap.xml
