User-agent: *
Disallow: /add
Disallow: /go/
Disallow: /goods/
Disallow: /*search_type=
Disallow: /*order_by=
Disallow: /*districtward
Disallow: */stats
Disallow: /*reference
Disallow: /sellers
Disallow: /*opinion
Disallow: /info
Disallow: /*/demands
Disallow: /*openstat=
Disallow: /*utm_*
Disallow: /dashboard
Disallow: /users
Disallow: /search_offers
Disallow: /*request
Disallow: /*/links
Disallow: /*products_region=
Disallow: /*.xls
Disallow: /*search/
Disallow: *filter[local]=1
Disallow: /karta
Disallow: /ajax
Disallow: /predl_ajax
Disallow: /*stats/
Disallow: /*another
Disallow: /*quick
Disallow: /firms/*/page/sellers
Disallow: /firms/*/showcase/new
Disallow: /cart
Disallow: /imageview
Disallow: /crossdomain_authentication
Disallow: */ajax-traits-filter
Disallow: /api/
Disallow: /*?*
Disallow: /wishlist
Disallow: */tenders/t_*
Allow: /sellers/
Allow: /sellers/reklama
Allow: /sellers/response
Allow: /sellers/webinar
Allow: /sellers/banner
Allow: /sellers/create_a_website
Allow: /sellers/FAQ
Allow: /sellers/blogs
Allow: /sellers/about/business/ugc/examples
Allow: /*?page=
Disallow: /sellers/*?*
Disallow: /company_wizard/*page*
Allow: *?traits=*

User-agent: bingbot
Disallow: /add
Disallow: /go/
Disallow: /goods/
Disallow: /*search_type=
Disallow: /*order_by=
Disallow: /*districtward
Disallow: */stats
Disallow: /*reference$
Disallow: /sellers
Disallow: /*opinion
Disallow: /info
Disallow: /*/demands
Disallow: /*openstat=
Disallow: /*utm_source=
Disallow: /dashboard
Disallow: /users
Disallow: /search_offers
Disallow: /*request$
Disallow: /*/links$
Disallow: /*products_region=
Disallow: /*.xls$
Disallow: /*search/
Disallow: *filter[local]=1
Disallow: /karta
Disallow: /ajax
Disallow: /predl_ajax
Disallow: /*stats/
Disallow: /*another$
Disallow: /*adsense.html
Disallow: /*adsense1.html
Disallow: /*quick$
Disallow: /firms/*/page/sellers
Disallow: /firms/*/showcase/new
Disallow: /cart
Disallow: /imageview
Disallow: /crossdomain_authentication
Disallow: */ajax-traits-filter
Disallow: /api/
Disallow: /*?*
Disallow: /wishlist
Disallow: */tenders/t_*
Allow: /sellers/
Allow: /sellers/reklama
Allow: /sellers/response
Allow: /sellers/webinar
Allow: /sellers/banner
Allow: /sellers/create_a_website
Allow: /sellers/FAQ
Allow: /sellers/blogs
Allow: /sellers/about/business/ugc/examples
Allow: /company_reviews
Allow: /company_wizard/new
Allow: /*?page=
Disallow: /sellers/*?*
Disallow: /company_wizard/*page*
Allow: *?traits=*

User-agent: Yandex
Disallow: /add
Disallow: /go/
Disallow: /goods/
Disallow: /*search_type=
Disallow: /*order_by=
Disallow: /*districtward
Disallow: */stats
Disallow: /*reference
Disallow: /sellers
Disallow: /*opinion
Disallow: /info
Disallow: /*/demands
Disallow: /dashboard
Disallow: /users
Disallow: /search_offers
Disallow: /*request
Disallow: /*/links
Disallow: /*products_region=
Disallow: /*.xls
Disallow: /*search/
Disallow: *filter[local]=1
Disallow: /karta
Disallow: /ajax
Disallow: /predl_ajax
Disallow: /*stats/
Disallow: /*another
Disallow: /*quick
Disallow: /firms/*/page/sellers
Disallow: /firms/*/showcase/new
Disallow: /cart
Disallow: /imageview
Disallow: /crossdomain_authentication
Disallow: */ajax-traits-filter
Disallow: /amp/*
Disallow: */amp/*?page=*
Disallow: /api/
Disallow: /*?*
Disallow: /wishlist
Disallow: */tenders/t_*
Allow: /sellers/
Allow: /sellers/reklama
Allow: /sellers/response
Allow: /sellers/webinar
Allow: /sellers/banner
Allow: /sellers/create_a_website
Allow: /sellers/FAQ
Allow: /sellers/blogs
Allow: /sellers/about/business/ugc/examples
Allow: /*?page=
Allow: *?ad_id*
Disallow: /sellers/*?*
Disallow: /company_wizard/*page*
Allow: *?traits=*
Clean-param: traits&list
Clean-param: utm_medium&utm_source&utm_campaign&utm_term&utm_content&openstat&yclid&gclid&pc&ad_id&campaign_id&company_id&ad_id_2
Clean-param: area&page_com&device

User-agent: Googlebot
Disallow: /add
Disallow: /go/
Disallow: /goods/
Disallow: /*search_type=
Disallow: /*order_by=
Disallow: /*districtward
Disallow: /*stats*
Disallow: /*reference
Disallow: /sellers
Disallow: /*opinion
Disallow: /info
Disallow: /*/demands
Disallow: /*openstat=
Disallow: /*utm_*
Disallow: /dashboard
Disallow: /users
Disallow: /search_offers
Disallow: /*request
Disallow: /*/links
Disallow: /*products_region=
Disallow: /*.xls
Disallow: /*search/
Disallow: *filter[local]=1
Disallow: /karta
Disallow: /ajax
Disallow: /predl_ajax
Disallow: /*stats/
Disallow: /*another
Disallow: /*quick
Disallow: /firms/*/page/sellers
Disallow: /firms/*/showcase/new
Disallow: /cart
Disallow: /imageview
Disallow: /crossdomain_authentication
Disallow: */ajax-traits-filter
Disallow: /api/
Disallow: /*?*
Disallow: /wishlist
Disallow: */tenders/t_*
Allow: /sellers/
Allow: /sellers/reklama
Allow: /sellers/response
Allow: /sellers/webinar
Allow: /sellers/banner
Allow: /sellers/create_a_website
Allow: /sellers/FAQ
Allow: /sellers/blogs
Allow: /sellers/about/business/ugc/examples
Allow: /*?page=
Disallow: /sellers/*?*
Disallow: /company_wizard/*page*
Allow: *?traits=*
Allow: *?ad_id*

User-agent: SemrushBot
Disallow: /

User-agent: GPTBot
Disallow: /

User-agent: ChatGPT-User
Disallow: /

User-agent: SemrushBot
Disallow: /

User-agent: Google-Extended
Disallow: /

User-agent: ClaudeBot
Disallow: /

User-agent: Claude-Web
Disallow: /

Host: https://blizko.ru


