

<!DOCTYPE html>
<!--[if lt IE 9]>      <html class="preload no-js oldie" data-srvid="130.131.32"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="preload no-js" data-srvid="130.131.32">
<!--<![endif]-->
<head>
    <title>Βοήθεια - Θα πρέπει με λύπη μας να σας ενημερώσουμε ότι η διεύθυνση IP έχει φραγεί</title>
    <!--[if lt IE 9]><script src="/HelpV3/Web/scripts/modernizr.js"></script><![endif]-->
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport">
<meta content="noindex, nofollow" name="robots">
<link rel="apple-touch-icon" sizes="180x180" href="-/media/31D1268CCAB24872B30A2417B435E21F.ashx">
<link rel="icon" type="image/png" sizes="32x32" href="-/media/9778FA7E25D446D58A3029FDBF9EAA1E.ashx">
<link rel="icon" type="image/png" sizes="16x16" href="-/media/3EFA107CACEA4E97BEB0A87FB3F7F678.ashx">
<link rel="shortcut icon" href="-/media/EBF98A905D424BCC87D708F2EF2C0C0E.ashx">
<meta name="format-detection" content="telephone=no">
<link href="https://scmedia.bwin.gr/$-$/d814c9305c15436185ea2a9dcb0d7716.css" rel="stylesheet" type="text/css" />

    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700&subset=latin,greek,cyrillic" rel="stylesheet" type="text/css">
    
    <!--[if gt IE 8]>
    <style type="text/css">
        #m-navigation #option-list li {
            display: inline-block\0;
            width: 33%\0;
        }
    </style>
    <!--<![endif]-->
</head>
<body class="cf active-content">

    <header class="header">
        <div class="regulatory-header">
            
        </div>
        <menu role="menubar" class="navigation-menu top-menu cf">
            <nav class="menu-left">
                <a href="#" class="theme-help-menu"></a>
            </nav>
                <div id="search-icon">
                    <span class="theme-search">
                    </span>
                </div>
            <h2>
                <a href="http://help.bwin.gr/closed">bwin<span>Βοήθεια</span></a>
            </h2>
            <nav class="menu-right">
                <a href="#" class="theme-close-i"></a>
            </nav>
        </menu>
    </header>


        <div id="language-switch" role="navigation">
            <div class="overlay"></div>
            <div class="list">
                <div class="content minimum">
                    <ul>
                            <li>
                                    <span>Ελληνικά</span>
                            </li>
                            <li>
                                    <a href="/en/closed">English</a>
                            </li>
                    </ul>
                </div>
            </div>
            <div class="current">
                <a href="#">EL<span></span></a>
            </div>
        </div>

        <form id="search-form" onkeypress="return event.keyCode != 13;">
            <div class="search-bar">
                <div class="overlay"></div>

                <div class="search-fields">
                    <input id="searchInput" autofocus type="text" placeholder="Αναζήτηση θεμάτων βοηθείας" data-lang="el" data-virtual-lang="" />
                </div>

                <div class="search-results">
                    <ul class="search-result-list" id="searchresultlist"></ul>

                    <div class="toggle-collapsible">
                        <div class="theme-toggle-button" id="searchResultToggle"></div>
                    </div>
                </div>
            </div>
        </form>

    <menu role="menu" class="navigation-menu sub-menu" style="display: block">
        <nav class="menu-left">
            <a href="#" class="theme-left" id="innerBack" data-depth="1"></a>
        </nav>
        <header>
            <h2>Θα πρέπει με λύπη μας να σας ενημερώσουμε ότι η διεύθυνση IP έχει φραγεί</h2>
        </header>
    </menu>
        <nav role="navigation" class="navigation main-navigation" style="display: block;">
            
        </nav>
            <div role="main" class="main" style="display: block;">
            <div class="wrapper cf">
                <a id="top"></a>


                    <section id="secTNC" class="content">
        <article>


            <style type="text/css">
    #search-form, nav.menu-left, #search-icon, .navigation-menu.sub-menu, nav.navigation.main-navigation, #language-switch {display:none!important}
    div.main {margin:0 auto !important; width:100%!important;}
    section.content {max-width:800px!important; margin: 0 auto !important; float:none !important; border:none!important;}    
</style>
<p><img height="261" alt="blocked-bwin" width="725" src="https://media.itsfogo.com/media/sccmsupload/Vanilla/Whitelabel/App/Help/blocked-bwin.jpg"></p>
<p>Αγαπητέ επισκέπτη!</p>
<p>Oι υπηρεσίες της παρούσας δικτυακής τοποθεσίας δεν είναι πλέον διαθέσιμες για πελάτες που διαμένουν στη χώρα σας. Επίσης, δεν αποδεχόμαστε πλέον καταθέσεις ή συμμετοχή σε παιχνίδια από την περιοχή δικαιοδοσίας από την οποία προσπαθήσατε να εγγραφείτε ή να συνδεθείτε. Εάν διατηρείτε λογαριασμό πραγματικών χρημάτων, θα έχετε πρόσβαση στο υπόλοιπό σας και θα μπορείτε να κάνετε ανάληψη αυτού υποβάλλοντας σχετικό αίτημα στο <a href="mailto:support@bwin.gr">support@bwin.gr</a>. Ο αποκλεισμός βασίζεται στη διεύθυνση IP του υπολογιστή από τον οποίο επιχειρείτε πρόσβαση στη δικτυακή τοποθεσία μας, ο οποίος υποδεικνύει την τοποθεσία σας.</p>
<p>Είμαστε στη δυσάρεστη θέση να σας ενημερώσουμε ότι αυτή τη στιγμή είμαστε υποχρεωμένοι να θέσουμε φραγή στην πρόσβασή σας στη δικτυακή τοποθεσία μας για όσο διάστημα επιχειρείτε να έχετε πρόσβαση από αυτή τη χώρα.</p>

<p>Η ομάδα bwin </p>
<p>
<h2>Συχνά ερωτήματα</h2>
<h3>Πώς μπορείτε να εντοπίσετε που βρίσκομαι αυτή τη στιγμή;</h3>
<p>Το λογισμικό μας εντοπίζει την τρέχουσα τοποθεσία σας βάσει τη διεύθυνσης IP σας. Εφόσον η διεύθυνσή IP σας αποδίδεται στη χώρα σας, δυστυχώς είμαστε υποχρεωμένοι να σας αποκλείουμε από τη χρήση της προσφοράς games μας.</p>
<h3>Τι είναι η διεύθυνση IP;</h3>
<p>Η διεύθυνση IP είναι μια διεύθυνση σε ένα δίκτυο υπολογιστών, η οποία -όπως για παράδειγμα και το Ίντερνετ- βασίζεται στο πρωτόκολλο Ίντερνετ (IP). Κάθε υπολογιστής που έχει πρόσβαση στο Ίντερνετ, μπορεί να εντοπιστεί σαφώς από αυτό το συνδυασμό αριθμών (στον οποίο τα νούμερα διαχωρίζονται πάντα σε τρεις περιόδους όπως 179.89.72.9).</p>
<h3>Πόσο αξιόπιστη είναι η τεχνολογία Geo-IP;</h3>
<p>Δυστυχώς, το τεχνολογικό σύστημα Geo-IP δεν εγγυάται 100% ακρίβεια στον εντοπισμό της τοποθεσίας σας. Θα βελτιώσουμε την ακρίβεια του τεχνολογικού συστήματος Geo-IP με διαρκείς ενημερώσεις. Εάν το λογισμικό Geo-IP σας τοποθέτησε εσφαλμένα σε χώρα η οποία δεν είναι η σωστή τοποθεσία ας ή εάν βρίσκεστε σε χώρα που δεν εξαιρείται από την προσφορά προϊόντων μας, παρακαλούμε επικοινωνήστε με το Τμήμα Εξυπηρέτησης Πελατών ώστε να βελτιώσουμε περαιτέρω την ακρίβεια του συστήματος Geo-IP μας.</p>
<p>
<p><style type="text/css">.pm-area-navigation{display:none!important}.container{width:100%;max-width:740px;margin:0 auto}#header{width:100%}#header .header-bar{width:auto; display: none}#main-wrap{width:100%;max-width:740px;padding:10px 1% 10px 1%;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;-ms-box-sizing:border-box;box-sizing:border-box}.sub-navigation{width:100%;max-width:700px;overflow:hidden;display:none}#main{width:100%}.pm-nav-layout .pm-area-main{width:100%}.pm-area-main>div.pm-widget-box{margin-right:0}.text>p>img{display:block;margin:0 auto;height:auto}#footer{width:98%;padding:0 1%}#footer .copyright{width:50%;max-width:740px;margin-top:-10px;float:right}.language-switch{width:25%;margin-top:0}#footer .meta-navigation{width:25%;margin-left:0}#footer .meta-navigation>ul#footer-navigation{position:static}#footer .language-switch .selector{width:100px}</style></p>

        </article>
    </section>
            </div>
        </div>



    <script type="text/javascript">
        var preLoadedResults =null;
var min = 3;var max = 30;    </script>

    <script src="https://scmedia.bwin.gr/$-$/48c8f130767e45e5b60f30b4c1d3246f.js" type="text/javascript">

</script>



    
        <script type="text/javascript">
            $(document).ready(function () {
                $("html").on("click", "#language-switch .current", function () {
                    $("#language-switch .list").toggle();
                    $("#language-switch .overlay").toggle();
                    $("body").toggleClass("ls-open");
                });

                $("html").on("click", ".ls-open #language-switch, .ls-open #language-switch .current", function () {
                    $("#language-switch .list").toggle();
                    $("#language-switch .overlay").toggle();
                    $("body").toggleClass("ls-open");
                });
                        
            });

            // Hide LanguageSwitcher by clicking outside
            $(document).click(function (event) {
            });
        </script>


</body>
</html>