User-agent: *
Disallow: /banners
Disallow: /m/
Disallow: /js/
Disallow: /client/
Disallow: /forms/
Disallow: /*/embed*
Disallow: /*/gallery*
Disallow: /*/wall*
Disallow: /*/gifts*
Disallow: /*/fanclub*
Disallow: /*/myshop*
Disallow: /legal
Disallow: /checkout
Disallow: /cam4ultimate
User-agent: ia_archiver
Disallow: /
Sitemap: https://es.cam4.com/sitemap.xml
