User-agent: *
Crawl-delay: 1
Disallow: /en-gb/participants-survey/businesses/form-pages/your-request-has-successfully-been-sent-
Disallow: /nl-nl/deelnemers-enquetes/bedrijven/formulier-paginas/bedankt-voor-het-insturen
Disallow: /nl-nl/deelnemers-enquetes/decentrale-overheden/overzicht/wet-inburgering/bedankt
Disallow: /en-gb/participants-survey/businesses/form-pages/your-request-has-been-sent-
Disallow: /nl-nl/deelnemers-enquetes/bedrijven/formulier-paginas/uw-verzoek-is-verstuurd-
Disallow: /nl-nl/deelnemers-enquetes/bedrijven/formulier-paginas/bedankt-uw-verzoek-is-verstuurd
Disallow: /nl-nl/maatschappij/veiligheid-en-recht/veiligheidsmonitor/het-formulier-is-verzonden-
Disallow: /nl-nl/deelnemers-enquetes/veilig-in-het-veld
Disallow: /nl-nl/deelnemers-enquetes/veilig-in-het-veld/training-links-en-telefoonnummers
Disallow: /nl-nl/deelnemers-enquetes/veilig-in-het-veld/wat-te-doen-bij-incidenten
Disallow: /nl-nl/deelnemers-enquetes/veilig-in-het-veld/incidenten-voorkomen
Disallow: /nl-nl/deelnemers-enquetes/veilig-in-het-veld/nazorg-en-opvang
Disallow: /en-gb/participants-survey/veilig-in-het-veld/faq-overzichtspagina
Disallow: /nl-nl/deelnemers-enquetes/veilig-in-het-veld/veelgestelde-vragen-personen
Disallow: /nl-nl/deelnemers-enquetes/decentrale-overheden/decentrale-overheid/doodsoorzaak/bestellen-van-b-verklaringen-en-telkaarten
Disallow: /nl-nl/deelnemers-enquetes/bedrijven/meer-over-cbs-enquetes/zorgaanbieders/uitvoeringsverordening
Disallow: /nl-nl/arbeid-en-inkomen/arbeid-en-sociale-zekerheid/barometer-culturele-diversiteit/webformulier-barometer-culturele-diversiteit-ingezoomde-variant
Disallow: /nl-nl/arbeid-en-inkomen/arbeid-en-sociale-zekerheid/barometer-culturele-diversiteit/wij-hebben-uw-gegevens-ontvangen
Disallow: /nl-nl/arbeid-en-inkomen/arbeid-en-sociale-zekerheid/barometer-culturele-diversiteit/webformulier-barometer-culturele-diversiteit-algemene-variant
Disallow: /en-gb/labour-and-income/labour-and-social-security/barometer-culturele-diversiteit/faq-overzichtspagina
Disallow: /nl-nl/arbeid-en-inkomen/arbeid-en-sociale-zekerheid/barometer-culturele-diversiteit/veelgestelde-vragen-barometer-culturele-diversiteit
Disallow: /nl-nl/arbeid-en-inkomen/arbeid-en-sociale-zekerheid/barometer-culturele-diversiteit/herkomstindeling-barometer-culturele-diversiteit
Disallow: /nl-nl/statline/dataportaal/general/general-settings/reagerenurl
Disallow: /en-gb/statline/dataportaal/general/dataportaal/cbsapiurl
Disallow: /nl-nl/statline/dataportaal/general/general-settings/cbsapiurl
Disallow: /en-gb/statline/dataportaal/general/dataportaal/copyright
Disallow: /nl-nl/statline/dataportaal/general/general-settings/copyright
Disallow: /en-gb/statline/dataportaal/general/dataportaal/backgroundappurl
Disallow: /nl-nl/statline/dataportaal/general/general-settings/backgroundappurl
Disallow: /en-gb/statline/dataportaal/general/dataportaal/recenturl
Disallow: /nl-nl/statline/dataportaal/general/general-settings/recenturl
Disallow: /en-gb/statline/dataportaal/general/dataportaal/portaltitle
Disallow: /nl-nl/statline/dataportaal/general/general-settings/portaltitle
Disallow: /en-gb/statline/dataportaal/general/dataportaal/dataportaal
Disallow: /nl-nl/statline/dataportaal/general/general-settings/dataportaal
Disallow: /en-gb/statline/dataportaal/general/dataportaal/apptitle
Disallow: /nl-nl/statline/dataportaal/general/general-settings/apptitle
Disallow: /en-gb/statline/dataportaal/general/dataportaal/mainsite_url
Disallow: /nl-nl/statline/dataportaal/general/general-settings/mainsite_url
Disallow: /en-gb/statline/dataportaal/general/dataportaal/mainsite
Disallow: /nl-nl/statline/dataportaal/general/general-settings/mainsite
Disallow: /en-gb/statline/dataportaal/general/dataportaal/dataportaal_text
Disallow: /nl-nl/statline/dataportaal/general/general-settings/dataportaal_text
Disallow: /nl-nl/statline/rivm/general/general-settings
Disallow: /nl-nl/statline/rivm/homepage/ontdek-cijfers-per-thema
Disallow: /nl-nl/statline/rivm/homepage/open-data
Disallow: /nl-nl/statline/rivm/homepage/recente-publicaties
Disallow: /nl-nl/statline/rivm/homepage/statline-rivm
Disallow: /nl-nl/statline/rivm/homepage/rivm
Disallow: /nl-nl/statline/rivm/general/general-settings/portalmobiletitle
Disallow: /nl-nl/statline/rivm/general/general-settings/payoff
Disallow: /nl-nl/statline/rivm/general/general-settings/mainsite_text
Disallow: /nl-nl/statline/rivm/general/general-settings/portaltitle
Disallow: /nl-nl/statline/rivm/general/general-settings/cbsapiurl
Disallow: /nl-nl/statline/rivm/general/general-settings/backgroundappurl
Disallow: /nl-nl/statline/rivm/general/general-settings/helpurl
Disallow: /nl-nl/statline/rivm/general/general-settings/dataportaal_url
Disallow: /nl-nl/statline/rivm/general/general-settings/rivm-data-en-statline
Disallow: /nl-nl/statline/rivm/general/general-settings/appmobiletitle
Disallow: /nl-nl/statline/rivm/general/general-settings/appadditionaltitle
Disallow: /nl-nl/statline/rivm/general/general-settings/mainsite_url
Disallow: /nl-nl/statline/rivm/general/general-settings/korteuitleg
Disallow: /nl-nl/statline/rivm/general/general-settings/copyright
Disallow: /nl-nl/statline/rivm/general/general-settings/apptitle
Disallow: /nl-nl/statline/rivm/general/general-settings/dataportaal_text
Disallow: /nl-nl/statline/rivm/general/general-settings/reagerenurl
Disallow: /nl-nl/statline/jm/general/general-settings
Disallow: /nl-nl/statline/jm/homepage/jeugdmonitor
Disallow: /nl-nl/statline/jm/homepage/statline-jeugdmonitor
Disallow: /nl-nl/statline/jm/homepage/grafieken-en-kaarten
Disallow: /nl-nl/statline/jm/homepage/zoek-op-trefwoord
Disallow: /nl-nl/statline/jm/general/general-settings/appadditionaltitle
Disallow: /nl-nl/statline/jm/general/general-settings/apptitle
Disallow: /nl-nl/statline/jm/general/general-settings/backgroundappurl
Disallow: /nl-nl/statline/jm/general/general-settings/helpurl
Disallow: /nl-nl/statline/jm/general/general-settings/mainsite_url
Disallow: /nl-nl/statline/jm/general/general-settings/mainsite_text
Disallow: /nl-nl/statline/jm/general/general-settings/reagerenurl
Disallow: /nl-nl/statline/jm/general/general-settings/copyright
Disallow: /nl-nl/statline/jm/general/general-settings/dataportaal_url
Disallow: /nl-nl/statline/jm/general/general-settings/korteuitleg
Disallow: /nl-nl/statline/jm/general/general-settings/portaltitle
Disallow: /nl-nl/statline/jm/general/general-settings/appmobiletitle
Disallow: /nl-nl/statline/jm/general/general-settings/cbsapiurl
Disallow: /nl-nl/statline/jm/general/general-settings/dataportaal_text
Disallow: /nl-nl/statline/jm/general/general-settings/payoff
Disallow: /nl-nl/statline/jm/general/general-settings/portalmobiletitle
Disallow: /nl-nl/statline/azw/general/general-settings
Disallow: /nl-nl/statline/azw/homepage/contact
Disallow: /nl-nl/statline/azw/homepage/definities
Disallow: /nl-nl/statline/azw/homepage/open-data
Disallow: /nl-nl/statline/azw/homepage/aanvullend-statistisch-onderzoek
Disallow: /nl-nl/statline/azw/homepage/azw-statline
Disallow: /nl-nl/statline/azw/homepage/azw
Disallow: /nl-nl/statline/azw/general/general-settings/portalmobiletitle
Disallow: /nl-nl/statline/azw/general/general-settings/mainsite_url
Disallow: /nl-nl/statline/azw/general/general-settings/helpurl
Disallow: /nl-nl/statline/azw/general/general-settings/copyright
Disallow: /nl-nl/statline/azw/general/general-settings/cbsapiurl
Disallow: /nl-nl/statline/azw/general/general-settings/dataportaal_url
Disallow: /nl-nl/statline/azw/general/general-settings/korteuitleg
Disallow: /nl-nl/statline/azw/general/general-settings/backgroundappurl
Disallow: /nl-nl/statline/azw/general/general-settings/appmobiletitle
Disallow: /nl-nl/statline/azw/general/general-settings/recenturl
Disallow: /nl-nl/statline/azw/general/general-settings/appadditionaltitle
Disallow: /nl-nl/statline/azw/general/general-settings/mainsite_text
Disallow: /nl-nl/statline/azw/general/general-settings/mainsite
Disallow: /nl-nl/statline/azw/general/general-settings/dataportaal_text
Disallow: /en-gb/statline/azw/general/azw/dataportaal
Disallow: /nl-nl/statline/azw/general/general-settings/dataportaal
Disallow: /nl-nl/statline/azw/general/general-settings/portaltitle
Disallow: /nl-nl/statline/azw/general/general-settings/payoff
Disallow: /nl-nl/statline/azw/general/general-settings/reagerenurl
Disallow: /nl-nl/statline/azw/general/general-settings/apptitle
Disallow: /en-gb/statline/sxstat/general/sint-maarten-statistics
Disallow: /nl-nl/statline/sxstat/general/general-settings
Disallow: /en-gb/statline/sxstat/homepage/statistics-st-maarten
Disallow: /nl-nl/statline/sxstat/homepage/algemeen
Disallow: /en-gb/statline/sxstat/homepage/keyword-search
Disallow: /nl-nl/statline/sxstat/homepage/keyword-search
Disallow: /en-gb/statline/sxstat/homepage/open-data
Disallow: /nl-nl/statline/sxstat/homepage/open-data
Disallow: /en-gb/statline/sxstat/homepage/st-maarten-in-figures
Disallow: /nl-nl/statline/sxstat/homepage/st-maarten-in-figures
Disallow: /en-gb/statline/sxstat/homepage/explanation
Disallow: /nl-nl/statline/sxstat/homepage/explanation
Disallow: /en-gb/statline/sxstat/general/sint-maarten-statistics/achtergrond-voor-dataportal
Disallow: /nl-nl/statline/sxstat/general/general-settings/backgroundappurl
Disallow: /en-gb/statline/sxstat/general/sint-maarten-statistics/appadditionaltitle
Disallow: /nl-nl/statline/sxstat/general/general-settings/appadditionaltitle
Disallow: /nl-nl/statline/sxstat/general/general-settings/cbsapiurl
Disallow: /en-gb/statline/sxstat/general/sint-maarten-statistics/payoff
Disallow: /nl-nl/statline/sxstat/general/general-settings/payoff
Disallow: /nl-nl/statline/sxstat/general/general-settings/portalmobiletitle
Disallow: /nl-nl/statline/sxstat/general/general-settings/reagerenurl
Disallow: /en-gb/statline/sxstat/general/sint-maarten-statistics/appmobiletitle
Disallow: /nl-nl/statline/sxstat/general/general-settings/appmobiletitle
Disallow: /en-gb/statline/sxstat/general/sint-maarten-statistics/korteuitleg
Disallow: /nl-nl/statline/sxstat/general/general-settings/korteuitleg
Disallow: /en-gb/statline/sxstat/general/sint-maarten-statistics/mainsite_url
Disallow: /nl-nl/statline/sxstat/general/general-settings/mainsite_url
Disallow: /en-gb/statline/sxstat/general/sint-maarten-statistics/dataportaal_text
Disallow: /nl-nl/statline/sxstat/general/general-settings/dataportaal_text
Disallow: /en-gb/statline/sxstat/general/sint-maarten-statistics/helpurl
Disallow: /nl-nl/statline/sxstat/general/general-settings/helpurl
Disallow: /en-gb/statline/sxstat/general/sint-maarten-statistics/apptitle
Disallow: /nl-nl/statline/sxstat/general/general-settings/apptitle
Disallow: /nl-nl/statline/sxstat/general/general-settings/portaltitle
Disallow: /en-gb/statline/sxstat/general/sint-maarten-statistics/mainsite_text
Disallow: /nl-nl/statline/sxstat/general/general-settings/mainsite_text
Disallow: /en-gb/statline/sxstat/general/sint-maarten-statistics/dataportaal_url
Disallow: /nl-nl/statline/sxstat/general/general-settings/dataportaal_url
Disallow: /en-gb/statline/sxstat/general/sint-maarten-statistics/copyright
Disallow: /nl-nl/statline/sxstat/general/general-settings/copyright
Disallow: /nl-nl/statline/mlz/homepage/statline-mlz
Disallow: /nl-nl/statline/mlz/homepage/grafieken-en-kaarten
Disallow: /nl-nl/statline/mlz/homepage/mlz
Disallow: /nl-nl/statline/mlz/homepage/zoek-op-trefwoord
Disallow: /nl-nl/statline/mlz/general/general-settings
Disallow: /nl-nl/statline/mlz/general/general-settings/cbsapiurl
Disallow: /nl-nl/statline/mlz/general/general-settings/korteuitleg
Disallow: /nl-nl/statline/mlz/general/general-settings/mainsite_text
Disallow: /nl-nl/statline/mlz/general/general-settings/payoff
Disallow: /nl-nl/statline/mlz/general/general-settings/portalmobiletitle
Disallow: /nl-nl/statline/mlz/general/general-settings/helpurl
Disallow: /nl-nl/statline/mlz/general/general-settings/appadditionaltitle
Disallow: /nl-nl/statline/mlz/general/general-settings/dataportaal_text
Disallow: /nl-nl/statline/mlz/general/general-settings/copyright
Disallow: /nl-nl/statline/mlz/general/general-settings/dataportaal_url
Disallow: /nl-nl/statline/mlz/general/general-settings/portaltitle
Disallow: /nl-nl/statline/mlz/general/general-settings/backgroundappurl
Disallow: /nl-nl/statline/mlz/general/general-settings/apptitle
Disallow: /nl-nl/statline/mlz/general/general-settings/reagerenurl
Disallow: /nl-nl/statline/mlz/general/general-settings/appmobiletitle
Disallow: /nl-nl/statline/mlz/general/general-settings/mainsite_url
Disallow: /nl-nl/statline/politie/homepage/het-dataportaal-van-de-politie
Disallow: /nl-nl/statline/politie/homepage/veelgestelde-vragen
Disallow: /nl-nl/statline/politie/homepage/nieuws
Disallow: /nl-nl/statline/politie/homepage/kaarten-van-wijken-en-buurten
Disallow: /nl-nl/statline/politie/homepage/definities
Disallow: /nl-nl/statline/politie/homepage/open-data
Disallow: /nl-nl/statline/politie/homepage/politie
Disallow: /nl-nl/statline/politie/general/general-settings
Disallow: /nl-nl/statline/politie/general/general-settings/copyright
Disallow: /nl-nl/statline/politie/general/general-settings/mainsite_url
Disallow: /nl-nl/statline/politie/general/general-settings/dataportaal_text
Disallow: /nl-nl/statline/politie/general/general-settings/backgroundappurl
Disallow: /nl-nl/statline/politie/general/general-settings/reagerenurl
Disallow: /nl-nl/statline/politie/general/general-settings/politiedata-en-statline
Disallow: /nl-nl/statline/politie/general/general-settings/payoff
Disallow: /nl-nl/statline/politie/general/general-settings/korteuitleg
Disallow: /nl-nl/statline/politie/general/general-settings/helpurl
Disallow: /nl-nl/statline/politie/general/general-settings/dataportaal_url
Disallow: /nl-nl/statline/politie/general/general-settings/cbsapiurl
Disallow: /nl-nl/statline/politie/general/general-settings/apptitle
Disallow: /nl-nl/statline/politie/general/general-settings/mainsite_text
Disallow: /nl-nl/statline/politie/general/general-settings/portaltitle
Disallow: /nl-nl/statline/politie/general/general-settings/portalmobiletitle
Disallow: /nl-nl/statline/politie/general/general-settings/appmobiletitle
Disallow: /nl-nl/statline/politie/general/general-settings/appadditionaltitle
Disallow: /nl-nl/statline/mvstat/general/general-settings
Disallow: /nl-nl/statline/mvstat/homepage/zoek-het-zelf
Disallow: /nl-nl/statline/mvstat/homepage/statline-m-v
Disallow: /nl-nl/statline/mvstat/homepage/ontdek-cijfers-per-thema
Disallow: /nl-nl/statline/mvstat/general/general-settings/portaltitle
Disallow: /nl-nl/statline/mvstat/general/general-settings/portalmobiletitle
Disallow: /nl-nl/statline/mvstat/general/general-settings/helpurl
Disallow: /nl-nl/statline/mvstat/general/general-settings/dataportaal
Disallow: /nl-nl/statline/mvstat/general/general-settings/backgroundappurl
Disallow: /nl-nl/statline/mvstat/general/general-settings/apptitle
Disallow: /nl-nl/statline/mvstat/general/general-settings/dataportaal_url
Disallow: /nl-nl/statline/mvstat/general/general-settings/payoff
Disallow: /nl-nl/statline/mvstat/general/general-settings/mainsite_url
Disallow: /nl-nl/statline/mvstat/general/general-settings/korteuitleg
Disallow: /nl-nl/statline/mvstat/general/general-settings/dataportaal_text
Disallow: /nl-nl/statline/mvstat/general/general-settings/recenturl
Disallow: /nl-nl/statline/mvstat/general/general-settings/copyright
Disallow: /nl-nl/statline/mvstat/general/general-settings/appadditionaltitle
Disallow: /nl-nl/statline/mvstat/general/general-settings/mainsite_text
Disallow: /nl-nl/statline/mvstat/general/general-settings/mainsite
Disallow: /en-gb/statline/interreg/homepage/grenzuberschreitende-statistik
Disallow: /nl-nl/statline/interreg/homepage/statistieken-over-grensregio-s
Disallow: /en-gb/statline/interreg/homepage/grenzdaten
Disallow: /nl-nl/statline/interreg/homepage/grensdata
Disallow: /en-gb/statline/interreg/homepage/kontakt
Disallow: /nl-nl/statline/interreg/homepage/contact
Disallow: /en-gb/statline/interreg/homepage/interreg
Disallow: /nl-nl/statline/interreg/homepage/interreg
Disallow: /en-gb/statline/interreg/homepage/offene-daten
Disallow: /nl-nl/statline/interreg/homepage/zoek-het-zelf
Disallow: /nl-nl/statline/interreg/general/general-settings
Disallow: /nl-nl/statline/interreg/general/general-settings/cbsapiurl
Disallow: /en-gb/statline/interreg/general/interreg/helpurl
Disallow: /nl-nl/statline/interreg/general/general-settings/helpurl
Disallow: /nl-nl/statline/interreg/general/general-settings/reagerenurl
Disallow: /en-gb/statline/interreg/general/interreg/mainsite_url
Disallow: /nl-nl/statline/interreg/general/general-settings/mainsite_url
Disallow: /en-gb/statline/interreg/general/interreg/apptitle
Disallow: /nl-nl/statline/interreg/general/general-settings/apptitle
Disallow: /en-gb/statline/interreg/general/interreg/dataportaal_text
Disallow: /nl-nl/statline/interreg/general/general-settings/dataportaal_text
Disallow: /en-gb/statline/interreg/general/interreg/payoff
Disallow: /nl-nl/statline/interreg/general/general-settings/payoff
Disallow: /en-gb/statline/interreg/general/interreg/appmobiletitle
Disallow: /nl-nl/statline/interreg/general/general-settings/appmobiletitle
Disallow: /en-gb/statline/interreg/general/interreg/copyright
Disallow: /nl-nl/statline/interreg/general/general-settings/copyright
Disallow: /en-gb/statline/interreg/general/interreg/korteuitleg
Disallow: /nl-nl/statline/interreg/general/general-settings/korteuitleg
Disallow: /en-gb/statline/interreg/general/interreg/mainsite_text
Disallow: /nl-nl/statline/interreg/general/general-settings/mainsite_text
Disallow: /nl-nl/statline/interreg/general/general-settings/portalmobiletitle
Disallow: /nl-nl/statline/interreg/general/general-settings/portaltitle
Disallow: /en-gb/statline/interreg/general/interreg/appadditionaltitle
Disallow: /nl-nl/statline/interreg/general/general-settings/appadditionaltitle
Disallow: /nl-nl/statline/interreg/general/general-settings/backgroundappurl
Disallow: /en-gb/statline/interreg/general/interreg/dataportaal_url
Disallow: /nl-nl/statline/interreg/general/general-settings/dataportaal_url
Disallow: /en-gb/statline/dataportaal/privacy--english--
Disallow: /nl-nl/statline/dataportaal/privacy
Disallow: /en-gb/statline/dataportaal/faq/which-odata-4-commands-are-available-
Disallow: /nl-nl/statline/dataportaal/faq/welke-odata-4-commando-s-zijn-beschikbaar-
Disallow: /nl-nl/statline/dataportaal/faq/wat-zijn-de-belangrijkste-verschillen-tussen-odata3-en-odata4-
Disallow: /en-gb/statline/dataportaal/faq/does-cbs-have-a-helpdesk-for-questions-about-open-data-
Disallow: /nl-nl/statline/dataportaal/faq/heeft-het-cbs-een-helpdesk-voor-vragen-over-open-data-
Disallow: /en-gb/statline/dataportaal/faq/why-do-i-get-a-warning-that-the-browser-may-not-be-able-to-handle-the-csv-download-
Disallow: /nl-nl/statline/dataportaal/faq/waarom-krijg-ik-een-waarschuwing-dat-de-browser-de-csv-download-misschien-niet-kan-verwerken-
Disallow: /en-gb/statline/dataportaal/faq/how-can-i-find-datasets-in-the-data-portal-
Disallow: /nl-nl/statline/dataportaal/faq/hoe-kan-ik-datasets-vinden-in-het-dataportaal-
Disallow: /nl-nl/statline/dataportaal/faq/waarom-krijg-ik-een-oud-csv-bestand-als-download-terwijl-er-een-nieuwe-versie-beschikbaar-is-
Disallow: /en-gb/statline/dataportaal/general/dataportaal
Disallow: /nl-nl/statline/dataportaal/general/general-settings
Disallow: /en-gb/statline/dataportaal/informatie/general-information-on-the-use-of-cbs-open-data
Disallow: /nl-nl/statline/dataportaal/informatie/algemene-informatie-voor-gebruik-van-cbs-open-data
Disallow: /en-gb/statline/dataportaal/informatie/information-for-developers
Disallow: /nl-nl/statline/dataportaal/informatie/informatie-voor-ontwikkelaars
Disallow: /en-gb/statline/dataportaal/informatie/information-for-data-analysts
Disallow: /nl-nl/statline/dataportaal/informatie/informatie-voor-data-analisten
Disallow: /en-gb/statline/dataportaal/homepage/banner/bannerfoto
Disallow: /nl-nl/statline/dataportaal/homepage/banner/bannerfoto
Disallow: /en-gb/statline/dataportaal/homepage/tekstblokken/introduction
Disallow: /nl-nl/statline/dataportaal/homepage/tekstblokken/introductie
Disallow: /en-gb/statline/dataportaal/homepage/tekstblokken/what-are-open-data-
Disallow: /nl-nl/statline/dataportaal/homepage/tekstblokken/wat-zijn-open-data-
Disallow: /en-gb/statline/dataportaal/homepage/tekstblokken/which-data-are-available-
Disallow: /nl-nl/statline/dataportaal/homepage/tekstblokken/welke-data-zijn-er-
Disallow: /en-gb/statline/dataportaal/general/dataportaal/portalmobiletitle
Disallow: /nl-nl/statline/dataportaal/general/general-settings/portalmobiletitle
Disallow: /en-gb/statline/dataportaal/general/dataportaal/korteuitleg
Disallow: /nl-nl/statline/dataportaal/general/general-settings/korteuitleg
Disallow: /en-gb/statline/dataportaal/general/dataportaal/reagerenurl
Disallow: /en-gb/statline/dataportaal/general/dataportaal/appmobiletitle
Disallow: /nl-nl/statline/dataportaal/general/general-settings/appmobiletitle
Disallow: /en-gb/statline/dataportaal/general/dataportaal/dataportaal_url
Disallow: /nl-nl/statline/dataportaal/general/general-settings/dataportaal_url
Disallow: /nl-nl/statline/dataportaal/general/general-settings/appadditionaltitle
Disallow: /en-gb/statline/dataportaal/general/dataportaal/payoff
Disallow: /nl-nl/statline/dataportaal/general/general-settings/payoff
Disallow: /en-gb/statline/dataportaal/general/dataportaal/mainsite_text
Disallow: /nl-nl/statline/dataportaal/general/general-settings/mainsite_text
Disallow: /en-gb/statline/dataportaal/general/dataportaal/helpurl
Disallow: /nl-nl/statline/dataportaal/general/general-settings/helpurl
Disallow: /en-gb/about-us/who-we-are/our-course/overview-of-multi-annual-programmes-and-annual-reports/multi-annual-programmes
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/meerjarenprogramma-s
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen
Disallow: /en-gb/about-us/who-we-are/our-course/overview-of-multi-annual-programmes-and-annual-reports/annual-reports
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen
Disallow: /en-gb/about-us/who-we-are/our-course/overview-of-multi-annual-programmes-and-annual-reports/multi-annual-programmes/multi-annual-programme-2019-2023
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/meerjarenprogramma-s/strategisch-meerjarenprogramma-2019-2023
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/meerjarenprogramma-s/meerjarenprogramma-caribisch-nederland-2020-2023
Disallow: /en-gb/about-us/who-we-are/our-course/overview-of-multi-annual-programmes-and-annual-reports/multi-annual-programmes/strategic-multi-annual-programme-2014-2018
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/meerjarenprogramma-s/strategisch-meerjarenprogramma-2014-2018
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/meerjarenprogramma-s/cbs-meerjarenprogramma-caribisch-nederland-2024-2028
Disallow: /en-gb/about-us/who-we-are/our-course/overview-of-multi-annual-programmes-and-annual-reports/2-jaarplannen/cbs-jaarplan-2025
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/meerjarenprogramma-s/strategisch-meerjarenprogramma-2009-2013
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2025
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2012
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2006
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2016
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2013
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2007
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2024
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2014
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2004
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2011
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2015
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2018
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2010
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2005
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2008
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2017
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2022
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2021
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2019
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2020
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarplannen/cbs-jaarplan-2009
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2008
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-duurzaamheidsverslag-2024
Disallow: /en-gb/about-us/who-we-are/our-course/overview-of-multi-annual-programmes-and-annual-reports/annual-reports/annual-report-statistics-netherlands-2012
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2013
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2012
Disallow: /en-gb/about-us/who-we-are/our-course/overview-of-multi-annual-programmes-and-annual-reports/annual-reports/annual-report
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/annual-report
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2004
Disallow: /en-gb/about-us/who-we-are/our-course/overview-of-multi-annual-programmes-and-annual-reports/annual-reports/annual-report-2018
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2018
Disallow: /en-gb/about-us/who-we-are/our-course/overview-of-multi-annual-programmes-and-annual-reports/annual-reports/annual-report-2010
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/annual-report-2010
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2017
Disallow: /en-gb/about-us/who-we-are/our-course/overview-of-multi-annual-programmes-and-annual-reports/annual-reports/annual-report-2021
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2021
Disallow: /en-gb/about-us/who-we-are/our-course/overview-of-multi-annual-programmes-and-annual-reports/annual-reports/annual-report-2023
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2023
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2005
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2009
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2011
Disallow: /en-gb/about-us/who-we-are/our-course/overview-of-multi-annual-programmes-and-annual-reports/annual-reports/annual-report-for-2014
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/annual-report-for-2014
Disallow: /en-gb/about-us/who-we-are/our-course/overview-of-multi-annual-programmes-and-annual-reports/annual-reports/annual-report-2009
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/annual-report-2009
Disallow: /en-gb/about-us/who-we-are/our-course/overview-of-multi-annual-programmes-and-annual-reports/annual-reports/annual-report-2007
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/annual-report-2007
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2024
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2010
Disallow: /en-gb/about-us/who-we-are/our-course/overview-of-multi-annual-programmes-and-annual-reports/annual-reports/annual-report-2008
Disallow: /en-gb/about-us/who-we-are/our-course/overview-of-multi-annual-programmes-and-annual-reports/annual-reports/annual-report-2022
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/annual-report-2008
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2022
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2016
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2015
Disallow: /en-gb/about-us/who-we-are/our-course/overview-of-multi-annual-programmes-and-annual-reports/annual-reports/annual-report-2019
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2014
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2019
Disallow: /en-gb/about-us/who-we-are/our-course/overview-of-multi-annual-programmes-and-annual-reports/annual-reports/annual-report-2020
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2020
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2006
Disallow: /nl-nl/over-ons/dit-zijn-wij/onze-koers/overzicht-jaarplannen-en-jaarverslagen/jaarverslagen/cbs-jaarverslag-2007
Disallow: /nl-nl/over-ons/contact/evaluatie-werkbezoek
Disallow: /en-gb/about-us/contact/how-do-you-rate-our-service-
Disallow: /nl-nl/over-ons/contact/hoe-beoordeelt-u-onze-dienstverlening-
Disallow: /en-gb/about-us/contact/how-do-you-rate-our-service-/thank-you-for-your-effort
Disallow: /nl-nl/over-ons/contact/hoe-beoordeelt-u-onze-dienstverlening-/dank-voor-uw-moeite
Disallow: /en-gb/errors/500-error
Disallow: /nl-nl/errors/500-error
Disallow: /en-gb/errors/this-content-is--currently---only-available-in-dutch
Disallow: /nl-nl/errors/vertaling-niet-beschikbaar
Disallow: /en-gb/errors/sorry-we-cannot-find-the-page-you-are-looking-for
Disallow: /nl-nl/errors/we-kunnen-de-pagina-die-je-zoekt-niet-vinden
Disallow: /nl-nl/statline/mvstat/general/general-settings/cbsapiurl
Disallow: /nl-nl/statline/mvstat/general/general-settings/appmobiletitle
Disallow: /nl-nl/statline/mkb/homepage/mkb
Disallow: /nl-nl/statline/mkb/homepage/ontdek-cijfers-per-thema
Disallow: /nl-nl/statline/mkb/homepage/zoek-het-zelf
Disallow: /nl-nl/statline/mkb/homepage/statline-mkb
Disallow: /nl-nl/statline/mkb/general/general-settings
Disallow: /nl-nl/statline/mkb/general/general-settings/backgroundappurl
Disallow: /nl-nl/statline/mkb/general/general-settings/copyright
Disallow: /nl-nl/statline/mkb/general/general-settings/dataportaal_text
Disallow: /nl-nl/statline/mkb/general/general-settings/dataportaal_url
Disallow: /nl-nl/statline/mkb/general/general-settings/mainsite_text
Disallow: /nl-nl/statline/mkb/general/general-settings/mainsite_url
Disallow: /nl-nl/statline/mkb/general/general-settings/portalmobiletitle
Disallow: /nl-nl/statline/mkb/general/general-settings/reagerenurl
Disallow: /nl-nl/statline/mkb/general/general-settings/payoff
Disallow: /nl-nl/statline/mkb/general/general-settings/appadditionaltitle
Disallow: /nl-nl/statline/mkb/general/general-settings/apptitle
Disallow: /nl-nl/statline/mkb/general/general-settings/korteuitleg
Disallow: /nl-nl/statline/mkb/general/general-settings/appmobiletitle
Disallow: /nl-nl/statline/mkb/general/general-settings/cbsapiurl
Disallow: /nl-nl/statline/mkb/general/general-settings/helpurl
Disallow: /nl-nl/statline/mkb/general/general-settings/portaltitle
Disallow: /en-gb/statline/cbs/general/general-settings
Disallow: /nl-nl/statline/cbs/general/general-settings
Disallow: /en-gb/statline/cbs/homepage/open-data
Disallow: /nl-nl/statline/cbs/homepage/open-data
Disallow: /en-gb/statline/cbs/homepage/explanation
Disallow: /nl-nl/statline/cbs/homepage/uitleg
Disallow: /en-gb/statline/cbs/homepage/graphs-and-maps
Disallow: /nl-nl/statline/cbs/homepage/grafieken-en-kaarten
Disallow: /en-gb/statline/cbs/homepage/keyword-search
Disallow: /nl-nl/statline/cbs/homepage/zoek-op-trefwoord
Disallow: /en-gb/statline/cbs/homepage/the-netherlands-in-figures
Disallow: /nl-nl/statline/cbs/homepage/statline
Disallow: /nl-nl/statline/cbs/homepage/vernieuwing-statline
Disallow: /en-gb/statline/cbs/general/general-settings/dataportaal_url
Disallow: /nl-nl/statline/cbs/general/general-settings/dataportaal_url
Disallow: /en-gb/statline/cbs/general/general-settings/dataportaal_text
Disallow: /nl-nl/statline/cbs/general/general-settings/dataportaal_text
Disallow: /en-gb/statline/cbs/general/general-settings/backgroundappurl
Disallow: /nl-nl/statline/cbs/general/general-settings/backgroundappurl
Disallow: /en-gb/statline/cbs/general/general-settings/appmobiletitle
Disallow: /nl-nl/statline/cbs/general/general-settings/appmobiletitle
Disallow: /en-gb/statline/cbs/general/general-settings/portaltitle
Disallow: /nl-nl/statline/cbs/general/general-settings/portaltitle
Disallow: /en-gb/statline/cbs/general/general-settings/mainsite_url
Disallow: /nl-nl/statline/cbs/general/general-settings/mainsite_url
Disallow: /en-gb/statline/cbs/general/general-settings/helpurl
Disallow: /nl-nl/statline/cbs/general/general-settings/helpurl
Disallow: /en-gb/statline/cbs/general/general-settings/cbsapiurl
Disallow: /nl-nl/statline/cbs/general/general-settings/cbsapiurl
Disallow: /en-gb/statline/cbs/general/general-settings/reagerenurl
Disallow: /nl-nl/statline/cbs/general/general-settings/reagerenurl
Disallow: /en-gb/statline/cbs/general/general-settings/portalmobiletitle
Disallow: /nl-nl/statline/cbs/general/general-settings/portalmobiletitle
Disallow: /en-gb/statline/cbs/general/general-settings/payoff
Disallow: /nl-nl/statline/cbs/general/general-settings/payoff
Disallow: /en-gb/statline/cbs/general/general-settings/dataportaal
Disallow: /nl-nl/statline/cbs/general/general-settings/dataportaal
Disallow: /en-gb/statline/cbs/general/general-settings/apptitle
Disallow: /nl-nl/statline/cbs/general/general-settings/apptitle
Disallow: /en-gb/statline/cbs/general/general-settings/mainsite_text
Disallow: /nl-nl/statline/cbs/general/general-settings/mainsite_text
Disallow: /en-gb/statline/cbs/general/general-settings/mainsite
Disallow: /nl-nl/statline/cbs/general/general-settings/mainsite
Disallow: /en-gb/statline/cbs/general/general-settings/korteuitleg
Disallow: /nl-nl/statline/cbs/general/general-settings/korteuitleg
Disallow: /en-gb/statline/cbs/general/general-settings/copyright
Disallow: /nl-nl/statline/cbs/general/general-settings/copyright
Disallow: /en-gb/statline/cbs/general/general-settings/recenturl
Disallow: /nl-nl/statline/cbs/general/general-settings/recenturl
Disallow: /nl-nl/statline/iv3/homepage/grafieken
Disallow: /nl-nl/statline/iv3/homepage/iv3
Disallow: /nl-nl/statline/iv3/homepage/zoeken
Disallow: /nl-nl/statline/iv3/homepage/bronvermelding
Disallow: /nl-nl/statline/iv3/homepage/statline-iv3
Disallow: /nl-nl/statline/iv3/general/general-settings
Disallow: /nl-nl/statline/iv3/homepage/statline-iv3/bronvermelding
Disallow: /nl-nl/statline/iv3/general/general-settings/reagerenurl
Disallow: /nl-nl/statline/iv3/general/general-settings/appmobiletitle
Disallow: /nl-nl/statline/iv3/general/general-settings/apptitle
Disallow: /nl-nl/statline/iv3/general/general-settings/copyright
Disallow: /nl-nl/statline/iv3/general/general-settings/dataportaal_url
Disallow: /nl-nl/statline/iv3/general/general-settings/helpurl
Disallow: /nl-nl/statline/iv3/general/general-settings/mainsite_text
Disallow: /nl-nl/statline/iv3/general/general-settings/mainsite_url
Disallow: /nl-nl/statline/iv3/general/general-settings/portalmobiletitle
Disallow: /nl-nl/statline/iv3/general/general-settings/portaltitle
Disallow: /nl-nl/statline/iv3/general/general-settings/appadditionaltitle
Disallow: /nl-nl/statline/iv3/general/general-settings/cbsapiurl
Disallow: /nl-nl/statline/iv3/general/general-settings/dataportaal_text
Disallow: /nl-nl/statline/iv3/general/general-settings/payoff
Disallow: /nl-nl/statline/iv3/general/general-settings/backgroundappurl
Disallow: /nl-nl/statline/iv3/general/general-settings/korteuitleg
Disallow: /nl-nl/statline/mvstat/general/general-settings/reagerenurl
Disallow: /nl-nl/externe-alias/ontdek-statline
Disallow: /en-gb/participants-survey/people/formulier-paginas/your-request-has-been-sent-
Disallow: /nl-nl/deelnemers-enquetes/personen/formulier-pagina/bedankt-voor-het-invullen
Disallow: /nl-nl/onze-diensten/center-for-big-data-statistics/bedankt
Disallow: /nl-nl/onze-diensten/leren-met-het-cbs/evaluatie-samenwerking-vu-cbs
Disallow: /nl-nl/onze-diensten/leren-met-het-cbs/evaluatie-samenwerking-vu-cbs/bedankt
Sitemap: https://www.cbs.nl/sitemap.xml
