User-agent: Yandex
Allow: *.pdf
Allow: *.svg
Allow: *.png
Allow: *.gif
Allow: *.jpeg
Allow: *.jpg
Disallow: /docs/astra/ug/index.html
Disallow: /docs/astra/ag/index.html
Disallow: /digitalproducts
Disallow: /randomizer
Disallow: /consultation
Disallow: /event/form-digital
Disallow: /mlspace-education
Disallow: /cmsb
Disallow: /partners/form
Disallow: /en/
Disallow: /cn/
Disallow: /calculator/partners
Disallow: /documents/eula
Disallow: /documents/license-policy
Disallow: */docs/search.html
Disallow: */docs/*/search.html
Disallow: */register?
Disallow: *?highlight
Disallow: /career/vacancies?
Disallow: /*?mindbox-
Disallow: *adrclid
Disallow: /contacts/compliance/form-with-name
Disallow: *?*
Disallow: /developers
Disallow: /rko
Disallow: /*%23form
Disallow: /ctech/cmsb
Disallow: */gigaconf-2024
Disallow: */search?query=
Disallow: /feedback/
Disallow: /feedback/*/
Disallow: /contacts/compliance
Disallow: /business-cards/
Disallow: /ru/
Disallow: /*genindex.html
Disallow: /events/cloud-ru-tech-day-2024-10-08
Disallow: /events/ochnaya-vstrecha-referalnykh-partnerov-cloud-ru-17-10-2024
Disallow: /events/cloud-ru-tech-day-2024-10-22
Disallow: /events/biznes-uzhin-segodnya-oblachno-2024-11-21
Disallow: /events/zaschischennyye-transportnyye-is-2024-11-20
Disallow: /events/mitap-dlya-tekhnicheskikh-pisateley-2024-11-14
Disallow: /events/biznes-uzhin-oblachniy-vecher-2024-11-28
Disallow: /events/biznes-uzhin-gostekh
Disallow: /events/polufinal-premii-v-oblasti-r-d-tekhnologicheskikh-dzo-2024-12-05
Disallow: /cases?industry=
Disallow: /events/magic-of-cloud-ru-schelkunchik
Disallow: /products/access-to-virtual-machines-with-gpu
Disallow: /products/gpu
Disallow: /products/cloud-backup-and-recovery
Disallow: /products/virtual-private-cloud
Disallow: /products/bare-metal
Disallow: /products/cloud-managed-kubernetes
Disallow: /products/cloud-container-engine
Disallow: /products/object-storage
Disallow: /products/elastic-load-balance
Disallow: /products/cloud-container-engine
Disallow: /products/elastic-volume-service
Disallow: /products/image-management-service
Disallow: /products/tag-management-service-tms
Disallow: /products/virtual-private-cloud-and-elastic-ip
Disallow: /products/elastic-cloud-server
Disallow: /products/relational-databases-service-postgresql
Disallow: /events/cloud-ru-tech-lab-golang
Disallow: /research/customer-centricity
Disallow: /solutions/rendering-3d-modelirovanie
Disallow: /solutions/gayd-vorkshopa-ot-cloud-ru-ilya-smirnov
Disallow: /offers/oblachnyye-resheniya
Disallow: */subscription/campcloud
Disallow: /events/dlya-uchastnikov-konferentsii-ds-conf
Disallow: /events/ai-keysarium
Disallow: /events/biznes-uzhin-evolution-18-09-2025
Disallow: /events/cloud-ru-connect-2025
Disallow: /events/ai-forsazh-02-09-2025
Disallow: /events/tekhnologii-generativnogo-ii-v-stroitelstve-2025
Disallow: /events/ai-talks-30-10-2025

Clean-param: utm_source&utm_medium&utm_term&utm_campaign&utm_content&utm_expid&utm_referrer
Clean-param: calltouch_tm&_openstat&yclid&gclid&from&fbclid&_ga&_gac&frommarket&cm_id&rb_clickid&callback&ref&uid&_ym_debug&gtm_debug
Clean-param: standalone&locale&service&name&phone&email&nameCompany&comment&surname&inn&position&product&stat-id&test-tag&format-type&actual-format&banner-test-tags&target-ref&h&amp&Finveritas
Clean-param: industry

User-agent: Googlebot
Allow: *.pdf
Allow: *.svg
Allow: *.png
Allow: *.gif
Allow: *.jpeg
Allow: *.jpg
Disallow: /docs/astra/ug/index.html
Disallow: /docs/astra/ag/index.html
Disallow: /digitalproducts
Disallow: /randomizer
Disallow: /consultation
Disallow: /event/form-digital
Disallow: /mlspace-education
Disallow: /cmsb
Disallow: /partners/form
Disallow: /en/
Disallow: /cn/
Disallow: /calculator/partners
Disallow: /documents/eula
Disallow: /documents/license-policy
Disallow: */docs/search.html
Disallow: */docs/*/search.html
Disallow: */register?
Disallow: *?highlight
Disallow: /career/vacancies?
Disallow: /*?mindbox-
Disallow: /contacts/compliance/form-with-name
Disallow: *adrclid
Disallow: *?*
Disallow: /*%23form
Disallow: /ctech/cmsb
Disallow: /developers
Disallow: /rko
Disallow: */gigaconf-2024
Disallow: */search?query=
Disallow: /feedback/
Disallow: /feedback/*/
Disallow: /contacts/compliance
Disallow: /business-cards/
Disallow: /*genindex.html
Disallow: /events/cloud-ru-tech-day-2024-10-08
Disallow: /events/ochnaya-vstrecha-referalnykh-partnerov-cloud-ru-17-10-2024
Disallow: /events/cloud-ru-tech-day-2024-10-22
Disallow: /events/biznes-uzhin-segodnya-oblachno-2024-11-21
Disallow: /events/zaschischennyye-transportnyye-is-2024-11-20
Disallow: /events/mitap-dlya-tekhnicheskikh-pisateley-2024-11-14
Disallow: /events/biznes-uzhin-oblachniy-vecher-2024-11-28
Disallow: /events/biznes-uzhin-gostekh
Disallow: /events/polufinal-premii-v-oblasti-r-d-tekhnologicheskikh-dzo-2024-12-05
Disallow: /cases?industry=
Disallow: /events/magic-of-cloud-ru-schelkunchik
Disallow: /products/access-to-virtual-machines-with-gpu
Disallow: /products/gpu
Disallow: /products/cloud-backup-and-recovery
Disallow: /products/virtual-private-cloud
Disallow: /products/bare-metal
Disallow: /products/cloud-managed-kubernetes
Disallow: /products/cloud-container-engine
Disallow: /products/object-storage
Disallow: /products/elastic-load-balance
Disallow: /products/cloud-container-engine
Disallow: /products/elastic-volume-service
Disallow: /products/image-management-service
Disallow: /products/tag-management-service-tms
Disallow: /products/virtual-private-cloud-and-elastic-ip
Disallow: /products/elastic-cloud-server
Disallow: /products/relational-databases-service-postgresql
Disallow: /events/cloud-ru-tech-lab-golang
Disallow: /research/customer-centricity
Disallow: /solutions/rendering-3d-modelirovanie
Disallow: /solutions/gayd-vorkshopa-ot-cloud-ru-ilya-smirnov
Disallow: /offers/oblachnyye-resheniya
Disallow: */subscription/campcloud
Disallow: /events/dlya-uchastnikov-konferentsii-ds-conf
Disallow: /events/ai-keysarium
Disallow: /events/biznes-uzhin-evolution-18-09-2025
Disallow: /events/cloud-ru-connect-2025
Disallow: /events/ai-forsazh-02-09-2025
Disallow: /events/tekhnologii-generativnogo-ii-v-stroitelstve-2025
Disallow: /events/ai-talks-30-10-2025

User-agent: *
Allow: *.pdf
Allow: *.svg
Allow: *.png
Allow: *.gif
Allow: *.jpeg
Allow: *.jpg
Disallow: /docs/astra/ug/index.html
Disallow: /docs/astra/ag/index.html
Disallow: /digitalproducts
Disallow: /randomizer
Disallow: /consultation
Disallow: /event/form-digital
Disallow: /mlspace-education
Disallow: /cmsb
Disallow: /partners/form
Disallow: /en/
Disallow: /cn/
Disallow: /calculator/partners
Disallow: /documents/eula
Disallow: /documents/license-policy
Disallow: */docs/search.html
Disallow: */docs/*/search.html
Disallow: */register?
Disallow: *?highlight
Disallow: /career/vacancies?
Disallow: /*?mindbox-
Disallow: *adrclid
Disallow: *?*
Disallow: /*%23form
Disallow: /contacts/compliance/form-with-name
Disallow: /ctech/cmsb
Disallow: /developers
Disallow: /rko
Disallow: */gigaconf-2024
Disallow: */search?query=
Disallow: /feedback/
Disallow: /feedback/*/
Disallow: /*genindex.html
Disallow: /contacts/compliance
Disallow: /business-cards/
Disallow: /events/cloud-ru-tech-day-2024-10-08
Disallow: /events/ochnaya-vstrecha-referalnykh-partnerov-cloud-ru-17-10-2024
Disallow: /events/cloud-ru-tech-day-2024-10-22
Disallow: /events/biznes-uzhin-segodnya-oblachno-2024-11-21
Disallow: /events/zaschischennyye-transportnyye-is-2024-11-20
Disallow: /events/mitap-dlya-tekhnicheskikh-pisateley-2024-11-14
Disallow: /events/biznes-uzhin-oblachniy-vecher-2024-11-28
Disallow: /events/biznes-uzhin-gostekh
Disallow: /events/polufinal-premii-v-oblasti-r-d-tekhnologicheskikh-dzo-2024-12-05
Disallow: /cases?industry=
Disallow: /events/magic-of-cloud-ru-schelkunchik
Disallow: /products/access-to-virtual-machines-with-gpu
Disallow: /products/gpu
Disallow: /products/cloud-backup-and-recovery
Disallow: /products/virtual-private-cloud
Disallow: /products/bare-metal
Disallow: /products/cloud-managed-kubernetes
Disallow: /products/cloud-container-engine
Disallow: /products/object-storage
Disallow: /products/elastic-load-balance
Disallow: /products/cloud-container-engine
Disallow: /products/elastic-volume-service
Disallow: /products/image-management-service
Disallow: /products/tag-management-service-tms
Disallow: /products/virtual-private-cloud-and-elastic-ip
Disallow: /products/elastic-cloud-server
Disallow: /products/relational-databases-service-postgresql
Disallow: /events/cloud-ru-tech-lab-golang
Disallow: /research/customer-centricity
Disallow: /solutions/rendering-3d-modelirovanie
Disallow: /solutions/gayd-vorkshopa-ot-cloud-ru-ilya-smirnov
Disallow: /offers/oblachnyye-resheniya
Disallow: */subscription/campcloud
Disallow: /events/dlya-uchastnikov-konferentsii-ds-conf
Disallow: /events/ai-keysarium
Disallow: /events/biznes-uzhin-evolution-18-09-2025
Disallow: /events/cloud-ru-connect-2025
Disallow: /events/ai-forsazh-02-09-2025
Disallow: /events/tekhnologii-generativnogo-ii-v-stroitelstve-2025
Disallow: /events/ai-talks-30-10-2025

Sitemap: https://cloud.ru/sitemap.xml
Sitemap: https://cloud.ru/docs/sitemap.xml
Sitemap: https://cloud.ru/documents/sitemap.xml
Sitemap: https://cloud.ru/sitemap_career.xml