User-agent: *
Allow: /
Disallow: /admin
Disallow: /find/address/*
Disallow: /find/bank/*
Disallow: /find/party/*
Disallow: /pokemon
Disallow: /profile
Disallow: /social
Disallow: /userecho-login
Disallow: /*?*
Disallow: /*!*
Disallow: /blog/*/
Allow: /blog/instructions/
Allow: /blog/cases/
Allow: /blog/vse-zapisi-bloga/
Allow: /blog/*/*/
Disallow: /blog/category/*/
Disallow: /blog/*/page/*/
Sitemap: https://dadata.ru/sitemap_index.xml