User-agent: Yandex
Disallow: /user
Disallow: /*search=
Disallow: /personal
Disallow: /*uid=
Disallow: /index?type=
Disallow: /index?nn_contact_position=
Disallow: /*captcha?v=
Disallow: /*v=
Disallow: /*nn_contact_position%5B%5D=
Disallow: /*nn_contact_position_buh
Disallow: /*nn_contact_position_lawyer
Disallow: /*nn_contact_position_staff
Disallow: /*nn_contact_position_head=
Disallow: /*nn_taxation%5B%5D=
Disallow: /*p=
Disallow: /*q=
Disallow: /*dt=
Disallow: /*category
Disallow: /*str=
Disallow: /*nn_contact_position=
Disallow: /*addresses=
Disallow: /*type=
Disallow: /*month=
Disallow: /*year=
Disallow: /*alias=
Disallow: /*per-page=
Disallow: /*nn_contact_position%5B0%5D=
Disallow: /*nn_taxation%5B0%5D=
Disallow: /*date=
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-internet-reporting
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-companies-and-owners
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-edo
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-search-purchases
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-ofd-licenses
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-esignatures
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy/sbis-buh
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy/sbis-urist
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy/sbis-to-lead
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy/sbis-zak
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy/sbis-budj
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy/sbis-commerce-company
Disallow: /?page_id=
Disallow: /?id=
Disallow: /*index.php
Disallow: /*louis-vuitton-
Disallow: /service/news/daydjest-bi
Disallow: /service/news/anonsi-knig
Disallow: /service/news/vesti-iz-nalogovykh
Disallow: /products/konsultantplus/supermassiv
Host: https://www.elcode.ru

User-agent: Googlebot
Disallow: /user
Disallow: /*search=
Disallow: /personal
Disallow: /*uid=
Disallow: /index?type=
Disallow: /index?nn_contact_position=
Disallow: /*captcha?v=
Disallow: /*v=
Disallow: /*nn_contact_position%5B%5D=
Disallow: /*nn_contact_position_buh
Disallow: /*nn_contact_position_lawyer
Disallow: /*nn_contact_position_staff
Disallow: /*nn_contact_position_head=
Disallow: /*nn_taxation%5B%5D=
Disallow: /*p=
Disallow: /*q=
Disallow: /*dt=
Disallow: /*category
Disallow: /*str=
Disallow: /*nn_contact_position=
Disallow: /*addresses=
Disallow: /*type=
Disallow: /*month=
Disallow: /*year=
Disallow: /*alias=
Disallow: /*per-page=
Disallow: /*nn_contact_position%5B0%5D=
Disallow: /*nn_taxation%5B0%5D=
Disallow: /*date=
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-internet-reporting
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-companies-and-owners
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-edo
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-search-purchases
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-ofd-licenses
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-esignatures
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy/sbis-buh
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy/sbis-urist
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy/sbis-to-lead
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy/sbis-zak
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy/sbis-budj
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy/sbis-commerce-company
Disallow: /?page_id=
Disallow: /?id=
Disallow: /*index.php
Disallow: /*louis-vuitton-
Disallow: /service/news/daydjest-bi
Disallow: /service/news/anonsi-knig
Disallow: /service/news/vesti-iz-nalogovykh
Disallow: /products/konsultantplus/supermassiv

User-agent: *
Disallow: /user
Disallow: /*search=
Disallow: /personal
Disallow: /*uid=
Disallow: /index?type=
Disallow: /index?nn_contact_position=
Disallow: /*captcha?v=
Disallow: /*v=
Disallow: /*nn_contact_position%5B%5D=
Disallow: /*nn_contact_position_buh
Disallow: /*nn_contact_position%5B%5D=
Disallow: /*nn_contact_position_lawyer
Disallow: /*nn_contact_position%5B%5D=
Disallow: /*nn_contact_position_staff
Disallow: /*nn_contact_position%5B%5D=
Disallow: /*nn_contact_position_head=
Disallow: /*nn_taxation%5B%5D=
Disallow: /*p=
Disallow: /*q=
Disallow: /*dt=
Disallow: /*category
Disallow: /*str=
Disallow: /*nn_contact_position=
Disallow: /*addresses=
Disallow: /*type=
Disallow: /*month=
Disallow: /*year=
Disallow: /*alias=
Disallow: /*per-page=
Disallow: /*nn_contact_position%5B0%5D=
Disallow: /*nn_taxation%5B0%5D=
Disallow: /*date=
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-internet-reporting
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-companies-and-owners
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-edo
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-search-purchases
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-ofd-licenses
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-esignatures
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy/sbis-buh
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy/sbis-urist
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy/sbis-to-lead
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy/sbis-zak
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy/sbis-budj
Disallow: /products/elektronnaya-otchetnost-sbis/sbis-buy/sbis-commerce-company
Disallow: /?page_id=
Disallow: /?id=
Disallow: /*index.php
Disallow: /*louis-vuitton-
Disallow: /service/news/daydjest-bi
Disallow: /service/news/anonsi-knig
Disallow: /service/news/vesti-iz-nalogovykh
Disallow: /products/konsultantplus/supermassiv