User-Agent: *
Disallow: /*yclid=*
Disallow: /*gclid=*
Disallow: /arhiv_*
Disallow: /banki/*/vklady/teg_valytnye*
Disallow: /banki/*/vklady/teg_do_vostrebovaniya*
Disallow: /banki/*/vklady/teg_sberegatelnye*
Disallow: /banki/*/vklady/teg_na_1_god*
Disallow: /banki/*/vklady/teg_kratkosrochnye*
Disallow: /banki/*/vklady/teg_dolgosrochnye*
Disallow: /banki/*/vklady/teg_sezonnye*
Disallow: /banki/*/vklady/teg_sberegatelnye*
Disallow: /banki/*/vklady/teg_bez_snyatiya_s_popolneniem*
Disallow: /banki/*/vklady/teg_so_snyatiem*
Disallow: /banki/*/vklady/teg_multivalyutnye*
Disallow: /banki/*/vklady/teg_v_euro*
Disallow: /banki/*/vklady/teg_v_dollarah*
Disallow: /banki/*/potrebitelskie_kredity/teg_pod_zalog_imushchestva*
Disallow: /banki/*/potrebitelskie_kredity/teg_na_lechenie*
Disallow: /banki/*/potrebitelskie_kredity/teg_na_obuchenie*
Disallow: /banki/*/potrebitelskie_kredity/teg_na_otdyh*
Disallow: /banki/*/potrebitelskie_kredity/teg_na_remont*
Disallow: /banki/*/potrebitelskie_kredity/teg_ot_10000_rublej*
Disallow: /banki/*/potrebitelskie_kredity/teg_ot_20000_rublej* 
Disallow: /banki/*/potrebitelskie_kredity/teg_ot_1000000_rublej*
Disallow: /banki/*/potrebitelskie_kredity/teg_pod_zalog_imushchestva*
Disallow: /banki/*/potrebitelskie_kredity/teg_s_21_goda*
Disallow: /banki/*/potrebitelskie_kredity/teg_s_18_let*
Disallow: /banki/*/potrebitelskie_kredity/teg_dlya_studentov*
Disallow: /banki/*/potrebitelskie_kredity/teg_v_dollarah*
Disallow: /banki/*/potrebitelskie_kredity/teg_v_evro* 
Disallow: /banki/*/potrebitelskie_kredity/teg_bez_registracii*
Disallow: /banki/*/potrebitelskie_kredity/teg_20_luchshih*
Disallow: /banki/*/potrebitelskie_kredity/teg_na_svadbu*
Disallow: /banki/*/potrebitelskie_kredity/teg_bez_obespecheniya*
Disallow: /banki/*/potrebitelskie_kredity/teg_dlya_inostrannyh_grazhdan*
Disallow: /banki/*/potrebitelskie_kredity/teg_necelevye* 
Disallow: /banki/*/potrebitelskie_kredity/teg_celevye*
Disallow: /banki/*/potrebitelskie_kredity/teg_s_plohoj_kreditnoj_istoriej*
Disallow: /ipoteka/*segments=*
Disallow: /ipoteka/*property_type=*
Disallow: /ipoteka/*amount*
Disallow: /ipoteka/*payment=*
Disallow: /ipoteka/*downpayment=*
Disallow: /ipoteka/*term=*
Disallow: /ipoteka/*proof=*
Disallow: /ipoteka/*sort=*
Disallow: /ipoteka/*sortDir=*
Allow: */*.css
Allow: */*.png
Allow: */*.jpg
Allow: */*.woff
Allow: */*.js

User-agent: Yandex
Disallow: /arhiv_*
Disallow: /banki/*/vklady/teg_valytnye*
Disallow: /banki/*/vklady/teg_do_vostrebovaniya*
Disallow: /banki/*/vklady/teg_sberegatelnye*
Disallow: /banki/*/vklady/teg_na_1_god*  
Disallow: /banki/*/vklady/teg_kratkosrochnye*
Disallow: /banki/*/vklady/teg_dolgosrochnye*
Disallow: /banki/*/vklady/teg_sezonnye*
Disallow: /banki/*/vklady/teg_sberegatelnye*
Disallow: /banki/*/vklady/teg_bez_snyatiya_s_popolneniem*
Disallow: /banki/*/vklady/teg_so_snyatiem*
Disallow: /banki/*/vklady/teg_multivalyutnye*
Disallow: /banki/*/vklady/teg_v_euro*
Disallow: /banki/*/vklady/teg_v_dollarah*
Disallow: /banki/*/potrebitelskie_kredity/teg_pod_zalog_imushchestva*
Disallow: /banki/*/potrebitelskie_kredity/teg_na_lechenie*
Disallow: /banki/*/potrebitelskie_kredity/teg_na_obuchenie*
Disallow: /banki/*/potrebitelskie_kredity/teg_na_otdyh*
Disallow: /banki/*/potrebitelskie_kredity/teg_na_remont*
Disallow: /banki/*/potrebitelskie_kredity/teg_ot_10000_rublej*
Disallow: /banki/*/potrebitelskie_kredity/teg_ot_20000_rublej* 
Disallow: /banki/*/potrebitelskie_kredity/teg_ot_1000000_rublej*
Disallow: /banki/*/potrebitelskie_kredity/teg_pod_zalog_imushchestva*
Disallow: /banki/*/potrebitelskie_kredity/teg_s_21_goda*
Disallow: /banki/*/potrebitelskie_kredity/teg_s_18_let*
Disallow: /banki/*/potrebitelskie_kredity/teg_dlya_studentov*
Disallow: /banki/*/potrebitelskie_kredity/teg_v_dollarah*
Disallow: /banki/*/potrebitelskie_kredity/teg_v_evro* 
Disallow: /banki/*/potrebitelskie_kredity/teg_bez_registracii*
Disallow: /banki/*/potrebitelskie_kredity/teg_20_luchshih*
Disallow: /banki/*/potrebitelskie_kredity/teg_na_svadbu*
Disallow: /banki/*/potrebitelskie_kredity/teg_bez_obespecheniya*
Disallow: /banki/*/potrebitelskie_kredity/teg_dlya_inostrannyh_grazhdan*
Disallow: /banki/*/potrebitelskie_kredity/teg_necelevye* 
Disallow: /banki/*/potrebitelskie_kredity/teg_celevye*
Disallow: /banki/*/potrebitelskie_kredity/teg_s_plohoj_kreditnoj_istoriej*
Allow: */*.css
Allow: */*.png
Allow: */*.jpg
Allow: */*.woff
Allow: */*.js

Clean-param: sortType&amount&term&withCapitalization&withMonthlyPercent&withPreferentialTermination&withRefill&currency&activeBanks&form&period&borrower&registration&collateral&online&sort&banks&flags&property_type&payment&bank&market&location&sortDir&downpayment&provision&proof&confirmId&email&adrclid&adv_p_id&offer_id&draft&authRedirect&autm_term&amp&etext&from&id&filter&offerid&state&gl&activeFilter&car&order_key&aggregator_id

Clean-param: frameId&click_id&erid&product_id&utm_source&utm_medium&utm_campaign&utm_term&utm_content&map&list&marker&region&town&company&mfo&termValue&termType&ref&undefined&optionId&depositRate&periodCapitalization&url&w&q&yclid&gclid&erid&sortType&subid1&subid2&term&affiliate_id&LegacyUserId&name&page_host&page_path&utm_&segments=