User-agent: *
Disallow: */ajax/*
Disallow: */amp/related/*
Disallow: /search?q=*
Disallow: *utm_source=*
Disallow: *utm_medium=*
Disallow: *utm_campaign=*
Disallow: /cdn-cgi/

Sitemap: https://focus.ua/sitemap.xml

Sitemap: https://focus.ua/sitemap-news-uk.xml
Sitemap: https://focus.ua/sitemap-news-ru.xml
Sitemap: https://focus.ua/sitemap-72h-uk.xml
Sitemap: https://focus.ua/sitemap-72h-ru.xml
Sitemap: https://focus.ua/sitemap-images-72h-uk.xml
Sitemap: https://focus.ua/sitemap-images-72h-ru.xml
