User-agent: *
Disallow: /zoeknaam.php
Disallow: /contact.php
Disallow: /aanknopingspunten/
Disallow: /scans/
Disallow: /pgv/
Disallow: /oai/
Disallow: /zoeken/
Disallow: /en/zoeken/
Disallow: /de/zoeken/
Disallow: /fr/zoeken/

SITEMAP: https://www.genealogieonline.nl/sitemaps/over-de-familienaam-nl.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/over-de-familienaam-en.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/over-de-familienaam-de.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/over-de-familienaam-fr.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/plaats.xml

SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-1.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-10.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-11.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-12.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-13.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-14.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-15.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-16.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-17.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-18.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-19.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-2.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-20.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-21.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-22.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-23.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-24.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-25.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-26.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-27.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-28.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-29.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-3.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-30.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-31.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-32.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-33.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-34.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-35.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-36.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-37.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-38.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-39.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-4.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-40.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-41.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-42.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-43.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-44.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-45.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-46.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-47.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-48.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-49.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-5.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-50.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-51.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-52.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-53.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-54.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-55.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-56.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-57.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-58.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-59.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-6.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-60.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-61.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-62.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-63.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-64.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-65.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-66.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-67.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-68.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-7.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-8.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications-9.xml
SITEMAP: https://www.genealogieonline.nl/sitemaps/publications.xml
