# www.robotstxt.org/
# www.google.com/support/webmasters/bin/answer.py?hl=en&answer=156449

Host: https://hyperauto.ru

User-agent: Amazonbot
Disallow: /

User-agent: *
Disallow: /*?*f_
Disallow: /*coupon=
Disallow: /admin/
Disallow: /pickers/
Disallow: /search/
Disallow: /search.php
Disallow: */search/
Disallow: */change-city/*
Disallow: /drugoy-gorod/
Disallow: /news/
Disallow: /city-*
Disallow: /federal-*
Disallow: /region-*
Disallow: */offer/
Disallow: /cart/

Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term&utm_referrer&utmstat&yclid&gclid&clid&_openstat&_ga&mindbox-click-id&fbclid&baobab_event_id&_gac&direct-crm-ticket&yhid&smartleads_pid&smartleads_sid&smartleads_src&from&frommarket&wprid&back&tagtag_uid&ga_campaignid&ga_adgroupid&ga_feeditemid&ga_targetid&ga_loc_interest_ms&ga_loc_physical_ms&ga_network&ga_device&ga_devicemodel&ga_creative&ga_keyword&ga_placement&ga_adposition&roistat&roistat_referrer&roistat_pos&verified
Clean-param: type&query&ssd&code&modificationInfo&car&vid&modificationsSsd&modificationSsd&modificationUuid&unit&year&carYear&qgid&oldSsd&modificationId&specId&lang&maintenanceOrder
Clean-param: q&category&coi&page&pageLimit&backUrl&season&sizeUuid&orderUuid&filter&coupon&city&orderId&name&email&etext&relId&callback&_controller&text&showComments&sort&action&brand&id&new&src_pof&subid
Clean-param: f_brand[]&f_brand[0]&f_brand&f_sae[]&f_sae[0]&f_category[]&f_stock[]&f_price_min&f_price_max&f_type[]&f_Type[]&f_type[0]&f_Purpose[]&f_purpose[]&f_Other[]&f_Other[0]&f_Other[1]&f_Other[2]&f_Colour[]&f_colour[]&f_maker[]&f_model[]&f_size[]&f_package[]&f_colourcode[]&f_label[]&f_Wax[]&f_deep[]&f_product[]
Clean-param: f_61[]&f_18[]&f_9[]&f_20[]&f_5[]&f_37[]&f_282[]&f_227[]&f_337[]&f_364[]&f_276[]&f_309[]&f_228[]&f_34[]&f_226[]&f_224[]&f_94[]&f_225[]&f_38[]&f_196[]&f_71[]&f_278[]&f_70[]&f_7[]&f_39[]&f_69[]&f_283[]&f_229[]&f_336[]&f_279[]&f_295[]&f_271[]&f_327[]&f_299[]&f_372[]&f_329[]&f_205[]&f_3[]&f_413[]&f_296[]&f_412[]&f_194[]&f_57[]&f_195[]&f_4[]&f_193[]&f_396[]&f_133[]&f_84[]&f_230[]&f_2[]&f_314[]&f_424[]&f_8[]&f_425[]&f_colour[]&f_206[]&f_73[]&f_298[]&f_96[]&f_72[]&f_68[]&f_397[]&f_328[]&f_436[]
Clean-param: mindbox-message-key&m-message-key-id&m-message-click-id&yprqee

Crawl-delay: 0.5

# Sitemap: https://hyperauto.ru/sitemap.xml

Sitemap: https://hyperauto.ru/sitemap__region-respublika-kareliya.xml
Sitemap: https://hyperauto.ru/sitemap__region-yaroslavskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-nenetskiy-avtonomniy-okr.xml
Sitemap: https://hyperauto.ru/sitemap__region-ryazanskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-tulskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-respublika-bashkortostan.xml
Sitemap: https://hyperauto.ru/sitemap__region-tambovskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-respublika-dagestan.xml
Sitemap: https://hyperauto.ru/sitemap__region-smolenskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-chukotskiy-avt-okrug.xml
Sitemap: https://hyperauto.ru/sitemap__region-irkutskaya-oblas.xml
Sitemap: https://hyperauto.ru/sitemap__region-respublika-altay.xml
Sitemap: https://hyperauto.ru/sitemap__region-vladimirskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-kabardino-balkarskaya-resp.xml
Sitemap: https://hyperauto.ru/sitemap__region-omskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-krasnodarskiy-kray.xml
Sitemap: https://hyperauto.ru/sitemap__region-yamalo-nenetskiy-avt-okrug.xml
Sitemap: https://hyperauto.ru/sitemap__sahalinskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-saratovskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-respublika-udmurtiya.xml
Sitemap: https://hyperauto.ru/sitemap__region-ulyanovskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-magadanskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-penzenskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-kurskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__evreyskaya-avton.xml
Sitemap: https://hyperauto.ru/sitemap__region-sevastopol.xml
Sitemap: https://hyperauto.ru/sitemap__region-leningradskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-rostovskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-krasnoyarskiy-kray.xml
Sitemap: https://hyperauto.ru/sitemap__region-voronezshkaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-respublika-ingushetiya.xml
Sitemap: https://hyperauto.ru/sitemap__region-saint-petersburg.xml
Sitemap: https://hyperauto.ru/sitemap__region-murmanskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-orenburgskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-volgogradskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-altayskiy-kray.xml
Sitemap: https://hyperauto.ru/sitemap__region-ivanovskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-sverdlovskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-kostromskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-respublika-tatarstan.xml
Sitemap: https://hyperauto.ru/sitemap__habarovskiy-kray.xml
Sitemap: https://hyperauto.ru/sitemap__region-respublika-adygeya.xml
Sitemap: https://hyperauto.ru/sitemap__region-respublika-mordoviya.xml
Sitemap: https://hyperauto.ru/sitemap__primorskiy-kray.xml
Sitemap: https://hyperauto.ru/sitemap__region-vologodskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-respublika-krym.xml
Sitemap: https://hyperauto.ru/sitemap__region-buryatiya-respub.xml
Sitemap: https://hyperauto.ru/sitemap__region-komi.xml
Sitemap: https://hyperauto.ru/sitemap__region-stavropolskiy-kray.xml
Sitemap: https://hyperauto.ru/sitemap__region-chechenskaya-respublika.xml
Sitemap: https://hyperauto.ru/sitemap__region-respublika-kalmykiya.xml
Sitemap: https://hyperauto.ru/sitemap__region-astrakhanskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-zabaykalskiy-kray.xml
Sitemap: https://hyperauto.ru/sitemap__region-respublika-severnaya-osetiya.xml
Sitemap: https://hyperauto.ru/sitemap__common.xml
Sitemap: https://hyperauto.ru/sitemap__region-tyumenskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-moscow.xml
Sitemap: https://hyperauto.ru/sitemap__region-karachaevo-cherskesskaya-resp.xml
Sitemap: https://hyperauto.ru/sitemap__region-respublika-mariy-el.xml
Sitemap: https://hyperauto.ru/sitemap__region-chelyabinskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-kaluzhskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-lipetskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-bryanskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-moskovskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-respublika-sakha-yakutiya.xml
Sitemap: https://hyperauto.ru/sitemap__region-pskovskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-novosibirskaya-oblast.xml
Sitemap: https://hyperauto.ru/sitemap__region-kaliningradskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-kurganskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__amurskaya-oblast.xml
Sitemap: https://hyperauto.ru/sitemap__region-chuvashskaya-respublika.xml
Sitemap: https://hyperauto.ru/sitemap__region-kamchatskiy-kray.xml
Sitemap: https://hyperauto.ru/sitemap__region-novgorodskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-permskiy-kray.xml
Sitemap: https://hyperauto.ru/sitemap__region-kirovskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-khanty-mansiyskiy-okrug-yugra.xml
Sitemap: https://hyperauto.ru/sitemap__region-nizhegorodskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-respublika-tyva.xml
Sitemap: https://hyperauto.ru/sitemap__region-belgorodskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-respublika-hakasiya.xml
Sitemap: https://hyperauto.ru/sitemap__region-samarskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-arkhangelskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-kemerovskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-orlovskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-tverskaya-obl.xml
Sitemap: https://hyperauto.ru/sitemap__region-tomskaya-obl.xml