User-agent: *
Disallow: /usuarios/
Disallow: /club/
Disallow: /comunes/
Disallow: /login.html
Disallow: /buscador/
Disallow: /minisite/
Disallow: /feeds/
Disallow: /*PageSpeed*
Disallow: /*ModPagespeed*
Disallow: /1001866/
Disallow: /temas/*/fotos/*
Disallow: /marcas/*/fotos/*
Disallow: /boletin/
Disallow: /revista
Disallow: /*/{{link}}$
Disallow: /*/{{url}}$

User-agent: GPTBot
Disallow: /
User-agent: CCBot
Disallow: /
User-agent: Amazonbot
Disallow: /
User-agent: ChatGPT-User
Disallow: /
User-agent: OAI-SearchBot
Disallow: /
User-agent: Bytespider
Disallow: /
User-agent: ClaudeBot
Disallow: /
User-agent: Perplexity-User
Disallow: /
User-agent: PerplexityBot
Disallow: /
User-agent: Claude-SearchBot
Disallow: /
