User-agent: * 
# Disallow /

# Disallow: /unternehmen/
# Disallow: /privatkunden/internet/dsl/internet/
# Disallow: /privatkunden/internet/dsl/telefonie/
# Disallow: /privatkunden/internet/dsl/tv/
# Disallow: /privatkunden/internet/dsl/kmu/
# Disallow: /privatkunden/internet/dsl/ip-subnetz/
# Disallow: /privatkunden/internet/dsl/verfuegbarkeit/
# Disallow: /privatkunden/internet/dsl/was-ist-dsl/
# Disallow: /services/bestellung/?r=/netz/dsl-eco/#/
# Disallow: /unternehmen/internet/dsl/hardware/
# Disallow: /unternehmen/internet/dsl/angebote/
# Disallow: /unternehmen/internet/dsl/optionen/
# Disallow: /unternehmen/internet/dsl/verfuegbarkeit/
# Disallow: /unternehmen/internet/verfuegbarkeit/verfuegbarkeits-check/
# Disallow: /unternehmen/internet/verfuegbarkeit/speedtest/
# Disallow: /privatkunden/internet/verfuegbarkeit/verfuegbarkeits-check/
# Disallow: /privatkunden/internet/verfuegbarkeit/speedtest/
# Disallow: /privatkunden/internet/verfuegbarkeit/glasfaser-oder-dsl/
# Disallow: /kontakt-formular/
# Disallow: /privatkunden/internet/glasfaser/uebersicht/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/zuerich/internet/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/bern/internet/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/winterthur/internet/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/luzern/internet/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/stgallen/internet/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/gossau/internet/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/didico/internet/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/baden/internet/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/lenzburg/internet/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/frauenfeld/internet/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/lindau/internet/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/basel/internet/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/zuerich/telefonie/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/zuerich/tv/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/zuerich/kmu/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/zuerich/ip-subnetz/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/zuerich/verfuegbarkeit/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/bern/telefonie/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/bern/tv/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/bern/kmu/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/bern/ip-subnetz/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/bern/verfuegbarkeit/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/winterthur/telefonie/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/winterthur/tv/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/winterthur/kmu/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/winterthur/ip-subnetz/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/winterthur/verfuegbarkeit/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/luzern/telefonie/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/luzern/tv/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/luzern/kmu/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/luzern/verfuegbarkeit/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/stgallen/telefonie/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/stgallen/tv/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/stgallen/kmu/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/stgallen/ip-subnetz/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/stgallen/verfuegbarkeit/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/gossau/telefonie/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/gossau/tv/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/gossau/kmu/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/gossau/ip-subnetz/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/gossau/verfuegbarkeit/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/didico/telefonie/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/didico/tv/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/didico/kmu/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/didico/ip-subnetz/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/didico/verfuegbarkeit/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/baden/telefonie/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/baden/tv/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/baden/kmu/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/baden/ip-subnetz/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/baden/verfuegbarkeit/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/lenzburg/telefonie/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/lenzburg/tv/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/lenzburg/kmu/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/lenzburg/ip-subnetz/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/lenzburg/verfuegbarkeit/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/frauenfeld/telefonie/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/frauenfeld/tv/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/frauenfeld/kmu/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/frauenfeld/ip-subnetz/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/frauenfeld/verfuegbarkeit/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/lindau/telefonie/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/lindau/tv/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/lindau/kmu/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/lindau/ip-subnetz/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/lindau/verfuegbarkeit/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/basel/telefonie/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/basel/tv/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/basel/kmu/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/basel/ip-subnetz/
# Disallow: /privatkunden/internet/glasfaser/stadtnetze/basel/verfuegbarkeit/
# Disallow: /privatkunden/internet/glasfaser/schweizweit/
# Disallow: /privatkunden/internet/glasfaser/schweizweit/internet/
# Disallow: /privatkunden/internet/glasfaser/schweizweit/telefonie/
# Disallow: /privatkunden/internet/glasfaser/schweizweit/tv/
# Disallow: /privatkunden/internet/glasfaser/schweizweit/kmu/
# Disallow: /privatkunden/internet/glasfaser/schweizweit/ip-subnetz/
# Disallow: /privatkunden/internet/glasfaser/schweizweit/verfuegbarkeit/
# Disallow: /privatkunden/internet/glasfaser/litexchange/
# Disallow: /privatkunden/internet/glasfaser/litexchange/internet/
# Disallow: /privatkunden/internet/glasfaser/litexchange/telefonie/
# Disallow: /privatkunden/internet/glasfaser/litexchange/tv/
# Disallow: /privatkunden/internet/glasfaser/litexchange/kmu/
# Disallow: /privatkunden/internet/glasfaser/litexchange/verfuegbarkeit/
# Disallow: /privatkunden/internet/glasfaser/hausinstallation/
# Disallow: /privatkunden/internet/glasfaser/verfuegbarkeit/
# Disallow: /privatkunden/internet/glasfaser/was-ist-glasfaser/
# Disallow: /unternehmen/internet/glasfaser/uebersicht/
# Disallow: /unternehmen/internet/glasfaser/stadtnetze/
# Disallow: /unternehmen/internet/glasfaser/stadtnetze/stadtnetz-zuerich/
# Disallow: /unternehmen/internet/glasfaser/stadtnetze/stadtnetz-bern/
# Disallow: /unternehmen/internet/glasfaser/stadtnetze/stadtnetz-winterthur/
# Disallow: /unternehmen/internet/glasfaser/stadtnetze/stadtnetz-luzern/
# Disallow: /unternehmen/internet/glasfaser/stadtnetze/stadtnetz-st-gallen/
# Disallow: /unternehmen/internet/glasfaser/stadtnetze/stadtnetz-gossau/
# Disallow: /unternehmen/internet/glasfaser/stadtnetze/stadtnetz-meilen-herrliberg/
# Disallow: /unternehmen/internet/glasfaser/stadtnetze/stadtnetz-baden/
# Disallow: /unternehmen/internet/glasfaser/stadtnetze/stadtnetz-lenzburg/
# Disallow: /unternehmen/internet/glasfaser/stadtnetze/stadtnetz-frauenfeld/
# Disallow: /unternehmen/internet/glasfaser/stadtnetze/stadtnetz-lindau/
# Disallow: /unternehmen/internet/glasfaser/stadtnetze/stadtnetz-basel/
# Disallow: /unternehmen/internet/glasfaser/schweizweit/
# Disallow: /unternehmen/internet/glasfaser/litexchange/
# Disallow: /unternehmen/internet/glasfaser/optionen/
# Disallow: /unternehmen/internet/glasfaser/hardware/
# Disallow: /unternehmen/internet/glasfaser/installation/
# Disallow: /unternehmen/internet/glasfaser/verfuegbarkeit/
# Disallow: /unternehmen/internet/hilfe/glasfaser-oder-dsl/
# Disallow: /unternehmen/internet/hilfe/ces/
# Disallow: /unternehmen/internet/hilfe/mpls/
# Disallow: /privatkunden/telefonie/telefonie/angebote/
# Disallow: /telefonie/telefonie/angebote/
# Disallow: /privatkunden/telefonie/telefonie/geraete/
# Disallow: /privatkunden/telefonie/telefonie/gespraechstarife/
# Disallow: /privatkunden/telefonie/telefonie/anleitungen-webportal/
# Disallow: /privatkunden/telefonie/telefonie/umstellung/
# Disallow: /hardware-preisliste/
# Disallow: /privatkunden/telefonie/das-aendert/umstellung/
# Disallow: /privatkunden/telefonie/das-aendert/was-ist-ip-telefonie/
# Disallow: /fritzbox/
# Disallow: /unternehmen/telefonie/mykmu/angebote/
# Disallow: /bestellung-mykmu/
# Disallow: /unternehmen/telefonie/mykmu/hardware/
# Disallow: /unternehmen/telefonie/mykmu/gespraechstarife/
# Disallow: /unternehmen/telefonie/mykmu/das-ist-mykmu/
# Disallow: /unternehmen/telefonie/vpbx/angebote/
# Disallow: /bestellung-vpbx/
# Disallow: /unternehmen/telefonie/vpbx/optionen/
# Disallow: /unternehmen/telefonie/vpbx/geraete/
# Disallow: /unternehmen/telefonie/vpbx/gespraechstarife/
# Disallow: /unternehmen/telefonie/vpbx/verwaltung/
# Disallow: /unternehmen/telefonie/vpbx/look-feel/
# Disallow: /unternehmen/telefonie/vpbx/das-ist-vpbx/
# Disallow: /unternehmen/telefonie/hosted-3cx/angebote/
# Disallow: /unternehmen/telefonie/hosted-3cx/lizenzen/
# Disallow: /unternehmen/telefonie/hosted-3cx/funktionen/
# Disallow: /unternehmen/telefonie/hosted-3cx/geraete/
# Disallow: /unternehmen/telefonie/hosted-3cx/gespraechstarife/
# Disallow: /offertenanfrage-voip-business/
# Disallow: /unternehmen/telefonie/trunk/angebote/
# Disallow: /unternehmen/telefonie/trunk/iway-business-trunk/
# Disallow: /unternehmen/telefonie/trunk/optionen/
# Disallow: /unternehmen/telefonie/trunk/gespraechstarife/
# Disallow: /bestellung-trunk/
# Disallow: /unternehmen/telefonie/voip/was-ist-voip/
# Disallow: /unternehmen/telefonie/voip/telefonieumstellung-2017/
# Disallow: /unternehmen/telefonie/voip/glossar/
# Disallow: /kontakt-formular/
# Disallow: /iway/ueber-iway/kontakt/
# Disallow: /iway/ueber-iway/team/
# Disallow: /iway/ueber-iway/unser-versprechen/
# Disallow: /iway/ueber-iway/offene-stellen/
# Disallow: /iway/ueber-iway/agb/
# Disallow: /datenschutzerklaerung/
# Disallow: /iway/ueber-iway/bankdaten/
# Disallow: /iway/ueber-iway/portrait/
# Disallow: /iway/providerstatus/
# Disallow: /iway/support/persoenlicher-support/
# Disallow: /iway/support/anleitungen/
# Disallow: /iway/support/kuendigungsvorlagen/
# Disallow: /iway/support/sender-policy-framework/
# Disallow: /iway/support/greylisting/
# Disallow: /iway/support/fernwartung/
# Disallow: /iway/umzug/
# Disallow: /blog/
# Disallow: /stoerungsmeldung/
# Disallow: /privatkunden/internet/dsl/verfuegbarkeit/
# Disallow: /partner-landing/
# Disallow: /impressum/
# Disallow: /privatkunden/hosting/webhosting/angebote/
# Disallow: /privatkunden/hosting/webhosting/optionen/
# Disallow: /privatkunden/hosting/webhosting/ssl-zertifikate/
# Disallow: /bestellung-shared-hosting/
# Disallow: /bestellung-ssl-zertifikat/
# Disallow: /unternehmen/hosting/web-hosting/angebote/
# Disallow: /unternehmen/hosting/web-hosting/optionen/
# Disallow: /unternehmen/hosting/web-hosting/ssl-zertifikate/
# Disallow: /unternehmen/hosting/web-hosting/weitere-angebote-business/
# Disallow: /privatkunden/hosting/mailhosting/angebote/
# Disallow: /bestellung-e-mail-hosting/
# Disallow: /unternehmen/hosting/mail-hosting/angebote/
# Disallow: /unternehmen/hosting/mail-hosting/sendnews-newsletter-tool/
# Disallow: /privatkunden/hosting/mailhosting/sendnews/
# Disallow: /unternehmen/hosting/ftp-hosting/angebote/
# Disallow: /unternehmen/hosting/hosted-exchange/angebote/
# Disallow: /unternehmen/hosting/hosted-exchange/uebersicht/
# Disallow: /unternehmen/hosting/hosted-exchange/technische-details/
# Disallow: /unternehmen/hosting/hosted-exchange/vorteile/
# Disallow: /privatkunden/cloud/net-backup/angebote/
# Disallow: /privatkunden/cloud/net-backup/optionen/
# Disallow: /privatkunden/cloud/net-backup/funktionsweise/
# Disallow: /privatkunden/cloud/net-backup/client-vergleich/
# Disallow: /unternehmen/cloud-services/net-backup/angebote/
# Disallow: /unternehmen/cloud-services/net-backup/optionen/
# Disallow: /unternehmen/cloud-services/net-backup/funktionsweise/
# Disallow: /unternehmen/cloud-services/net-backup/client-vergleich/
# Disallow: /bestellung-netbackup/
# Disallow: /unternehmen/cloud-services/net-backup/kostenlos-testen/
# Disallow: /privatkunden/cloud/net-backup/kostenlose-testversion/
# Disallow: /privatkunden/cloud/sync-share/angebote/
# Disallow: /privatkunden/cloud/sync-share/optionen/
# Disallow: /privatkunden/cloud/sync-share/was-ist-syncshare/
# Disallow: /privatkunden/cloud/sync-share/download-demo/
# Disallow: /bestellung-syncshare/
# Disallow: /unternehmen/cloud-services/sync-share/angebote/
# Disallow: /unternehmen/cloud-services/sync-share/optionen/
# Disallow: /unternehmen/cloud-services/sync-share/was-ist-sync-share/
# Disallow: /unternehmen/cloud-services/sync-share/download-demo/
# Disallow: /unternehmen/cloud-services/server/cloud-server-angebote/
# Disallow: /unternehmen/cloud-services/server/warum-virtuelle-server/
# Disallow: /unternehmen/cloud-services/server/vmware-angebote/
# Disallow: /bestellung-cloud-server/
# Disallow: /unternehmen/cloud-services/datacenter/rackspace-angebote/
# Disallow: /unternehmen/cloud-services/datacenter/ssl-zertifikate/
# Disallow: /privatkunden/domains/domainshop/domain-registrieren/
# Disallow: /privatkunden/domains/domainshop/domain-transferieren/
# Disallow: /privatkunden/domains/swiss/swiss-domain-beantragen/
# Disallow: /privatkunden/domains/swiss/swiss-kriterien/
# Disallow: /unternehmen/domains/domainshop/domain-registrieren/
# Disallow: /unternehmen/domains/domainshop/domain-transfer/
# Disallow: /unternehmen/domains/swiss/swiss-beantragen/
# Disallow: /unternehmen/domains/swiss/registrierungskriterien-swiss-domains/


# =========================================================================
# Old Site
# =========================================================================

# Disallow: /_downloads/productsheets/iw_ps_virtual_pbx.pdf
# Disallow: /revolution_services.php
# Disallow: /de/produkte/connectivity/ipv6/
# Disallow: /support/utilities/formular-mailer.aspx
# Disallow: /applications/hosted-sharepoint.aspx
# Disallow: /_downloads/Presse/20101109_MM_iway_lanciert_HEX2010.pdf
# Disallow: /partner.aspx
# Disallow: /de/ueberuns/partner/
# Disallow: /communication-and-email.aspx
# Disallow: /_downloads/Fiber/Flyer-Fiber-Glasfaser-Internet-und-Telefonie-Bern.pdf
# Disallow: /privatkunden/media_category/logos/
# Disallow: /communication-and-email/office/preise.aspx
# Disallow: /support/utilities/counter.aspx
# Disallow: /privatkunden/media_category/content-750/
# Disallow: /privatkunden/media_category/bilder/
# Disallow: /_downloads/VoIP/20110510-iway-POA-MSN-Fr.pdf
# Disallow: /_downloads/IwayAUP-AcceptableUsePolicy.pdf
# Disallow: /osMedia/doc/200807_produktblatt_sharedhost_0512.pdf
# Disallow: /support/utilities.aspx
# Disallow: /privatkunden/media_category/geraete/
# Disallow: /ueber-iway-kontakt/iway/team/blert-barileva.aspx
# Disallow: /_iframes/passwortgenerator.php?length=32&specialchars=n&submit=Passwort+generieren
# Disallow: /support/utilities/passwort-generator.aspx
# Disallow: /communication-and-email/sms.aspx
# Disallow: /support/utilities/fastviewer.aspx
# Disallow: /ueber-iway-kontakt/newsletter/abmeldung.aspx
# Disallow: /wp-content/uploads/2015/08/IwayAUP-AcceptableUsePolicy.pdf
# Disallow: /communication-and-email/sms/sms-gateway.aspx
# Disallow: /de/support/suchen/?search=webmail
# Disallow: /ueber-iway-kontakt/iway/pressemitteilungen.aspx
# Disallow: /ueber-iway-kontakt/iway/sponsoring.aspx
# Disallow: /_downloads/productsheets/20121111-Produkteblatt-NetBackup.pdf
# Disallow: /webstatistik/media/player.swf
# Disallow: /privatkunden/wp-content/uploads/sites/3/2015/12/Ursachen-und-Probleml%C3%B6sung-Funkst%C3%B6rungen-iWay-2015.pdf
# Disallow: /ueber-iway-kontakt/iway/team/patricia-weisskopf.aspx
# Disallow: /ueber-iway-kontakt/iway/team/markus-vetterli.aspx
# Disallow: /_downloads/MailSystemUpgrade-Kunden-Info-Deutsch.pdf
# Disallow: /ueber-iway-kontakt/iway/team/christoph-roethlisberger.aspx
# Disallow: /ueber-iway-kontakt/iway/team/karin-oswald.aspx
# Disallow: /webstatistik/
# Disallow: /_iframes/passwortgenerator.php?length=10&specialchars=n&submit=Passwort+generieren
# Disallow: /application-hosting/hosted-sharepoint.aspx
# Disallow: /privatkunden/phone/iway-home-telefonie-fuer-privathaushalte/attachment/sn_760-2/
# Disallow: /privatkunden/wp-content/uploads/sites/3/2015/11/iway-rgbeilage-oktober-final.pdf
# Disallow: /privatkunden/wp-content/uploads/sites/3/2016/04/iway-rgbeilage-private-apr16.pdf
# Disallow: /privatkunden/wp-content/uploads/sites/3/2017/04/iway-rgbeilage-apr17_Privat.pdf
# Disallow: /privatkunden/wp-content/uploads/sites/3/2017/04/iway-rgbeilage-private-okt16_final.pdf
# Disallow: /ewz-stadtnetz/sony-dsc-2/
# Disallow: /maler-und-gipser-kmu/
# Disallow: /privatkunden/dsl-atlas/
# Disallow: /iway-business/business_gastronomie5/
# Disallow: /shop/
# Disallow: /iway-business/business_gastronomie3/
# Disallow: /media_category/logos/
# Disallow: /bwewetest/
# Disallow: /osMedia/doc/adsl_bestellform_business_20090505_1254.doc
# Disallow: /de/produkte/productivity/cms/typo3.php
# Disallow: /osSite/osPicWin.php?pic=/osMedia/pic/webko_1236_or.jpg&template=1
# Disallow: /cloud-services/cloud-services/cloud-3-phasen-modell.aspx
# Disallow: /osMedia/doc/2007-07-19-fastviewer_produktmappe_de_3040.pdf
# Disallow: /osMedia/doc/firmware-updatezyxelvdsl_1120.pdf
# Disallow: /~rwalker/tamahome.html
# Disallow: /_downloads/Fiber/Flyer-Fiber-Glasfaser-Internet-und-Telefonie-ewz.zuerinet-Zuerich.pdf
# Disallow: /privatkunden/xmlrpc.php?rsd
# Disallow: /privatkunden/glossary
# Disallow: /_downloads/MailSystemUpgrade-Kunden-Info-English.pdf
# Disallow: /interway/ch_dir.html
# Disallow: /businesstarife?pid=301506
# Disallow: /de/support/nettools/lookinglass.php
# Disallow: /:/www.ewz.ch
# Disallow: /de/support/suchen/?start=21&search=aufl%25F6sungen
# Disallow: /de/technopark/tpinternetaccess.php
# Disallow: /de/support/suchen/?start=71&search=r%25E4umlichkeiten
# Disallow: /de/produkte/connectivity/ipass/
# Disallow: /osMedia/doc/linksys_spa1001_1126.pdf
# Disallow: /privatkunden/wp-includes/js/wp
# Disallow: /wp-content/themes/iway/js/jque
# Disallow: /privatkunden/wp-content/plugin
# Disallow: /~sos/cndrop.html
# Disallow: /--------------enigD2AA2D493EE7AC69D54019DCContent-Type
# Disallow: /beaniwaysurfer.php
# Disallow: /interway/rwd/index.html
# Disallow: /~jwolve/home.html
# Disallow: /privatkunden/wp-content/upload
# Disallow: /de/support/suchen/?start=61&search=f%25E4higen
# Disallow: /de/support/suchen/?search=openscope
# Disallow: /display_game.php?game=index
# Disallow: /de/support/suchen/?start=1&search=l%25E4ngen
# Disallow: /de/support/suchen/?start=11&search=t%25E4gliches
# Disallow: /de/support/suchen/?start=71&search=erm%25F6glicht
# Disallow: /de/support/suchen/?start=11&search=shop
# Disallow: /de/support/suchen/?start=11&search=qualit%25E4tsklasse
# Disallow: /de/support/suchen/?start=21&search=technoparkr%25E4umlichkeiten
# Disallow: /de/support/suchen/?start=1&search=services
# Disallow: /de/support/suchen/?search=zus%25E4tzliche&start=41
# Disallow: /de/support/suchen/?start=51&search=leitungsqualit%25E4t
# Disallow: /%20rel=
# Disallow: /osMedia/doc/mm_20070130_retoschmidt_1551.pdf
# Disallow: /key/ASWD56425CSA
# Disallow: /xmlrpc.php
# Disallow: /privatkunden/xmlrpc.php
# Disallow: /?p=11864
# Disallow: /?p=11868
# Disallow: /privatkunden/wp-content/uploads/sites/3/2016/02/Preisliste-Internet-Domains-16022016.pdf
# Disallow: /partnerevent-2016/
# Disallow: /lbcmanager/downloadseite.html
# Disallow: /privatkunden/?p=2374
# Disallow: /split/
# Disallow: /tryandbuy/
# Disallow: /tryandbuy-form/
# Disallow: /tryandbuy-danke/
# Noindex: /_downloads/productsheets/iw_ps_virtual_pbx.pdf
# Noindex: /revolution_services.php
# Noindex: /de/produkte/connectivity/ipv6/
# Noindex: /support/utilities/formular-mailer.aspx
# Noindex: /applications/hosted-sharepoint.aspx
# Noindex: /_downloads/Presse/20101109_MM_iway_lanciert_HEX2010.pdf
# Noindex: /partner.aspx
# Noindex: /de/ueberuns/partner/
# Noindex: /communication-and-email.aspx
# Noindex: /_downloads/Fiber/Flyer-Fiber-Glasfaser-Internet-und-Telefonie-Bern.pdf
# Noindex: /privatkunden/media_category/logos/
# Noindex: /communication-and-email/office/preise.aspx
# Noindex: /support/utilities/counter.aspx
# Noindex: /privatkunden/media_category/content-750/
# Noindex: /privatkunden/media_category/bilder/
# Noindex: /_downloads/VoIP/20110510-iway-POA-MSN-Fr.pdf
# Noindex: /_downloads/IwayAUP-AcceptableUsePolicy.pdf
# Noindex: /osMedia/doc/200807_produktblatt_sharedhost_0512.pdf
# Noindex: /support/utilities.aspx
# Noindex: /privatkunden/media_category/geraete/
# Noindex: /ueber-iway-kontakt/iway/team/blert-barileva.aspx
# Noindex: /_iframes/passwortgenerator.php?length=32&specialchars=n&submit=Passwort+generieren
# Noindex: /support/utilities/passwort-generator.aspx
# Noindex: /communication-and-email/sms.aspx
# Noindex: /support/utilities/fastviewer.aspx
# Noindex: /ueber-iway-kontakt/newsletter/abmeldung.aspx
# Noindex: /wp-content/uploads/2015/08/IwayAUP-AcceptableUsePolicy.pdf
# Noindex: /communication-and-email/sms/sms-gateway.aspx
# Noindex: /de/support/suchen/?search=webmail
# Noindex: /ueber-iway-kontakt/iway/pressemitteilungen.aspx
# Noindex: /ueber-iway-kontakt/iway/sponsoring.aspx
# Noindex: /_downloads/productsheets/20121111-Produkteblatt-NetBackup.pdf
# Noindex: /webstatistik/media/player.swf
# Noindex: /privatkunden/wp-content/uploads/sites/3/2015/12/Ursachen-und-Probleml%C3%B6sung-Funkst%C3%B6rungen-iWay-2015.pdf
# Noindex: /ueber-iway-kontakt/iway/team/patricia-weisskopf.aspx
# Noindex: /ueber-iway-kontakt/iway/team/markus-vetterli.aspx
# Noindex: /_downloads/MailSystemUpgrade-Kunden-Info-Deutsch.pdf
# Noindex: /ueber-iway-kontakt/iway/team/christoph-roethlisberger.aspx
# Noindex: /ueber-iway-kontakt/iway/team/karin-oswald.aspx
# Noindex: /webstatistik/
# Noindex: /_iframes/passwortgenerator.php?length=10&specialchars=n&submit=Passwort+generieren
# Noindex: /application-hosting/hosted-sharepoint.aspx
# Noindex: /privatkunden/phone/iway-home-telefonie-fuer-privathaushalte/attachment/sn_760-2/
# Noindex: /privatkunden/wp-content/uploads/sites/3/2015/11/iway-rgbeilage-oktober-final.pdf
# Noindex: /privatkunden/wp-content/uploads/sites/3/2016/04/iway-rgbeilage-private-apr16.pdf
# Noindex: /privatkunden/wp-content/uploads/sites/3/2017/04/iway-rgbeilage-apr17_Privat.pdf
# Noindex: /privatkunden/wp-content/uploads/sites/3/2017/04/iway-rgbeilage-private-okt16_final.pdf
# Noindex: /ewz-stadtnetz/sony-dsc-2/
# Noindex: /maler-und-gipser-kmu/
# Noindex: /privatkunden/dsl-atlas/
# Noindex: /iway-business/business_gastronomie5/
# Noindex: /shop/
# Noindex: /iway-business/business_gastronomie3/
# Noindex: /media_category/logos/
# Noindex: /bwewetest/
# Noindex: /osMedia/doc/adsl_bestellform_business_20090505_1254.doc
# Noindex: /de/produkte/productivity/cms/typo3.php
# Noindex: /osSite/osPicWin.php?pic=/osMedia/pic/webko_1236_or.jpg&template=1
# Noindex: /cloud-services/cloud-services/cloud-3-phasen-modell.aspx
# Noindex: /osMedia/doc/2007-07-19-fastviewer_produktmappe_de_3040.pdf
# Noindex: /osMedia/doc/firmware-updatezyxelvdsl_1120.pdf
# Noindex: /~rwalker/tamahome.html
# Noindex: /_downloads/Fiber/Flyer-Fiber-Glasfaser-Internet-und-Telefonie-ewz.zuerinet-Zuerich.pdf
# Noindex: /privatkunden/xmlrpc.php?rsd
# Noindex: /privatkunden/glossary
# Noindex: /_downloads/MailSystemUpgrade-Kunden-Info-English.pdf
# Noindex: /interway/ch_dir.html
# Noindex: /businesstarife?pid=301506
# Noindex: /de/support/nettools/lookinglass.php
# Noindex: /:/www.ewz.ch
# Noindex: /de/support/suchen/?start=21&search=aufl%25F6sungen
# Noindex: /de/technopark/tpinternetaccess.php
# Noindex: /de/support/suchen/?start=71&search=r%25E4umlichkeiten
# Noindex: /de/produkte/connectivity/ipass/
# Noindex: /osMedia/doc/linksys_spa1001_1126.pdf
# Noindex: /privatkunden/wp-includes/js/wp
# Noindex: /wp-content/themes/iway/js/jque
# Noindex: /privatkunden/wp-content/plugin
# Noindex: /~sos/cndrop.html
# Noindex: /--------------enigD2AA2D493EE7AC69D54019DCContent-Type
# Noindex: /beaniwaysurfer.php
# Noindex: /interway/rwd/index.html
# Noindex: /~jwolve/home.html
# Noindex: /privatkunden/wp-content/upload
# Noindex: /de/support/suchen/?start=61&search=f%25E4higen
# Noindex: /de/support/suchen/?search=openscope
# Noindex: /display_game.php?game=index
# Noindex: /de/support/suchen/?start=1&search=l%25E4ngen
# Noindex: /de/support/suchen/?start=11&search=t%25E4gliches
# Noindex: /de/support/suchen/?start=71&search=erm%25F6glicht
# Noindex: /de/support/suchen/?start=11&search=shop
# Noindex: /de/support/suchen/?start=11&search=qualit%25E4tsklasse
# Noindex: /de/support/suchen/?start=21&search=technoparkr%25E4umlichkeiten
# Noindex: /de/support/suchen/?start=1&search=services
# Noindex: /de/support/suchen/?search=zus%25E4tzliche&start=41
# Noindex: /de/support/suchen/?start=51&search=leitungsqualit%25E4t
# Noindex: /%20rel=
# Noindex: /osMedia/doc/mm_20070130_retoschmidt_1551.pdf
# Noindex: /key/ASWD56425CSA
# Noindex: /xmlrpc.php
# Noindex: /privatkunden/xmlrpc.php
# Noindex: /?p=11864
# Noindex: /?p=11868
# Noindex: /privatkunden/wp-content/uploads/sites/3/2016/02/Preisliste-Internet-Domains-16022016.pdf
# Noindex: /partnerevent-2016/
# Noindex: /lbcmanager/downloadseite.html
# Noindex: /privatkunden/?p=2374
# Noindex: /split/
# Noindex: /tryandbuy/
# Noindex: /tryandbuy-form/
# Noindex: /tryandbuy-danke/