User-agent: *
Disallow: *tplmode=print
Disallow: *tpl=r_news_popular
Disallow: */signin
Disallow: */login
Disallow: */share
Disallow: */search
Disallow: /click

Host: https://isport.ua

User-agent: Slurp
Disallow: /
User-agent: Gigabot
Disallow: /
User-agent: Scrubby
Disallow: /
User-agent: Robozilla
Disallow: /
User-agent: Nutch
Disallow: /
User-agent: psbot
Disallow: /
User-agent: asterias
Disallow: /

Sitemap: https://isport.ua/sitemap.xml
Sitemap: https://isport.ua/sitemap.news.xml

