User-agent: *
Disallow: /cgi-bin/
Disallow: /test/
Disallow: /sapredir/
Disallow: /persoverzicht/
Disallow: /maps/
Disallow: /english/life-at-ku-leuven/money-matters/social-services-students/reduced-tuition-fee
Disallow: /bevestiging-inschrijving
Disallow: /english/application-submitted
Disallow: /english/registration-completed
Disallow: /opleidingen/bachelor-geneeskunde
Disallow: /opleidingen/bachelor-biomedische-wetenschappen
Disallow: /opleidingen/master-biomedische-wetenschappen/schakelprogramma
Disallow: /opleidingen/bachelor-architectuur
Disallow: /opleidingen/bachelor-geschiedenis
Disallow: /opleidingen/bachelor-interieurarchitectuur
Disallow: /opleidingen/bachelor-revalidatiewetenschappen-kinesitherapie
Disallow: /programmes/master-business-administration
