User-agent: *
Disallow: /orderstraat/
Disallow: /page/
Disallow: /handelsregister/TST-BIN/
Disallow: /bestellen/
Disallow: /bestellen-ubo/
Disallow: /bestellen-ubo-geen-toegang/
Disallow: /_next/
Disallow: /overzicht/fase/
Disallow: /overzicht/thema/
Disallow: /overzicht/transactie/
Disallow: /overzicht/organisatie/
Disallow: /overzicht/auteur/
Disallow: /overzicht/documentType/
Disallow: /persoverzicht/fase/
Disallow: /persoverzicht/thema/
Disallow: /persoverzicht/transactie/
Disallow: /persoverzicht/organisatie/
Disallow: /woo-publicaties/documentType/
Disallow: /woo-publicaties/wetOpenOverheid/
Sitemap: https://www.kvk.nl/sitemap_index.xml
Sitemap: https://www.kvk.nl/en/sitemap_index.xml
Sitemap: https://www.kvk.nl/sitemapindex-diwoo-infocat004.xml
Sitemap: https://www.kvk.nl/sitemapindex-diwoo-infocat005.xml
Sitemap: https://www.kvk.nl/sitemapindex-diwoo-infocat011.xml
Sitemap: https://www.kvk.nl/sitemapindex-diwoo-infocat012.xml
Sitemap: https://www.kvk.nl/sitemapindex-diwoo-infocat014.xml
Sitemap: https://www.kvk.nl/sitemapindex-diwoo-infocat015.xml
Sitemap: https://www.kvk.nl/sitemapindex-diwoo-infocat016.xml
Sitemap: https://www.kvk.nl/sitemapindex-diwoo-infocat017.xml
