# Sitemaps
Sitemap: https://www.lalibre.be/arc/outboundfeeds/sitemap-index/?outputType=xml
Sitemap: https://www.lalibre.be/arc/outboundfeeds/sitemap-index/news/?outputType=xml
Sitemap: https://www.lalibre.be/arc/outboundfeeds/sitemap-news/?outputType=xml
Sitemap: https://www.lalibre.be/arc/outboundfeeds/sitemap-section/?outputType=xml

# Disallow some files and directories for all bots
User-agent: *
Disallow: /apc.php
Disallow: /partners/
Disallow: /phpinfo.php
Disallow: /preview/
Disallow: /pub/
Disallow: /recherche
Disallow: /profil
Disallow: /redirect/
Disallow: /status/
Disallow: /test/
Disallow: /edition-abonne
Disallow: /podcast
Disallow: /undefined.html
Disallow: *gclid=
Disallow: /pf/resources/dist/fonts/*
Disallow: /pf/resources/dist/images/*
Disallow: /pf/resources/plugins/*
Disallow: /pf/api/*
Disallow: /*outputType=android
Disallow: /*outputType=ios
Disallow: /*outputType=app

# Allow Mediapartners-Google *
User-agent: Mediapartners-Google
Allow: /

# Disallow undesired bots
User-agent: 5emeRue
Disallow: /
User-agent: 5erue
Disallow: /
User-agent: adequat
Disallow: /
User-agent: adequat-systems
Disallow: /
User-agent: AmiSoftware
Disallow: /
User-agent: Argus
Disallow: /
User-agent: Ask n read
Disallow: /
User-agent: asknread.com
Disallow: /
User-agent: Augure
Disallow: /
User-agent: auramundi
Disallow: /
User-agent: Bloodhound
Disallow: /
User-agent: CCBot
Disallow: /
User-agent: ChatGPT-User
Disallow: /
User-agent: Cision
Disallow: /
User-agent: Claudebot
Disallow: /
User-agent: Cliqzbot
Disallow: /
User-agent: coexel
Disallow: /
User-agent: ConveraCrawler
Disallow: /
User-agent: Corporama
Disallow: /
User-agent: cydralspider
Disallow: /
User-agent: Digimind
Disallow: /
User-agent: Dotbot
Disallow: /
User-agent: Download Ninja
Disallow: /
User-agent: downloadexpress
Disallow: /
User-agent: EDD
Disallow: /
User-agent: ellisphere
Disallow: /
User-agent: eureka
Disallow: /
User-agent: Europresse
Disallow: /
User-agent: Explore
Disallow: /
User-agent: Factiva
Disallow: /
User-agent: Fasterfox
Disallow: /
User-agent: Fetch
Disallow: /
User-agent: FirstRain
Disallow: /
User-agent: gammaSpider
Disallow: /
User-agent: GnowitNewsbot
Disallow: /
User-agent: Google-Extended
Disallow: /
User-agent: GPTBot
Disallow: /
User-agent: grub-client
Disallow: /
User-agent: ia_archiver
Disallow: /
User-agent: ia_archiver-web.archive.org
Disallow: /
User-agent: indexer
Disallow: /
User-agent: infoseek
Disallow: /
User-agent: Jetbot
Disallow: /
User-agent: k2spider
Disallow: /
User-agent: Kantar
Disallow: /
User-agent: kbcrawl
Disallow: /
User-agent: Knowings
Disallow: /
User-agent: larbin
Disallow: /
User-agent: leadbox
Disallow: /
User-agent: libwww
Disallow: /
User-agent: linkfluence
Disallow: /
User-agent: linko
Disallow: /
User-agent: manageo
Disallow: /
User-agent: MaxPointCrawler
Disallow: /
User-agent: mediacompil
Disallow: /
User-agent: Meltawer
Disallow: /
User-agent: Meltwater
Disallow: /
User-agent: mention
Disallow: /
User-agent: Moreover
Disallow: /
User-agent: MSIECrawler
Disallow: /
User-agent: mytwip
Disallow: /
User-agent: newscan-online
Disallow: /
User-agent: NewsNow
Disallow: /
User-agent: Newzbin
Disallow: /
User-agent: NPBot
Disallow: /
User-agent: Nutch
Disallow: /
User-agent: ObjectsSearch
Disallow: /
User-Agent: omgili
Disallow: /
User-Agent: omgilibot
Disallow: /
User-agent: opinion-tracker
Disallow: /
User-agent: Pimptrain
Disallow: /
User-agent: proxem
Disallow: /
User-agent: QuepasaCreep
Disallow: /
User-agent: Qwam content intelligence
Disallow: /
User-agent: Raven
Disallow: /
User-agent: readability.com
Disallow: /
User-agent: Riddler
Disallow: /
User-agent: rogerbot
Disallow: /
User-agent: scoop.it
Disallow: /
User-agent: score3
Disallow: /
User-agent: SearchmetricsBot
Disallow: /
User-agent: Sindup
Disallow: /
User-agent: sitecheck.internetseer.com
Disallow: /
User-agent: SiteSnagger
Disallow: /
User-agent: spotter
Disallow: /
User-agent: Synthesio
Disallow: /
User-agent: Talkwater
Disallow: /
User-agent: Teleport
Disallow: /
User-agent: TeleportPro
Disallow: /
User-agent: trendeo
Disallow: /
User-agent: trendybuzz
Disallow: /
User-agent: TunitinBot
Disallow: /
User-agent: TurnitinBot
Disallow: /
User-agent: up2news
Disallow: /
User-agent: vecteurplus
Disallow: /
User-agent: Verif
Disallow: /
User-agent: verticalsearch
Disallow: /
User-agent: vsw
Disallow: /
User-agent: wapspider
Disallow: /
User-agent: WebCopier
Disallow: /
User-agent: WebReaper
Disallow: /
User-agent: WebStripper
Disallow: /
User-agent: WebZinger
Disallow: /
User-agent: WebZip
Disallow: /
User-agent: winello
Disallow: /
User-agent: XoviBot
Disallow: /
User-agent: Youmag
Disallow: /
User-agent: Zealbot
Disallow: /
User-agent: Zite
Disallow: /
User-agent: ZyBORG
Disallow: /
User-agent: Amazonbot
Disallow: /
User-agent: Applebot-Extended
Disallow: /
User-agent: anthropic-ai
Disallow: /
User-agent: Bytespider
Disallow: /
User-agent: Claude-Web
Disallow: /
User-agent: cohere-ai
Disallow: /
User-agent: FacebookBot
Disallow: /
User-agent: Meta-ExternalAgent
Disallow: /
User-agent: Meta-ExternalFetcher
Disallow: /
User-agent: OAI-SearchBot
Disallow: /
User-agent: PerplexityBot
Disallow: /
User-agent: AI2Bot
Disallow: /
User-agent: DuckAssistBot
Disallow: /