User-Agent: *
Disallow: *admin
Disallow: *back_url
Disallow: *bitrix_include
Disallow: *clear_cache=
Disallow: *edit.php
Disallow: *etext
Disallow: *filter
Disallow: *height=
Disallow: *KEY*=
Disallow: *width=
Disallow: /node/
Disallow: /privacy/
Disallow: /products/lb360/
Disallow: /search/
Disallow: /sites/
Disallow: /ssh/
Disallow: /taxonomy/term/
Disallow: /technical-information/documentation/core-settings/
Disallow: /technical-information/documentation/documentation/
Disallow: /technical-information/documentation/nas-settings/
Disallow: /technical-information/documentation/payment-systems/
Disallow: /technical-information/use-cases/
Disallow: /products/wifi/
Disallow: /en/products/wifi/
Disallow: *.pdf
Sitemap: https://www.lanbilling.ru/sitemap.xml
