User-agent: *
Disallow: o-regione/pochetnye-grazhdane/
Disallow: gubernator/fotogalereya/
Disallow: pravitelstvo-leningradskoj-oblasti/informacionnye-sistemy/
Disallow: dlya-smi/fotogalereya-gubernatora/
Disallow: dlya-smi/accreditation/zayavka-na-akkreditaciyu-zhurnalistov/
Disallow: dokumenty/opublikovanie-pravovyh-aktov/opublikovanie-pravovyh-aktov-leningradskoj-oblasti-s-3-po-7-iyunya-201/
Disallow: dokumenty/opublikovanie-pravovyh-aktov/oficialnoe-opublikovanie-pravovyh-aktov-leningradskoj-oblasti-s-10-iyu/
Disallow: deyatelnost/protivodejstvie-korrupcii/
Disallow: deyatelnost/portal-gosuslug/
Disallow: informaciya/statistika/
Disallow: informaciya/xxx/
Disallow: informaciya/interaktivnye-oprosy/anketa-oprosa-naseleniya-ob-ocenke-effektivnosti-deyatelnosti-rukovodi/
Disallow: kontakty/o-portale/statistika-poseshaemosti/
Disallow: kontakty/priemnaya-grazhdan-pravitelstva-leningradskoj-oblasti/obzory-obrashenij-grazhdan/
Disallow: koryushka/
Disallow: obshaya-informaciya/protivodejstvie-korrupcii/nezavisimaya-antikorrupcionnaya-ekspertiza/
Disallow: programmy-i-plany/zashita-prav-potrebitelej/organizaciya-besplatnoj-yuridicheskoj-pomoshi-po-voprosam-zashity-2020/
Disallow: pravovaya-baza/npa47/
Disallow: pravovaya-baza/npa47_antikorr/
Disallow: nacionalnaya-politika/
Disallow: informaciya/protivodejstvie-korrupcii/antikorrupcionnaya-ekspertiza/
Disallow: informaciya/protivodejstvie-korrupcii/metodicheskie-materialy/
Disallow: informaciya/protivodejstvie-korrupcii/formy-dokumentov-svyazannyh-s-protivodejstviem-korrupcii-dlya-zapolnen/
Disallow: informaciya/protivodejstvie-korrupcii/obratnaya-svyaz-dlya-soobshenij-o-faktah-korrupcii/
Disallow: dokumenty/npa47/
Disallow: dokumenty/npa47_antikorr/
Disallow: dokumenty/gos-reg/
Disallow: knigoizdanie/
Disallow: socialnaya-reklama/
Disallow: socialnaya-reklama/osushestvlenie-gosudarstvennoj-politiki-v-sfere-reklamy-i-socialnoj-re/makety-socialnoj-reklamy-2025/
Disallow: socialnaya-reklama/osushestvlenie-gosudarstvennoj-politiki-v-sfere-reklamy-i-socialnoj-re/makety-socialnoj-reklamy-2024/
Disallow: podderzhka-socialno-orientirovannyh-nekommercheskih-organizacij/finansovaya-podderzhka/subsidy_nko/
Disallow: programm/corrupt1/
Disallow: law/npa47/
Disallow: law/npa47_antikorr/
Disallow: dokumenty/protivodejstvie-korrupcii/metodicheskie-materialy/
Disallow: dokumenty/protivodejstvie-korrupcii/formy-dokumentov-svyazannyh-s-protivodejstviem-korrupcii/
Disallow: dokumenty/protivodejstvie-korrupcii/svedeniya-o-dohodah-rashodah-ob-imushestve-i-obyazatelstvah-imushestve/
Disallow: dokumenty/100letiegosudarstvennoysluzbi/sobytiya/ekskursiya-dlya-shkolnikov-mladshih-klassov-v-arhivnom-otdele-administ/
Disallow: dokumenty/fotogalereya/sobranie-trudovogo-kollektiva-oblastnogo-gosudarstvennogo-arhiva-8-fev/fhgfgfjfhfjf/
Disallow: deiatelnost/npa47/
Disallow: deiatelnost/npa47_antikorr/
Disallow: dokumenty/npa47/
Disallow: npa47_antikorr/
Disallow: informaciya/antikorup/obratnaya-svyaz-telefonnaya-liniya-protivodejstvie-korrupcii/
Disallow: law/npa47/
Disallow: law/npa47_antikorr/
Disallow: dokumenty/npa47/
Disallow: deiatelnost/protivodeistvie-korruptsii/npa47_antikorr/
Disallow: deiatelnost/protivodeistvie-korruptsii/metodicheskie-materialy/
Disallow: deiatelnost/protivodeistvie-korruptsii/formy-dokumentov-svyazannye-s-protivodejstviem-korrupcii-dlya-zapolnen/
Disallow: deiatelnost/protivodeistvie-korruptsii/forma-obratnoj-svyazi/
Disallow: kadry/vakansy/
Disallow: kadry/poryadok-postupleniya-grazhdan-na-gosudarstvennuyu-grazhdanskuyu-sluzh/
Disallow: o-komitete/podvedomsvennye-organizacii/plany-provedeniya-proverok-podvedomstvennyh-uchrezhdenij/
Disallow: o-komitete/podvedomsvennye-organizacii/rezultaty-proverok-podvedomstvennyh-uchrezhdenij/
Disallow: o-komitete/kadry/vakansi/
Disallow: informaciya/obshestvennye-obsuzhdeniya/
Disallow: deyatelnost/deiatelnost/gosudarstvennyj-stroitelnyj-nadzor/formy-dokumentov/
Disallow: deyatelnost/ispolnenie-ukazov-prezidenta-rossijskoj-federacii/
Disallow: dokumenty/npa47/
Disallow: dokumenty/npa47_antikorr/
Disallow: protivodeistvie-korruptsii/metodicheskie-materialy/
Disallow: protivodeistvie-korruptsii/antikorrupcionnoe-prosveshenie-grazhdan/stranica-sajta-generalnoj-prokuratury-rossijskoj-federacii-po-voprosam/
Disallow: protivodeistvie-korruptsii/antikorrupcionnoe-prosveshenie-grazhdan/antikorrupcionnie-pamyatki-i-buklety/
Disallow: protivodeistvie-korruptsii/antikorrupcionnoe-prosveshenie-grazhdan/video-prezentaciya-protivodejstvie-korrupcii-v-rossii/
Disallow: protivodeistvie-korruptsii/antikorrupcionnoe-prosveshenie-grazhdan/antikorrupcionnie-videoroliki/
Disallow: protivodeistvie-korruptsii/antikorrupcionnoe-prosveshenie-grazhdan/formy-dokumentov/
Disallow: protivodeistvie-korruptsii/antikorrupcionnoe-prosveshenie-grazhdan/anonimnyj-opros-v-sfere-profilaktiki-korrupcii/
Disallow: dokumenty/npa47_antikorr/
Disallow: dokumenty/npa47/
Disallow: contakt/telefonnyj-spravochnik/
Disallow: deiatelnost/nadzornaya-deyatelnost/svedeniya-o-predostavlennyh-organizaciyam-i-individualnym-predprinimat/
Disallow: deiatelnost/nadzornaya-deyatelnost/otnesenie-obektov-gosudarstvennogo-kontrolya-nadzora-k-kategoriyam-ris/rasporyazhenie_ot_07022024_14-03-5_2024/
Disallow: deiatelnost/zakupki/
Disallow: dokumenty/npa47/
Disallow: dokumenty/npa47_antikorr/
Disallow: o-komitete/informatsionnye-sistemy/reestr-gis/
Disallow: dokumenty/npa47/
Disallow: dokumenty/npa47_antikorr/
Disallow: deiatelnost/plan-meropriiatii-po-protivodeistviiu-korruptsii/svedeniya-o-dohodah-rashodah-ob-imushestve-i-obyazatelstvah-imushestve/svedeniya-o-dohodah-rashodah-lic-zameshayushih-gosudarstvennye-dolzhno/
Disallow: deiatelnost/plan-meropriiatii-po-protivodeistviiu-korruptsii/formy-blanki/
Disallow: deiatelnost/plan-meropriiatii-po-protivodeistviiu-korruptsii/antikorrupcionnaya-ekspertiza/
Disallow: polls/onlajn-opros-kultura-granty-rossii/
Disallow: upravlenie-obrazovaniem/depobr/otdel-socialnoj-zashity-i-specialnyh-uchrezhdenij/desyatiletie-detstva-v-rossijskoj-federacii/
Disallow: law/npa47_antikorr/
Disallow: law/npa47/
Disallow: o-komitete/napravleniya-deyatelnosti/sodejstvie-sadovodcheskim-ogorodnicheskim-i-dachnym-nekommercheskim-ob/syuzhet-leningradskoj-oblastnoj-telekompanii-o-gosudarstvennoj-podderz/
Disallow: deiatelnost/oprosy/
Disallow: pravovaya-baza/npa47/
Disallow: pravovaya-baza/npa47_antikorr/
Disallow: kadry/protivodeistvie-korruptsii/normativnye-pravovye-i-inye-akty-v-sfere-protivodejstviya-korrupcii/
Disallow: kadry/protivodeistvie-korruptsii/svedeniya-o-dohodah-rashodah-lic-zameshayushih-gosudarstvennye-dolzhno/
Disallow: kadry/protivodeistvie-korruptsii/formy-dokumentov-svyazannyh-s-protivodejstviem-korrupcii-dlya-zapolnen/
Disallow: kadry/protivodeistvie-korruptsii/metodicheskie-materialy/
Disallow: kadry/protivodeistvie-korruptsii/plan-meropriiatii-po-protivodeistviiu-korruptsii/plany-protivodejstviya-korrupcii-v-leningradskoj-oblasti-i-otchety-ob-/
Disallow: o-komitete/podvedomstvennye-uchrezhdeniya/podvedomstvennye-organizatsii/goszakaz-leningradskoj-oblasti-elektronnyj-magazin-leningradskoj-oblas/
Disallow: o-komitete/podvedomstvennye-uchrezhdeniya/podvedomstvennye-organizatsii/plan-grafik-zakupok-na-2021-god-razmeshennyj-na-oficialnom-sajte-edino/
Disallow: o-komitete/podvedomstvennye-uchrezhdeniya/podvedomstvennye-organizatsii/informaciya-o-zakupkah-razmeshennyh-na-oficialnom-sajte-edinoj-informa/
Disallow: dokumenty/setevoe-izdanie-elektronnoe-opublikovanie-dokumentov-npa47ru/
Disallow: dokumenty/npa47/
Disallow: dokumenty/normativy-gradostroitelnogo-proektirovaniya/regionalnye-normativy-gradostroitelnogo-proektirovaniya/
Disallow: dokumenty/normativy-gradostroitelnogo-proektirovaniya/mngp/
Disallow: dokumenty/npa47_antikorr/
Disallow: deiatelnost/protivodeistvie-korruptsii/plan-meropriiatii-po-protivodeistviiu-korruptsii/
Disallow: deiatelnost/protivodeistvie-korruptsii/metodicheskie-materialy/
Disallow: deiatelnost/protivodeistvie-korruptsii/formy-dokumentov-svyazannyh-s-protivodejstviem-korrupcii-dlya-zapolnen/
Disallow: deiatelnost/plan-meropriiatii-po-protivodeistviiu-korruptsii/antikorrupcionnaya-ekspertiza/
Disallow: deiatelnost/plan-meropriiatii-po-protivodeistviiu-korruptsii/metodicheskie-materialy/
Disallow: deiatelnost/plan-meropriiatii-po-protivodeistviiu-korruptsii/formy-dokumentov-svyazannyh-s-protivodejstviem-korrupcii-dlya-zapolnen/
Disallow: dokumenty/npa47/
Disallow: dokumenty/npa47_antikorr/
Disallow: o-komitete/podvedomstvennye-organizatsii/konkursy-na-pravo-zamesheniya-vakantnoj-dolzhnosti-rukovoditelya-direk/
Disallow: dokumenty/npa47/
Disallow: dokumenty/npa47_antikorr/
Disallow: dokumenty/plan-meropriiatii-po-protivodeistviiu-korruptsii/metodicheskie-rekomendacii/
Disallow: dokumenty/plan-meropriiatii-po-protivodeistviiu-korruptsii/formy-blanki/
Disallow: dokumenty/plan-meropriiatii-po-protivodeistviiu-korruptsii/komissiya-po-soblyudeniyu-trebovanij-k-sluzhebnomu-povedeniyu-gosudars/otchety-o-deyatelnosti-komissij-po-soblyudeniyu-trebovanij-k-sluzhebno/
Disallow: dokumenty/plan-meropriiatii-po-protivodeistviiu-korruptsii/komissiya-po-koordinacii-raboty-po-protivodejstviyu-korrupcii-v-lening/
Disallow: dokumenty/plan-meropriiatii-po-protivodeistviiu-korruptsii/antikorrupcionnaya-ekspertiza/
Disallow: o-komitete/vnutrennyaya-struktura/
Disallow: dokumenty/npa47/
Disallow: dokumenty/npa47_antikorr/
Disallow: deiatelnost/plan-meropriiatii-po-protivodeistviiu-korruptsii/antikorrupcionnaya-ekspertiza/
Disallow: deiatelnost/plan-meropriiatii-po-protivodeistviiu-korruptsii/formy-dokumentov-svyazannyh-s-protivodejstviem-korrupcii-dlya-zapolnen/
Disallow: deiatelnost/plan-meropriiatii-po-protivodeistviiu-korruptsii/metodicheskie-materialy/
Disallow: law/npa47/
Disallow: contact/hot_line/oplat/onlajninspekciyarf/
Disallow: about/structure/funkcii-strukturnyh-podrazdelenij/
Disallow: deiatelnost/gosudarstvennye-uslugi/
Disallow: deiatelnost/gosudarstvennyj-uchet/
Disallow: deiatelnost/okn/gike/
Disallow: deiatelnost/okn/obshestvennye-obsuzhdeniya1/
Disallow: deiatelnost/muzejnaya-deyatelnost/podvedomstvennye-uchrezhdeniya3/gosudarstvennoe-byudzhetnoe-uchrezhdenie-kultury-leningrads2/
Disallow: deiatelnost/muzejnaya-deyatelnost/podvedomstvennye-uchrezhdeniya3/22/
Disallow: deiatelnost/muzejnaya-deyatelnost/podvedomstvennye-uchrezhdeniya3/gosudarstvennoe-byudzhetnoe-5skoj-oblasti/
Disallow: deiatelnost/muzejnaya-deyatelnost/podvedomstvennye-uchrezhdeniya3/gosudarstvennoe-byudzhetnoe-uchrezhdenie-kultury-leningradskoj-oblasti/
Disallow: deiatelnost/muzejnaya-deyatelnost/podvedomstvennye-uchrezhdeniya3/34/
Disallow: deiatelnost/muzejnaya-deyatelnost/podvedomstvennye-uchrezhdeniya3/ssti/
Disallow: deiatelnost/muzejnaya-deyatelnost/podvedomstvennye-uchrezhdeniya/
Disallow: deiatelnost/muzejnaya-deyatelnost/muzei-leningradskoj-oblasti11/podvedomstvennye-uchrezhdeniya/
Disallow: deiatelnost/populyarizaciya-naslediya/110/
Disallow: dokumenty/npa47/
Disallow: dokumenty/npa47_antikorr/
Disallow: dokumenty/antikor/antikor-eksp/
Disallow: dokumenty/antikor/metodicheskie-materialy/
Disallow: dokumenty/antikor/form-doks/
Disallow: dokumenty/antikor/komissiya/
Disallow: dokumenty/antikor/obratnaya-svyaz-telefonnaya-liniya-protivodejstvie-korrupcii/
Disallow: obrashcheniia/polls/onlajn-opros-kultura-granty-rossii/
Disallow: kontakty/
Disallow: about/antikor/antikorrupcionnaya-ekspertiza/
Disallow: about/razvitie-konkurencii/
Disallow: law/npa47/
Disallow: law/nezavisimaya-antikorrupcionnaya-ekspertiza/
Disallow: law/npa47_antikorr/
Disallow: dokumenty/npa47/
Disallow: dokumenty/npa47_antikorr/
Disallow: o-komitete/o-protivodejstvii-korrupcii/
Disallow: dokymenty/npa47/
Disallow: dokymenty/npa47_antikorr/
Disallow: o-komitete/npa47_antikorr/
Disallow: deiatelnost/podderzhka-veteranov-svo/mediko-psihologicheskaya-podderzhka-dlya-chlenov-semej-i-uchastnikov-s/
Disallow: deiatelnost/podderzhka-veteranov-svo/obrazovatelnaya-programma-dlya-uchastnikov-svo-biznes-geroev-47/
Disallow: subsidii/
Disallow: dokumenty/npa47/
Disallow: dokumenty/npa47_antikorr/
Disallow: informaciya-po-covid-19/informaciya-o-proizvoditelyah-oborudovaniya-dlya-izgotovleniya-netkann/
Disallow: antikor/npa47_antikorr/
Disallow: doc/npa47/
Disallow: doc/npa47_antikorr/
Disallow: deiatelnost/rezultaty-proverok/informaciya-o-rezultatah-proverok-provedennyh-komitetom/2020-god/regionalnyj-gosudarstvennyj-kontrol-v-sfere-socialnogo-obsluzhiva-iii/
Disallow: pravovaya-baza/prikazy-i-rasporyazheniya-komiteta/regulirovanie-i-kontrol-deyatelnosti-podvedomstvennyh-gosudarstvennyh-/regionalnyj-gosudarstvennyj-kontrol-v-sfere-socialnogo-obsluzhivan-ii/
Disallow: pravovaya-baza/npa47/
Disallow: pravovaya-baza/npa47_antikorr/
Disallow: deiatelnost/fond-zashity-prav-grazhdan-uchastnikov-dolevogo-stroitelstva-leningrad/
Disallow: statistic/npa47/
Disallow: statistic/npa47_antikorr/
Disallow: dokumenty/npa47/
Disallow: dokumenty/opublikovanie-pravovyh-aktov/
Disallow: dokumenty/npa47_antikorr/
Disallow: dokumenty/antikorrupcionnaya-ekspertiza-pravovyh-aktov/dokumenty/
Disallow: programmy-i-plany/protivodejstvie-korrupcii/obratnaya-svyaz-dlya-soobshenij-o-fakte-korrupcii/
Disallow: dokumenty/npa47/
Disallow: dokumenty/npa47_antikorr/
Disallow: obshaya-informaciya/komissii-i-inye-soveshatelnye-organy/leningradskaya-oblastnaya-mezhvedomstvennaya-komissiya-po-ohrane-truda/
Disallow: obshaya-informaciya/komissii-i-inye-soveshatelnye-organy/komissiya-po-soblyudeniyu-trebovanij-k-sluzhebnomu-povedeniyu-gosudars/
Disallow: deiatelnost/professionalnaya-orientaciya/karernoe-konsultirovanie/
Disallow: dokumenty/npa47/
Disallow: dokumenty/npa47_antikorr/
Disallow: about/protcor/normativnye-pravovye-i-inye-akty-v-sfere-protivodejstviya-korrupcii/normativnye-pravovye-i-inye-akty-v-sfere-protivodejstviya-korrupcii/
Disallow: about/protcor/normativnye-pravovye-i-inye-akty-v-sfere-protivodejstviya-korrupcii/zakonodatelstvo-leningradskoj-oblasti-v-sfere-protivodejstviya-korrupc/
Disallow: about/protcor/normativnye-pravovye-i-inye-akty-v-sfere-protivodejstviya-korrupcii/prikazy-apparata-gubernatora-i-pravitelstva-leningradskoj-oblasti-v-sf/
Disallow: about/protcor/metodicheskie-materialy/informacionnye-pisma/
Disallow: about/protcor/metodicheskie-materialy/materialy-kruglogo-stola-10122018-leningradskaya-oblast-protiv-korrupc/
Disallow: about/protcor/metodicheskie-materialy/materialy-seminara-20022019-ispolnenie-gosudarstvennymi-grazhdanskimi-/
Disallow: about/protcor/metodicheskie-materialy/materialy-kruglogo-stola-04042019-deyatelnost-organov-ispolnitelnoj-vl/
Disallow: about/protcor/formy-dokumentov-svyazannyh-s-protivodejstviem-korrupcii-dlya-zapolnen/
Disallow: about/protcor/svedeniya-o-dohodah-rashodah-ob-imushestve-i-obyazatelstvah-imushestve/svedeniya-o-dohodah-rashodah/
Disallow: about/protcor/svedeniya-o-dohodah-rashodah-ob-imushestve-i-obyazatelstvah-imushestve/svedeniya-ob-istochnikah-polucheniya-sredstv/
Disallow: about/protcor/komissiya-po-soblyudeniyu-trebovanij-k-sluzhebnomu-povedeniyu-i-uregul/
Disallow: programm/vserossijskie-konkursy/
Disallow: law/npa47/
Disallow: law/npa47_antikorr/
Disallow: law/plavanie-dlya-vseh-spisok-npa/
Disallow: deyatelnost/stopkorr/anticor-legal-education/
Disallow: law/npa47/
Disallow: law/npa47_antikorr/
Disallow: dokumenty/npa47_antikorr/
Disallow: dokumenty/npa47/
Disallow: pravovaya-baza/npa47/
Disallow: pravovaya-baza/protivodeistvie-korruptsii/npa47_antikorr/
Disallow: programm/statistic1/budget_lo/
Disallow: news/govorim-ob-ispolnenii-byudzheta-po-rashodam/
Disallow: may_orders/
Disallow: about/direction/licen_goszak/alk/
Disallow: about/direction/licen_goszak/met/
Disallow: about/direction/licen_goszak/regionalnyj-gosudarstvennyj-kontrol-nadzor-v-oblasti-roznichnoj-prodaz/
Disallow: about/direction/licen_goszak/federalnyj-gosudarstvennyj-licenzionnyj-kontrol-nadzor-za-deyatelnosty/
Disallow: budget/okaz_uslug/alcohol_license/rpa/application_rpa_1/
Disallow: budget/okaz_uslug/alcohol_license/rpa/zayavlenie-o-pereoformlenie-yuridicheskogo-adresa/
Disallow: budget/okaz_uslug/alcohol_license/rpa/opis-dokumentov/
Disallow: budget/okaz_uslug/alcohol_license/rpo/appl_2/
Disallow: budget/okaz_uslug/alcohol_license/rpo/opis-dokumentov/
Disallow: budget/okaz_uslug/licenzirovanie-zagotovki-hraneniya-pererabotki-i-realizacii-loma-chern/reestr-licenzij/
Disallow: budget/okaz_uslug/reestr-licenzij/
Disallow: budget/okaz_uslug/kontrolnaya-nadzornaya-deyatelnost/
Disallow: budget/test/regionalnyj-gosudarstvennyj-kontrol-nadzor-v-oblasti-roznichnoj-prodaz/markirovka-piva/markirovka-sredstvami-identifikacii/
Disallow: budget/test/federalnyj-gosudarstvennyj-licenzionnyj-kontrol-nadzor-za-deyatelnosty/profilaktika-riskov-prichineniya-vreda-usherba-ohranyaemym-zakonom-cen/obshestvennoe-obsuzhdenie-proekta-programmy-profilaktiki/
Disallow: dokumenty/law/npa47/
Disallow: dokumenty/law/npa47_antikorr/
Disallow: about/antikorr/antikorrupcionnaya-ekspertiza/
Disallow: about/antikorr/metodicheskie-materialy/
Disallow: about/antikorr/formy-dokumentov-svyazannyh-s-protivodejstviem-korrupcii-dlya-zapolnen/
Disallow: about/antikorr/svedeniya-o-dohodah-rashodah-ob-imushestve-i-obyazatelstvah-imushestve/
Disallow: about/antikorr/komissiya-po-soblyudeniyu-trebovanij-k-sluzhebnomu-povedeniyu-i-uregul/otchety-o-deyatelnosti-komissij-po-soblyudeniyu-trebovanij-k-sluzhebno/
Disallow: dokumenty/npa47/
Disallow: dokumenty/npa47_antikorr/
Disallow: progandplan/npa47/
Disallow: progandplan/corrupt/1/otchety-o-deyatelnosti-komissij/
Disallow: progandplan/npa47_antikorr/
Disallow: dokumenty/npa47/
Disallow: dokumenty/npa47_antikorr/
Disallow: deiatelnost/protivodejstvie-korrupcii/metodicheskie-materialy/
Disallow: deiatelnost/protivodejstvie-korrupcii/formy-dokumentov-svyazannyh-s-protivodejstviem-korrupcii-dlya-zapolnen/
Disallow: deiatelnost/protivodejstvie-korrupcii/obratnaya-svyaz-dlya-soobshenij-o-faktah-korrupcii/
Disallow: law/npa47/
Disallow: law/npa47_antikorr/
Disallow: ihtiopatologiya/novosti/razvitie-akvakultury-v-leningradskoj-oblasti/
Disallow: dokumenty/npa47/
Disallow: dokumenty/npa47_antikorr/
Disallow: deiatelnost/protivodeistvie-korruptsii/metodicheskie-materialy/
Disallow: deiatelnost/protivodeistvie-korruptsii/formy-blanki/
Disallow: dokumenty/npa47/
Disallow: dokumenty/npa47_antikorr/
Disallow: deiatelnost/protivodejstvie-korrupcii/svedeniya-o-dohodah/
Disallow: deiatelnost/protivodejstvie-korrupcii/pamyatka-chto-nuzhno-znat-o-korrupcii/
Disallow: deiatelnost/protivodejstvie-korrupcii/metodicheskie-materialy/
Disallow: deiatelnost/protivodejstvie-korrupcii/formy-dokumentov-svyazannyh-s-protivodejstviem-korrupcii-dlya-zapolnen/
Disallow: deiatelnost/protivodejstvie-korrupcii/antikorrupcionnaya-ekspertiza/
Disallow: deiatelnost/protivodejstvie-korrupcii/obratnaya-svyaz-telefonnaya-liniya-protivodejstvie-korrupcii/
Disallow: dokumenty/administrativnye-reglamenty/gosudarstvennye-uslugi/ob-utverzhdenii-administrativnogo-reglamenta-predostavleniya-upravleni/pravovye-osnovaniya-dlya-predostavleniya-uslugi/
Disallow: dokumenty/npa47_antikorr/
Disallow: dokumenty/npa47/
Disallow: dokumenty/antikorrupcionnaya-ekspertiza/
Disallow: dokumenty/oficialnoe-opublikovanie-pravovyh-aktov/
Disallow: oficialnye-meropriyatiya/
Disallow: dokumenty/npa47/
Disallow: dokumenty/npa47_antikorr/
Disallow: deiatelnost/protivodeistvie-korruptsii/plany-protivodejstviya-korrupcii-v-komitete/nezavisimaya-antikorrupcionnaya-ekspertiza/
Disallow: deiatelnost/protivodeistvie-korruptsii/metodicheskie-materialy/
Disallow: deiatelnost/protivodeistvie-korruptsii/formy-dokumentov/
Disallow: deiatelnost/protivodeistvie-korruptsii/antikorrupcionnaya-ekspertiza/
Disallow: deiatelnost/protivodeistvie-korruptsii/obratnaya-svyaz-telefonnaya-liniya-protivodejstvie-korrupcii/
Disallow: deiatelnost/ispolnenie-majskih-ukazov/
Disallow: law/npa47/
Disallow: law/protivodejstvie-korrupcii/antikorrupcionnaya-ekspertiza/proekty-normativnyh-pravovyh-aktov/
Disallow: law/protivodejstvie-korrupcii/metodicheskie-materialy/
Disallow: law/protivodejstvie-korrupcii/formy-blanki/
Disallow: law/protivodejstvie-korrupcii/svedeniya-o-dohodah-rashodah-ob-imushestve-i-obyazatelstvah-imushestve/svedeniya-o-dohodah-rashodah-ob-imushestve-i-obyazatelstvah-imushestve/
Disallow: law/npa47_antikorr/
Disallow: zadat-vopros-vkontakte/
Disallow: dokumenty/npa47/
Disallow: dokumenty/npa47_antikorr/
Disallow: ob-upravlenii/government/otdel-podderzhki-socialnyh-iniciativ/
Disallow: deyatelnost/protivodejstvie-korrupcii/metodicheskie-materialy/
Disallow: deyatelnost/protivodejstvie-korrupcii/formy-dokumentov-svyazannyh-s-protivodejstviem-korrupcii-dlya-zapolnen/
Disallow: deyatelnost/protivodejstvie-korrupcii/svedeniya-o-dohodah-rashodah-ob-imushestve-i-obyazatelstvah-imushestve/
Disallow: deyatelnost/protivodejstvie-korrupcii/obratnaya-svyaz-dlya-soobshenij-o-faktah-korrupcii/
Disallow: informaciya/informaciya-o-poryadke-postupleniya-grazhdan-na-gosudarstvennuyu-grazh/
Disallow: dokumenty/npa47/
Disallow: dokumenty/npa47_antikorr/
Disallow: dokumenty/npa/
Disallow: dokumenty/nezavisimaya-antikorrupcionnaya-ekspertiza/
Disallow: informaciya/protivodejstvie-korrupcii/metodicheskie-materialy/
Disallow: informaciya/protivodejstvie-korrupcii/formy-dokumentov-svyazannyh-s-protivodejstviem-korrupcii-dlya-zapolnen/
Disallow: informaciya/protivodejstvie-korrupcii/svedeniya-o-dohodah-rashodah-ob-imushestve-i-obyazatelstvah-imushestve/
Disallow: informaciya/informaciya-o-kadrovom-obespechenii-v-organah-ispolnitelnoj-vlasti-len/
Disallow: dokumenty/nezavismaya-antikorrupcionnaya-ekspertiza/
Disallow: /admin/
Disallow: /search/

sitemap: https://lenobl.ru/sitemap/