User-agent: PetalBot
Disallow: /
User-agent: Barkrowler
Disallow: /
User-agent: GPTBot
Disallow: /
User-agent: ChatGPT-User
Disallow: /
User-agent: Google-Extended
Disallow: /
User-agent: PerplexityBot
Disallow: /
User-agent: Amazonbot
Disallow: /
User-agent: ClaudeBot
Disallow: /
User-agent: Omgilibot
Disallow: /
User-agent: FacebookBot
Disallow: /
User-agent: Applebot
Disallow: /
User-agent: anthropic-ai
Disallow: /
User-agent: Bytespider
Disallow: /
User-agent: Diffbot
Disallow: /
User-agent: ImagesiftBot
Disallow: /
User-agent: Omgili
Disallow: /
User-agent: YouBot
Disallow: /
User-agent: CCBot
Disallow: /
User-agent: cohere-ai
Disallow: /
User-agent: Twitterbot
Disallow: /
User-agent: AhrefsSiteAudit
Allow: /
User-agent: AhrefsBot
Allow: /
User-agent: *
Disallow: 
Allow: /
Sitemap: https://www.lenouvelliste.ch/sitemap.xml
User-agent: *
Disallow: /api/*
Disallow: /flash-monde/*
Disallow: /flash-suisse/*
Disallow: /flash-sport/*