User-agent: *
Allow: /
Sitemap: https://matrp.ru/sitemap.xml
Disallow: /link?
Disallow: /promo?
Disallow: /promonew?
Disallow: /blogers-blacklist
Disallow: /*?*
Disallow: /*%
Disallow: /index.php
Disallow: /*?page=
Disallow: /*&page=
Disallow: *PHPSESSID=
Disallow: *session_id=