Sitemap: https://maxmodels.pl/sitemap.xml
User-agent: *
Allow: /
Disallow: /?pack=*
Allow: /?pack=0
Allow: /?pack=1
Allow: /?pack=2
Allow: /?pack=3
Allow: /?pack=4
Disallow: */search/*
Disallow: *?filter*
Disallow: *,komentarze.html
Disallow: *,referencje.html
Disallow: /?t=zglos&*
Disallow: /common/loginboxframe*
Disallow: *?nmrd*
Disallow: *referer=*
Disallow: *?fp=*
Disallow: /message/thread/*
Disallow: *?_escaped_fragment_
Disallow: /profile/website/id/*
Disallow: */forum*
Disallow: *?v=*
Disallow: *?fn=*
Disallow: *page_referer=*

Disallow: /ogloszenia*
Disallow: /rejestracja
Disallow: /odzyskaj-haslo
Disallow: *najczesciej-komentowane.html
Disallow: *najwyzej-ocenione.html
Disallow: *najczesciej-ogladane.html
Disallow: *kategoria-*
Disallow: *ranking-zdjec-48h.html
Disallow: */ranking-zdjec-72h.html
Disallow: */ranking-zdjec-tygodnia.html
Disallow: */ranking-zdjec-miesiaca.html
Disallow: */ranking-zdjec-od-poczatku.html
Disallow: *typ-*
Disallow: */ranking-portfolio-48h.html
Disallow: */ranking-portfolio-72h.html
Disallow: */ranking-portfolio-tygodnia.html
Disallow: */ranking-portfolio-miesiaca.html
Disallow: */ranking-portfolio-od-poczatku.html
Disallow: /portfolia-tygodnia/*

User-agent: BLEXBot
Disallow: /
