User-agent: *
Disallow: *?s=*
Disallow: *?sort=*
Disallow: *priceFrom=*
Disallow: */account/*
Disallow: */man+women/*
Disallow: */login*
Disallow: */signup*
Disallow: */terms-of-use*
Disallow: */cart*
Disallow: */checkout/*
Disallow: */index*

Disallow: */utm_source*
Disallow: */utm_medium*
Disallow: */utm_campaign*
Disallow: */utm_content*
Disallow: */utm_term*
Disallow: *gclid=*

Sitemap: https://sitemap.md-fashion.ua/sitemap.xml