User-agent: *
Disallow: /en/
Disallow: /cz/
Disallow: /hu/
Disallow: /sk/
Disallow: /de/
Disallow: /at/
Disallow: /ajax/
Disallow: /gfx/
Disallow: /pdf/
Allow: /gfx/*.jpg$
Allow: /gfx/*.gif$
Allow: /gfx/*.png$
Allow: /gfx/*.jpeg$
Allow: /*.js$
Allow: /*.css$
Sitemap: https://www.merkurymarket.pl/sitemap.xml
Allow: /szablony/merkurymarket/
Allow: /gfx/merkurymarket/_thumbs/
Allow: /*.pdf$
Allow: /*.doc$
Allow: /*.xls$
Allow: /*.rtf$
Allow: /gfx/*.css
User-agent: Fasterfox
Disallow: /
