#ver. 20.08.2024

User-agent: *
Crawl-delay: 5
Disallow: /*&
Disallow: /*=
Allow: /*?v=
Allow: /local/ajax/*=
Disallow: */?
Disallow: /*?ELEMENT_ID=
Allow: /*?PAGEN_1
Allow: */?utm_source=
Disallow: *@
Disallow: *@*?PAGEN_
Disallow: /*?PAGEN*&
Disallow: /*TAB=?PAGEN
Disallow: /*backurl*?PAGEN
Disallow: */allinmap.php
Disallow: *tel:
Disallow: /bitrix/
Allow: /bitrix/*.css
Allow: /bitrix/*.js
Allow: /bitrix/*.xml
Allow: /fonts/*.ttf
Allow: /fonts/*.woff
Disallow: */contacts-new/
Disallow: /upload/
Allow: /upload*iblock/*.pdf$
Allow: /upload*iblock/*.jpg$
Allow: /upload*iblock/*.png$
Allow: /upload*iblock/*.svg$
Allow: /upload*iblock/*.gif$
Allow: /upload*iblock/*.webp$
Allow: /upload/images/
Allow: /upload/menu_files/
Disallow: /guarantee/
Disallow: /examples/my-components/
Disallow: /examples/download/download_private/
Disallow: */auth/
Disallow: */auth.php$
Disallow: /*personal/
Disallow: */search/
Disallow: */slide_show/
Disallow: */index.php$
Disallow: */about/documents/soup.php
Disallow: /*catalogFilter_*
Disallow: */order/
Disallow: */filter/
Disallow: */filter/*/apply/*
Disallow: */filter/*/?PAGEN_1
Disallow: */compare.php
Disallow: /vybrat_dom/?result_test*
Disallow: /shop/registration/
Disallow: /coating/filter/clear/
Disallow: /coating/compare/
Disallow: */black-friday
Disallow: */stalnaya-pyatnitsa
Disallow: /shop/utilities/_test_pbd.php
Disallow: /shop/pokupatelyam/depth/0_4_MC/
Disallow: /shop/informatsiya/natsenka/
Disallow: /postavshchikam-uslug*
Disallow: /calculators/siding-iframe*
Disallow: */sberbank-online/
Disallow: */catalog/*/offer/
Clean-param: items_count&sort&utm_campaign&utm_medium&utm_source&utm_term&ELEMENT_ID&utm_content&PAGEN_1
Sitemap: https://metallprofil.ru/sitemap.xml
User-agent: SMTBot
Disallow: /
User-agent: dotbot
Disallow: /
User-agent: ia_archiver
Disallow: /
User-agent: CamontSpider
Disallow: /
User-agent: cityreview
Disallow: /
User-agent: Baiduspider
Disallow: /
User-agent: Baiduspider-video
Disallow: /
User-agent: Baiduspider-image
Disallow: /
User-agent: ScoutJet
Disallow: /
User-agent: TurnitinBot
Disallow: /
User-agent: ICC-Crawler
Disallow: /
User-agent: plukkie
Disallow: /
User-agent: discobot
Disallow: /
User-agent: NerdByNature.Bot
Disallow: /
User-agent: SindiceBot
Disallow: /
User-agent: Exabot
Disallow: /
User-agent: Aboundexbot
Disallow: /
User-agent: archive.org_bot
Disallow: /
User-agent: Speedy
Disallow: /
User-agent: 008
Disallow: /
User-agent: Linguee
Disallow: /
User-agent: 360Spider
Disallow: /
User-agent: HaoSouSpider
Disallow: /
User-agent: BLEXBot
Disallow: /
User-agent: AhrefsBot
Crawl-delay: 5
User-agent: grapeshot
Disallow: /
User-agent: MegaIndex
Crawl-delay: 5
User-agent: MJ12bot
Disallow: /
User-agent: Riddler (http://riddler.io/about)
Disallow: /
User-agent: Python-urllib/2.6
Disallow: /
User-Agent: DISCo Pump
Disallow: /
User-Agent: Wget
Disallow: /
User-Agent: Teleport Pro
Disallow: /
User-agent: psbot
Disallow: /
User-agent: Twiceler
Disallow: /
User-agent: NetinfoBot
Disallow: /
User-agent: UbiCrawler
Disallow: /
User-agent: DOC
Disallow: /
User-agent: Zao
Disallow: /
User-agent: sitecheck.internetseer.com
Disallow: /
User-agent: Zealbot
Disallow: /
User-agent: MSIECrawler
Disallow: /
User-agent: SiteSnagger
Disallow: /
User-agent: WebStripper
Disallow: /
User-agent: WebCopier
Disallow: /
User-agent: Fetch
Disallow: /
User-agent: Offline Explorer
Disallow: /
User-agent: Teleport
Disallow: /
User-agent: linko
Disallow: /
User-agent: HTTrack
Disallow: /
User-agent: Microsoft.URL.Control
Disallow: /
User-agent: Xenu
Disallow: /
User-agent: larbin
Disallow: /
User-agent: libwww
Disallow: /
User-agent: ZyBORG
Disallow: /
User-agent: Download Ninja
Disallow: /
User-agent: grub-client
Disallow: /
User-agent: NPBot
Disallow: /
User-agent: WebReaper
Disallow: /
User-Agent: YandexAdditional
Disallow: /
User-Agent: PerplexityBot
Disallow: /
User-agent: Google-Extended
Disallow: /
User-agent: GPTBot
Disallow: /
User-agent: ChatGPT-User
Disallow: /
User-agent: CCBot
Disallow: /
User-agent: ChatGenie
Disallow: /
User-agent: Jasper.ai
Disallow: /
User-agent: AnthropicBot
Disallow: /
User-agent: anthropic-ai
Disallow: /
User-agent: Claude
Disallow: /
User-agent: ClaudeBot
Disallow: /
User-agent: Claude-Web
Disallow: /
User-agent: Amazonbot
Disallow: /
User-agent: OmgiliBot
Disallow: /
User-Agent: omgili
Disallow: /
User-agent: cohere-ai
Disallow: /
User-agent: ia_archiver
Disallow: /
