User-agent: *
Disallow: /rss
Disallow: /xml
Disallow: /ifrc
Disallow: /frc/*?*
Disallow: /guestbook/*
Disallow: /flashinformer/*
Disallow: /speech/*
Crawl-delay: 5
Host: https://www.meteonova.ru
sitemap: https://www.meteonova.ru/sitemap_weather.xml
sitemap: https://www.meteonova.ru/sitemap_frc.xml
sitemap: https://www.meteonova.ru/sitemap_pogoda.xml
sitemap: https://www.meteonova.ru/sitemap_month.xml
sitemap: https://www.meteonova.ru/sitemap_med.xml
sitemap: https://www.meteonova.ru/sitemap_pro.xml
sitemap: https://www.meteonova.ru/sitemap_auto.xml
sitemap: https://www.meteonova.ru/sitemap_agro.xml
sitemap: https://www.meteonova.ru/sitemap_avia.xml
sitemap: https://www.meteonova.ru/sitemap_uv.xml
sitemap: https://www.meteonova.ru/sitemap_gm.xml
sitemap: https://www.meteonova.ru/sitemap_hourly.xml
sitemap: https://www.meteonova.ru/sitemap_allergy.xml
sitemap: https://www.meteonova.ru/sitemap_today.xml
sitemap: https://www.meteonova.ru/sitemap_tomorrow.xml
sitemap: https://www.meteonova.ru/sitemap_week.xml
sitemap: https://www.meteonova.ru/sitemap_10.xml
sitemap: https://www.meteonova.ru/sitemap_map.xml
