User-Agent: *
Allow: *video*
Disallow: */img/*
Disallow: */js/*
Disallow: */?$
Disallow: */css/*
Disallow: */bitrix/*
Disallow: *id=*
Disallow: *ID=*
Disallow: *section=*
Disallow: *utm_source=*
Disallow: *lang=*
Disallow: */twitter.com/*
Disallow: *.php
Disallow: */frss/*
Disallow: */en_old/*
Disallow: *showMe=*
Disallow: *password=*
Disallow: *login=*
Disallow: *wpost=*
Disallow: *ctype=*
Disallow: *search*
Disallow: *?q=*
Disallow: *ajax=*
Disallow: */map/
Disallow: /files/
Disallow: *rss.xml
Disallow: /about/newcollateral/
Disallow: /upload/iblock*
Disallow: */backup/*
Disallow: */disclosure/facts/detail/*
Disallow: /*?*
Disallow: */l/*
Disallow: /lk/*
Disallow: /chastnim-licam/karti/virtual-card-mts-dengi*
Disallow: */b/*
Disallow: */pid/*
Disallow: /chastnim-licam/akcii/
Disallow: /malomu-biznesu/sme-krediti-i-garantii/bankovskie-garantii*
Disallow: /a/mtsfinans/
Disallow: /chastnim-licam/vse-servici/mtsdengi-faq/
Disallow: */adapter/*
Disallow: */sign/*
Disallow: */success/*
Disallow: *short*
Disallow: */micron/*
Disallow: */landings/premium/*
Disallow: */landings/private/*
Disallow: */a/premium/*
Disallow: */a/private/*
Disallow: */static/html/*
Disallow: /1/*
Disallow: /2/*
Disallow: */c/*
Disallow: /chastnim-licam/karti/unionpay/
Disallow: */d/*
Disallow: /e/
Disallow: /upload/static/documents/malomu-biznesu/pravila-otkrytiya-i-vedeniya-schetov-dlya-servisa-Nalogovaya-kopilka.pdf
Disallow: /chastnim-licam/private-banking/private-pif/
Disallow: /chastnim-licam/private-banking/trust-management/
Disallow: /chastnim-licam/private-banking/strukturnye-producty/
Disallow: /chastnim-licam/private-banking/private-iis/
Disallow: /malomu-biznesu/events/
Disallow: /upload/static/documents/rasp/vk.pdf
Disallow: /upload/static/documents/rasp/rosneft.pdf
Disallow: /upload/static/documents/rasp/rostelekom.pdf
Disallow: /upload/static/documents/rasp/segezha.pdf
Disallow: /upload/static/documents/rasp/Inter-RAO.pdf
Disallow: /upload/static/documents/rasp/BPIF-tekhnologii-budushchego.pdf
Disallow: /upload/static/documents/rasp/fix-price.pdf
Disallow: /upload/static/documents/rasp/rusal.pdf
Disallow: /upload/static/documents/rasp/MMK.pdf 
Disallow: /upload/static/documents/rasp/seligdar.pdf
Disallow: /factory/vkladi/vklad_dirkhamy/
Disallow: /upload/static/documents/oferty.pdf
Disallow: /chastnim-licam/karti/weekend-svyaznoy/
Disallow: /chastnim-licam/karti/card-mir/
Disallow: /chastnim-licam/karti/credit-mts-smart-dengi/
Disallow: /chastnim-licam/karti/unionpay/
Disallow: /chastnim-licam/karti/mts-dengi-vklad/
Disallow: /chastnim-licam/karti/karta-studenta/
Disallow: /chastnim-licam/karti/virtual-card-mts-dengi/
Disallow: /chastnim-licam/karti/credit-card-detskij-mir/
Disallow: /chastnim-licam/karti/pre-paid-card-detskij-mir/
Disallow: /chastnim-licam/karti/podarok-mts-dengi/
Disallow: /dst/
Disallow: /ipo/
Disallow: *id=*
Disallow: *?categories*
Disallow: *uslovia_obrabotki_xranenia_pd*
Disallow: *uslovia_obrabotki_xranenia_ofd*
Disallow: *CumyTpn7tS*
Disallow: *xid=*
Disallow: /factory/1of3/
Disallow: /upload/static/documents/prilozhenie-5-DKO-MTSB.pdf
Disallow: /upload/static/documents/prilozhenie-8-DKO-MTSB.pdf
Disallow: /upload/static/documents/dopolnitelnoe-soglashenie-k-DBS.pdf
Disallow: /upload/static/documents/soglashenie.pdf
Disallow: /upload/static/documents/dopolnitelnoe-soglashenie-k-DBS-eksport.pdf
Disallow: /upload/static/documents/dopolnitelnoe-soglashenie-k-DBS-import.pdf
Allow: /b/chastnim-licam/premium/premium-package/
Sitemap: https://www.mtsbank.ru/sitemap.xml


User-Agent: Googlebot
Allow: *video*
Allow: */img/*
Allow: */js/*
Allow: */css/*
Allow: */bitrix/*
Allow: *?yclid=*
Disallow: *id=*
Disallow: *ID=*
Disallow: *section=*
Disallow: *utm_source=*
Disallow: *lang=*
Disallow: */twitter.com/*
Disallow: *.php
Disallow: */frss/*
Disallow: */en_old/*
Disallow: *showMe=*
Disallow: *password=*
Disallow: *login=*
Disallow: *wpost=*
Disallow: *ctype=*
Disallow: *search*
Disallow: *?q=*
Disallow: *ajax=*
Disallow: */map/
Disallow: /files/
Disallow: *rss.xml
Disallow: /upload/iblock*
Disallow: */backup/*
Disallow: */disclosure/facts/detail/*
Disallow: /*?*
Disallow: */malomu-biznesu/raschetny-schet-c1/
Disallow: */malomu-biznesu/raschetny-schet-c2/
Disallow: */malomu-biznesu/raschetny-schet-c3/
Disallow: */malomu-biznesu/raschetny-schet-c4/
Disallow: */l/*
Disallow: /lk/*
Disallow: /chastnim-licam/karti/virtual-card-mts-dengi*
Disallow: */pid/*
Disallow: */b/*
Disallow: /chastnim-licam/akcii/
Disallow: /malomu-biznesu/sme-krediti-i-garantii/bankovskie-garantii*
Disallow: /a/mtsfinans/
Disallow: /chastnim-licam/vse-servici/mtsdengi-faq/
Disallow: */adapter/*
Disallow: */sign/*
Disallow: */success/*
Disallow: *short*
Disallow: */micron/*
Disallow: */landings/premium/*
Disallow: */landings/private/*
Disallow: */a/premium/*
Disallow: */a/private/*
Disallow: */static/html/*
Disallow: /1/*
Disallow: /2/*
Disallow: */c/*
Disallow: /chastnim-licam/karti/unionpay/
Disallow: */d/*
Disallow: /e/
Disallow: /upload/static/documents/malomu-biznesu/pravila-otkrytiya-i-vedeniya-schetov-dlya-servisa-Nalogovaya-kopilka.pdf
Disallow: /chastnim-licam/private-banking/private-pif/
Disallow: /chastnim-licam/private-banking/trust-management/
Disallow: /chastnim-licam/private-banking/strukturnye-producty/
Disallow: /chastnim-licam/private-banking/private-iis/
Disallow: /malomu-biznesu/events/
Disallow: /upload/static/documents/rasp/vk.pdf
Disallow: /upload/static/documents/rasp/rosneft.pdf
Disallow: /upload/static/documents/rasp/rostelekom.pdf
Disallow: /upload/static/documents/rasp/segezha.pdf
Disallow: /upload/static/documents/rasp/Inter-RAO.pdf
Disallow: /upload/static/documents/rasp/BPIF-tekhnologii-budushchego.pdf
Disallow: /upload/static/documents/rasp/fix-price.pdf
Disallow: /upload/static/documents/rasp/rusal.pdf
Disallow: /upload/static/documents/rasp/MMK.pdf
Disallow: /upload/static/documents/rasp/seligdar.pdf
Disallow: /factory/vkladi/vklad_dirkhamy/
Disallow: /upload/static/documents/oferty.pdf
Disallow: /chastnim-licam/karti/weekend-svyaznoy/
Disallow: /chastnim-licam/karti/card-mir/
Disallow: /chastnim-licam/karti/credit-mts-smart-dengi/
Disallow: /chastnim-licam/karti/unionpay/
Disallow: /chastnim-licam/karti/mts-dengi-vklad/
Disallow: /chastnim-licam/karti/karta-studenta/
Disallow: /chastnim-licam/karti/virtual-card-mts-dengi/
Disallow: /chastnim-licam/karti/credit-card-detskij-mir/
Disallow: /chastnim-licam/karti/pre-paid-card-detskij-mir/
Disallow: /chastnim-licam/karti/podarok-mts-dengi/
Disallow: /dst/
Disallow: /ipo/
Disallow: *id=*
Disallow: *?categories*
Disallow: *uslovia_obrabotki_xranenia_pd*
Disallow: *uslovia_obrabotki_xranenia_ofd*
Disallow: *CumyTpn7tS*
Disallow: *xid=*
Disallow: /factory/1of3/
Disallow: /upload/static/documents/prilozhenie-5-DKO-MTSB.pdf
Disallow: /upload/static/documents/prilozhenie-8-DKO-MTSB.pdf
Disallow: /upload/static/documents/dopolnitelnoe-soglashenie-k-DBS.pdf
Disallow: /upload/static/documents/soglashenie.pdf
Disallow: /upload/static/documents/dopolnitelnoe-soglashenie-k-DBS-eksport.pdf
Disallow: /upload/static/documents/dopolnitelnoe-soglashenie-k-DBS-import.pdf
Disallow: *?erid*
Allow: /b/chastnim-licam/premium/premium-package/

User-Agent: Yandex
Disallow:*offers*categories*
Disallow: */?$
Disallow: *pricesort=*
Disallow: *?agi-*
Disallow: *=video_private_short*
Allow: *video*
Disallow: */img/*
Disallow: */js/*
Disallow: */css/*
Disallow: */bitrix/*
Disallow: *section=*
Disallow: *lang=*
Disallow: */twitter.com/*
Disallow: *.php
Disallow: */frss/*
Disallow: */en_old/*
Disallow: *showMe=*
Disallow: *password=*
Disallow: *login=*
Disallow: *search*
Disallow: *?q=*
Disallow: *ajax=*
Disallow: */map/
Disallow: /files/
Disallow: *rss.xml
Disallow: /about/newcollateral/
Disallow: /upload/iblock*
Disallow: */backup/*
Disallow: */disclosure/facts/detail/*
Disallow: */l/*
Disallow: /lk/*
Disallow: /chastnim-licam/karti/virtual-card-mts-dengi*
Disallow: */b/*
Disallow: */pid/*
Disallow: /chastnim-licam/akcii/
Disallow: /malomu-biznesu/sme-krediti-i-garantii/bankovskie-garantii*
Disallow: /a/mtsfinans/
Disallow: /chastnim-licam/vse-servici/mtsdengi-faq/
Disallow: */adapter/*
Disallow: */sign/*
Disallow: */success/*
Disallow: *short*
Disallow: */micron/*
Disallow: */landings/premium/*
Disallow: */landings/private/*
Disallow: */a/premium/*
Disallow: */a/private/*
Disallow: */static/html/*
Disallow: /1/*
Disallow: /2/*
Disallow: */c/*
Disallow: /chastnim-licam/karti/unionpay/
Disallow: */d/*
Disallow: /e/
Disallow: /upload/static/documents/malomu-biznesu/pravila-otkrytiya-i-vedeniya-schetov-dlya-servisa-Nalogovaya-kopilka.pdf
Disallow: /chastnim-licam/private-banking/private-pif/
Disallow: /chastnim-licam/private-banking/trust-management/
Disallow: /chastnim-licam/private-banking/strukturnye-producty/
Disallow: /chastnim-licam/private-banking/private-iis/
Disallow: /malomu-biznesu/events/
Disallow: /upload/static/documents/rasp/vk.pdf
Disallow: /upload/static/documents/rasp/rosneft.pdf
Disallow: /upload/static/documents/rasp/rostelekom.pdf
Disallow: /upload/static/documents/rasp/segezha.pdf
Disallow: /upload/static/documents/rasp/Inter-RAO.pdf
Disallow: /upload/static/documents/rasp/BPIF-tekhnologii-budushchego.pdf
Disallow: /upload/static/documents/rasp/fix-price.pdf
Disallow: /upload/static/documents/rasp/rusal.pdf
Disallow: /upload/static/documents/rasp/MMK.pdf 
Disallow: /upload/static/documents/rasp/seligdar.pdf
Disallow: /factory/vkladi/vklad_dirkhamy/
Disallow: /upload/static/documents/oferty.pdf
Disallow: /chastnim-licam/karti/weekend-svyaznoy/
Disallow: /chastnim-licam/karti/card-mir/
Disallow: /chastnim-licam/karti/credit-mts-smart-dengi/
Disallow: /chastnim-licam/karti/unionpay/
Disallow: /chastnim-licam/karti/mts-dengi-vklad/
Disallow: /chastnim-licam/karti/karta-studenta/
Disallow: /chastnim-licam/karti/virtual-card-mts-dengi/
Disallow: /chastnim-licam/karti/credit-card-detskij-mir/
Disallow: /chastnim-licam/karti/pre-paid-card-detskij-mir/
Disallow: /chastnim-licam/karti/podarok-mts-dengi/
Disallow: /dst/
Disallow: /ipo/
Disallow: *utm_campaign*ved*
Disallow: *utm_campaign_*
Disallow: *?categories*
Disallow: *uslovia_obrabotki_xranenia_pd*
Disallow: *uslovia_obrabotki_xranenia_ofd*
Disallow: *CumyTpn7tS*
Disallow: /factory/1of3/
Disallow: /upload/static/documents/prilozhenie-5-DKO-MTSB.pdf
Disallow: /upload/static/documents/prilozhenie-8-DKO-MTSB.pdf
Disallow: /upload/static/documents/dopolnitelnoe-soglashenie-k-DBS.pdf
Disallow: /upload/static/documents/soglashenie.pdf
Disallow: /upload/static/documents/dopolnitelnoe-soglashenie-k-DBS-eksport.pdf
Disallow: /upload/static/documents/dopolnitelnoe-soglashenie-k-DBS-import.pdf
Disallow: *?erid*
Disallow:*?utm*
Allow: /b/chastnim-licam/premium/premium-package/
Clean-param: utm_source&utm_medium&utm_campaign&partners&utm_content&clickid&wgid&erid&advert&hs&product&type&wpost&ctype&referrer&tab&scroll
Clean-param: 1M_refin_anketa&5_globalmedia&action&advert&amp&amp;erid&appmetrica_tracking_id%&bankovskie_produkty&calc&campaignName&cardForm&cardFormBlockId&cashback_referal&cpa&creditForm&credit-loy-al&dbo&debet_cashback_mir&debet_mts_card&debet_weekend&debetUpridForm&defPaySystem&desktop-maps&doma-i-kottedzhi
Clean-param: dvizhymoe-imusch-estvo&ecom&ecomkp&faq&fin_uslugi&finAdvice&free_summer&from&home_page&inhouse&investicii&ipoteka&ipoteka_s_gos&ipoteka-s-gospodderjkoyipoteka-s-gospodderjkoy&kommercheskaya-nedvizhimost&kredfinans2020&kredit0rub&kvartiry-i-komnaty&magnitForm&mastercard-bookingcom&maximedia&media&menu_sait&metro&mgmcc&mir
Clean-param: mortgageArti-cles&mts_cashback&mts_ru&mtscashback&mtsru&ncpk&NY_vklad&odnoklassniki&offerId&partner&platform_id&primamedia&pr&prinupd&raschetny-schet&ref&refin&smart&smm&smm_post&social&tab&tg&transaction_id&tw&utm&utm_analiti-ka&utm_campaign_%20MTS%C2%AC_CASHBACK_Digital_Mir%C2%AC%C2%AC_novosib&utm_campaign_LoungeKey_Mastercard_BO
Clean-param: utm_campaign_mir_mts_cashback_lite_novosib&utm_campaign_mtsbank_vklad_osnovatelnyi&utm_campaign_perevody_ip_Novosib&utm_campaign_perevody_ip_Primamedia&utm_campaign_perevody_ip_Rostovgazeta
Clean-param: utm_campaign_perevody_ip_Ufa&utm_campaign_vklad_bery-vishe_Stav&utm_campaign_prodlenie_do_31_marta_Novosib&vc.ru
Clean-param: VED&video_private_short&virtualImgInfoBlock&vk.com&vk-ads&vkontakte&weekend&weekend_k&wownetwork&wownetwork_Bankiros&wownetwork_CPAhub&wownetwork_Dalead.pro&wownetwork_Gdeslon
Clean-param: wownet-work_GetBlogger&wownetwork_Guruleads&wownetwork_Leadssu&wownetwork_Liknot&wownet-work_MasterTarget&wownetwork_pampadu&wownetwork_Rafinad&wownetwork_Workle&yandex_source&yandex_zapravki
Clean-param: yasam&YT&zemelnye-uchastki-lph&zero&zhilaya-nedvizhimost&utm_campaign_rating_vbr_june_2021&to
Clean-param: utm_leads&yandex-source&utm_campaign_rating_vbr_2020&click_id&utm_campaign_millionair&%20utm_sour-ce&utm_campaign_perevody_ip_sovainfo&utm_campaign_perevody_ip_%D1%8A_privolgie&utm_campaign_perevody_ip_%D1%8A_privolgie&utm_campaign_perevody_ip_dk&utm_campaign_perevody_ip_ura&utm_term&utm_source&rel&_ga&_liknot_sid&etext
Clean-param: part-ner_sale&a_id&page&category&pricesort&js_days&js_summ&js_currency&code&dop_id&tagtag_uid&utm_campaign_tass&u&cardtype&darim_mln&cfidsmts-w-sso&groupid&categories[0]&amp;utm_medium&lang&ysclid&amp;utm_campaign&salesid&amp;utm_term&trk&amp;utm_content&section
Clean-param: _currency&_lang&_ym_debug&adrclid&af_js_web&af_ss_ui&af_ss_ver&allowprocessingcondi-tions&amp;utm_source&appl_id&b24form_user&baobab_event_id&c&cam_id&categories[1]&channel&clckid&click_text&click_url&companyinn&dclid
Clean-param: disableglobalinfocol-lect&ea&ec&el&email&erir&error&error_description&excustid&externalapp&fbclid&fl_checkpoint&flagallowpassbki&flagallowreceiveinfofrombank&flagessentialconditions&flagsmsaccepted&form_fa&forward_var
Clean-param: frm&fromapp&geo_region&hashphone&hit_id&hl&icookie&isdelivery&issuer&miniapp&mort-gage_uid&msguid&mtm_wid&mtsrequestid&mymts_brws&name&page_hostname&page_path&page_start&page_type&phone&phonenumber&pid&platform&pr_cat
Clean-param: pr_sku&productkey&producttype&rb_clickid&region&requestid&secret&ship_avalaible&source&src_pof&state&sum&target&tclick&term&theme&timestamp&utm_campaing&utm_expid&utm_mefium
Clean-param: utm_referrer&utm_source&utm_source_service&vc_mts_client&web&wprid&yandex_user_id&yandexuid&sid&apid&roughly&shortform&rate&clientfio&birthdate&city&fullname&tgwebappplatform&tgwebappversion&tgwebappthemeparams 
Clean-param: aff_sub1&cmd&st.cmd&st.canonicalUrl&st.hosterId&st._aid&st.shareUrl&st.hoster&subcatego-ry&yadclid&yadordid&yclid&UTM_MEDIUM_TXT&UTM_CAMPAIGN_TXT&fromApp&externalApp&cardType&groupId&allowProcessingConditions&mtsRequestId&productType&hashPhone&requestId&JS_SUMM&JS_CURRENCY&JS_DAYS&utm_id
Clean-param: exCus-tId&isDelivery&productKey&companyINN&disableGlobalInfoCollect&msgUID&amp;partners&amp;clickid&apId&sId&ext-uniq-id&_source_stat_&phoneNumber&birthDate&ID&sku&price&pfr_is_agreed&clientFio&flagEssentialConditions&flagSMSAccepted&flagAllowReceiveInfoFromBank&uid
Clean-param: aff_sub&gtm_debug&rrcid&marketing-parameters&ypppel&click&sub_id_1&tn&cardid
Clean-param: tl&sa&sa2&client_id&tid&token&ad&wbraid&term&sId&ym_tracking_id&text&constructor[prototype][a42e5579]&ved&yun3a0n2yi&s2
Clean-param: utm_referrer&fbjoue2jij&hvwcpgtasv&dmbugnmaqh&u4ccos5bpp&vxr1m23fck&bewy562g1x&%20utm_source&campaigName&utm%20source&_gl&yprqee&tgWebAppThemeParams&id&xid
Clean-param: content&utm_referrer&Center&frm&amp;referrer&Chain&amp;fl_checkpoint&tracking_url&utm_token&utm_sourse&consentAdvertising&roduct&surname&middlename&birthday&amp;yclid&consentPolicy&allowReceiveInfoFromBank
Clean-param: filter[offices]&aff_sub1&aff_sub3&aff_sub2&partner_sale&utm_analitika&utm_leads&services[]
Clean-param: ab_redir&websub3&websub5&s_trk&subid&utmsource&content&amp;yandex_source&amp;ysclid&id_token&amp;tid&subid1&subid3&campaignname&yadiscount&productid&redit-holidays&subject&back&errorcode&body&9pdzbris00uo5k3wc35u-&errormessage&af_click_lookback&buttonhidden&is_retargeting&description&af_adset&agreement
Clean-param: m-message-key-id&m-message-click-id&referer&felosearch_translate&media-test-tag&sub1&utmmedium&utmcampaign&oid&amp;defpaysystem&amp;wgid&amp;oid&cn&pl&reserved&data&changeTab&rowan_msg_id&rowan_id1&tracelog&ck&frompartners
Clean-param: cms_offer_id&landing&amp;transaction_id&activetab&ctime&startdate&t7&t8&order&form&app_lang&amp;sum&t6&enddate
Clean-param: ab_redir&cms_offer_id&fact_city&fact_fias&fact_settlement&fact_ship_option_1st_date&fact_ship_option_intervals&fact_ship_option_last_date&pr_sku&prodCode&reg_city&reg_fias&reg_settlement&ship_select_city&ship_select_date&ship_select_interval&ship_select_method&work_city&work_fias&work_settlement&work_ship_option_1st_date&work_ship_option_intervals&work_ship_option_last_date
Clean-param: CODE&exCustId&managerName&fullName&inn&HashPhone&webSub3&webSub5&s6&channelId&creditSum&creditPeriod&currency&period&unique_param&location&start-page&provided-visitor&tgclid&v&bid&queryparam1&colourscheme&route&smsagreeflag&personaldataconfirmation&show_loading&push_animated&peer_id&maxprice&k50id&credit_limit&par1&amp;is_channel&webview_progress_bar&minprice&par2&free_days&contactphone&maxamount&maxperiod&af_ip&ybaip&af_model&af_lang&af_ua&af_os_version
Clean-param: fathername&__proto__[1111]&sweho&ahr0chm6ly9tdhniyw5rlnj1l3cvcglsnw&spm&swecmd&passportnumberwithserial&equipment&test&clid&platform&family&swecm