User-agent: *

Disallow: /auth/*
Disallow: *nosign=*
Disallow: *persons?page=*
Disallow: *news_page=*
Disallow: *period=*
Disallow: *is_trusted=*
Disallow: *t=images*
Disallow: *t=videos*
Disallow: */article/media*
Disallow: *network=*
Disallow: *country=*
Disallow: *use_recommendations=*
Disallow: */news/sources/?page=*
Disallow: *first_news_id=*
Disallow: /v1/*
Disallow: /api/v2/*
Disallow: /preview/*

Sitemap: https://my.ua/sitemap.xml
Host: my.ua
