User-agent: *
Allow: /

sitemap: https://www.myastro.gr/sitemap.xml
sitemap: https://www.myastro.gr/sitemap-horoscope_daily.xml
sitemap: https://www.myastro.gr/sitemap-horoscope_weekly.xml
sitemap: https://www.myastro.gr/sitemap-horoscope_monthly.xml
sitemap: https://www.myastro.gr/sitemap-horoscope_annually.xml
sitemap: https://www.myastro.gr/sitemap-horoscope_hourly.xml
sitemap: https://www.myastro.gr/sitemap-zwdia.xml
sitemap: https://www.myastro.gr/sitemap-astrologia.xml
sitemap: https://www.myastro.gr/sitemap-oneirokritis.xml
sitemap: https://www.myastro.gr/sitemap-tarw.xml
sitemap: https://www.myastro.gr/sitemap-astrologoi.xml
sitemap: https://www.myastro.gr/sitemap-dimofili.xml
sitemap: https://www.myastro.gr/sitemap-images.xml


