User-agent: *
Disallow: /usuarios/
Disallow: /club/
Disallow: /comunes/
Disallow: /login.html
Disallow: /buscador
Disallow: /suscripciones/
Disallow: /boletin/
Disallow: /fotografia/hemeroteca-de-foto-del-dia
Disallow: /*/{{link}}$
Disallow: /*/{{url}}$
Disallow: /articulo.aspx
Disallow: /feeds

User-agent: GPTBot
Disallow: /
User-agent: CCBot
Disallow: /
User-agent: Amazonbot
Disallow: /
User-agent: ChatGPT-User
Disallow: /
User-agent: OAI-SearchBot
Disallow: /
User-agent: Bytespider
Disallow: /
User-agent: ClaudeBot
Disallow: /
User-agent: Perplexity-User
Disallow: /
User-agent: PerplexityBot
Disallow: /
User-agent: Claude-SearchBot
Disallow: /
