User-agent: george
Disallow: /web/file/
Disallow: /Particulier/Verzekeren/Opzeghulp/
Disallow: /Particulier.htm
Disallow: /robots.txt.htm
Disallow: /Emailform.htm*
Disallow: /*showlightbox*
Disallow: /bq-leven-mutaties/
User-agent: Googlebot
Disallow: /Sitemap-pages.htm
User-agent: bingbot
Disallow: /Sitemap-pages.htm
User-agent: DuckDuckBot
Disallow: /Sitemap-pages.htm
User-agent: Slurp
Disallow: /Sitemap-pages.htm
User-agent: GPTBot
Allow: /
User-agent: ChatGPT-User
Allow: /
User-agent: OAI-SearchBot
Allow: /
User-agent: *
Disallow: /*view=ajax* 
Disallow: /Glossary/ 
Disallow: /Videos/ 
Disallow: /Emailform.htm*
Disallow: /*showlightbox*
Sitemap: https://www.nn.nl/sitemappages.xml.gz
Sitemap: https://www.nn.nl/sitemaparticle.xml.gz