User-agent: *
Disallow: /wp-admin/
Disallow: /wp/
Disallow: /wp-content/
Disallow: /?
Disallow: *?s=
Disallow: *&s=
Disallow: /search
Disallow: */xmlrpc.php
Disallow: *utm*=
Allow: */wp-*/*.js
Allow: */wp-*/*.css
Allow: */wp-*/*.png
Allow: */wp-*/*.jpg
Allow: */wp-*/*.jpeg
Allow: */wp-*/*.gif
Allow: */wp-*/*.svg
Allow: */wp-*/*.webp
#Allow: */wp-*/*.pdf
Allow: */wp-*/*ajax*.php


Sitemap: https://novapay.ua/sitemap_index.xml