User-agent: *
Allow: *
Disallow: /notepads
Disallow: /abuses
Disallow: /api
Disallow: /redirect
Disallow: /call-access-new
Disallow: /password-edit
Disallow: /confirmation
Disallow: /payment_methods
Disallow: /payment_plans
Disallow: /payment_statuses
Disallow: /agents
Disallow: /cabinet
Disallow: /estate
Disallow: /*?
Disallow: /?
Host: https://olan.ru
Sitemap: https://olan.ru/xml/sitemap.xml
