# sitecode:olxpl-desktop
Host: https://www.olx.pl 
Sitemap: https://www.olx.pl/sitemap.xml
User-agent: *
Disallow: */ajax/
Disallow: /adminpanel/
Disallow: /api/
Disallow: */facebook/
Disallow: */rss/
Disallow: */konto/
Disallow: */mojolx/
Disallow: /drukuj/
Disallow: /oferta/ulotka/
Disallow: /oferta/kontakt/
Disallow: /platnosci/
Disallow: /searchform/
Disallow: /nowe-ogloszenie/confirm/
Disallow: /nowe-ogloszenie/confirmpage/
Disallow: /i2/oferta/abuse/
Disallow: /m/oferta/abuse/
Disallow: /i2/oferta/kontakt/*
Disallow: /api/open/oauth/token/
Disallow: */i2/*
Allow: /api/v1/offers/
Allow: /api/v1/targeting/
Allow: /api/v1/friendly-links/
Allow: /
