User-agent: *
Disallow: /livewire/
Disallow: /storage/debugbar/
Disallow: /storage/framework/
Disallow: /storage/logs/
Disallow: /storage/app/public/content/
Allow: /storage/app/public/media/

User-agent: Twitterbot
Disallow: /storage/debugbar/
Disallow: /storage/framework/
Disallow: /storage/logs/
Disallow: /storage/app/public/content/
Allow: /storage/app/public/media/

Sitemap: https://onclinic.ua/sitemap.xml
Sitemap: https://onclinic.ua/sitemap-video.xml