# robots.txt automatically generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/robotstxt.html
User-agent: AdsBot-Google
Allow: /

User-agent: *
Allow: /modules/lgsitemaps/
Disallow: /*?utm_source=facebook.com
Disallow: /*?utm_source=tradedoubler
Disallow: /*?utm_source=salesmanago
Disallow: /*?utm_source=instagram.com
Disallow: /*?smclient=
Disallow: /*fbclid=*&page=
Disallow: /*gclid=*&page=
Disallow: */module/inpostizi/*

# Private pages
Disallow: /*?order=
Disallow: /*?tag=
Disallow: /*?id_currency=
Disallow: /*?search_query=
Disallow: /*?back=
Disallow: /*?n=
Disallow: /*&order=
Disallow: /*&tag=
Disallow: /*&id_currency=
Disallow: /*&search_query=
Disallow: /*&back=
Disallow: /*&n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
Disallow: /*?q=
Disallow: /*?kolor=
Disallow: /*?cena=
Disallow: /*?rozmiar=

# Directories for pakuten
Disallow: /app/
Disallow: /cache/
Disallow: /classes/
Disallow: /config/
Disallow: /controllers/
Disallow: /download/
Disallow: /js/
Disallow: /localization/
Disallow: /log/
Disallow: /mails/
Disallow: /modules/
Disallow: /override/
Disallow: /pdf/
Disallow: /src/
Disallow: /tools/
Disallow: /translations/
Disallow: /upload/
Disallow: /var/
Disallow: /vendor/
Disallow: /webservice/

#Disallow: /*?p=
#Disallow: /*?smclient=
#Disallow: /*?fbclid=
#Disallow: /*?%
#Disallow: */blog/*/feed/*

#Disallow: /*?utm_source
#Disallow: /*?utm_medium
#Disallow: /*?utm_campaign

# Files
Disallow: /adres
Disallow: /adresy
Disallow: /logowanie
Disallow: /koszyk
Disallow: /rabaty
Disallow: /sledzenie-zamowien-gosci
Disallow: /historia-zamowien
Disallow: /dane-osobiste
Disallow: /moje-konto
Disallow: /zamowienie
Disallow: /potwierdzenie-zamowienia
Disallow: /sledzenie-zamowienia
Disallow: /potwierdzenie-zwrotu
Disallow: /odzyskiwanie-hasla
Disallow: /szukaj
# Sitemap
Sitemap: https://pakuten.pl/sitemap.xml

User-agent: Storebot-Google
Allow: /

User-agent: AdsBot-Google-Mobile
Allow: /

User-agent: FacebookBot
Allow: /
Allow: /*fbclid=
Allow: /*?utm_source=facebook.com
Allow: /*?utm_source=instagram.com

User-agent: Pinterest/0.2 (+https://www.pinterest.com/bot.html)
Allow: /

User-agent: Pinterestbot/1.0
Allow: /
