User-agent: *
Allow: /doc/
Allow: /info/
Allow: /backoffice/static/img/
Allow: /$
Allow: /welcome.htm
Disallow: /*.pdf
Disallow: /*.rtf

Sitemap: https://payanyway.ru/info/w/ru/public/sitemap.xml

Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /

Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /backoffice/auth/support
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /backoffice/auth/register
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/public/w/partnership/developers/instructions/shopscript.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/sbp.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/en/public/w/partnership/developers/instructions/netcat_47.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/magento.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /backoffice/auth/signin
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/en/public/w/partnership/developers/instructions/joomla_virtuemart3.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/en/public/w/partnership/developers/instructions/oscommerce3.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/en/public/w/about.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/en/public/w/partnership/howto/terms.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/cms.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/en/public/w/payment-methods/index.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/assistant.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/en/public/w/partnership/faq.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/en/public/w/partnership/howto/index.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/en/public/w/customers/check.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /news.htm
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /viewNews.htm
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/5cms.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/webcanape.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/crmbitrix24.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/cartenergy.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/dle.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/dle_kylshop.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/kylaksizov.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/fastsales.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/hostcms.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/instantcms.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/joomla4_virtuemart4.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/joomla_virtuemart3.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/joomla_joomshopping419.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/joomla_j2store3211.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/joomla_membership.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/joomla_rsmembership.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/joomla_eventsbooking.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/joomla_joomlakassa3413.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/joomla_hikashop.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/joomla_simplecaddy30.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/joomla_donation.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/joomla_ijoomlaadagency.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/modx_evolution.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/modx_revolution.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/modx_rev_minishop.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/moysklad.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/getcourse.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/okaycms.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/onlinemerchant2.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/oscommerce3.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/oscommerce2.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/phpshop.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/readyscript.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/shopcms.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/simpla.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/simpla_2.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/simpla_14.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/tamaranga.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/vamshop_2.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/vamshop.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/wix.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/zencart.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/adobemuse.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/bitrix.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/advantshop.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/cscartrus.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/cscart4.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/cscart3.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/drupal8_ubercart4.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/drupal7_ubercart3.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/drupal_ubercart.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/drupal_ecommerce.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/drupal_commerce.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/drupal_8_commerce_2.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/goorucms.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/imagecms49.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/ispring.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/joomla_virtuemart2.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/joomla_virtuemart.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/joomla_simplecaddy.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/joomla_joomshopping3.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/megagroup.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/netcat_54.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/netcat_5.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/netcat_47.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/netcat_45.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/ocstore23.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/ocstore24.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/opencart4.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/opencart3.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/opencart23.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/opencart2.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/opencartfk.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/paraplan.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/prestashop17.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/prestashop.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/prestashop15.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/prestashop13.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/school-master.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/shoprent.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/skadate.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/vicms.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/woocommerce.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/dopbsp.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/freelancemarketplacetheme.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/eautopay.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/adobebc.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/bitrixstandart.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/bmshop.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/amirocms.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/diafancms.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/ecwid.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/heeg.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/imperacms.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/landingi.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/magento2.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/merchium.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/moodle.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/nopcommerce.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/opentao.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/payplugin.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/retailcrm.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/shop2you.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/shopscript5.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/shopscript.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/shopscript_legoedition.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/storeland.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/umicms.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/whmcs.html
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&utm_term /info/w/ru/public/w/partnership/developers/instructions/xcart.html