User-agent: *
Disallow: /
Disallow: *clk?*
Disallow: *clk/*
Disallow: /clk
Disallow: /ot-amp-consent

Disallow: *?*sort=*
Disallow: *?*priceMin=*
Disallow: *?*priceMax=*
Disallow: *?*page=*
Disallow: *?*q=*
Disallow: *?*dekolty=*
Disallow: *?*dlakogo=*
Disallow: *?*dodatki=*
Disallow: *?*dostepnosci=*
Disallow: *?*duze-rozmiary=*
Disallow: *?*dlugosc=*
Disallow: *?*dlugosci-nogawek=*
Disallow: *?*dlugosci-rekawow=*
Disallow: *?*dlugosci-sukienek-i-spodnic=*
Disallow: *?*eco=*
Disallow: *?*fasony=*
Disallow: *?*kategorie=*
Disallow: *?*kolory=*
Disallow: *?*marki=*
Disallow: *?*materialy=*
Disallow: *?*mechanizmy-zegarkow=*
Disallow: *?*miseczki=*
Disallow: *?*modele=*
Disallow: *?*modele-okularow=*
Disallow: *?*motywy-wzory=*
Disallow: *?*obwody-pod-biustem=*
Disallow: *?*okazje=*
Disallow: *?*podeszwy=*
Disallow: *?*pory-roku=*
Disallow: *?*rodzaje-materialow=*
Disallow: *?*rodzaje-noskow=*
Disallow: *?*rozmiary=*
Disallow: *?*rozmiary-butow=*
Disallow: *?*rozmiary-garniturow=*
Disallow: *?*rozmiary-kolnierzykow=*
Disallow: *?*rozmiary-marynarek=*
Disallow: *?*rozmiary-rajtop=*
Disallow: *?*sekcje=*
Disallow: *?*sklepy=*
Disallow: *?*sport=*
Disallow: *?*style=*
Disallow: *?*sylwetki=*
Disallow: *?*szerokosci-w-pasie=*
Disallow: *?*typy-torebek=*
Disallow: *?*typy-zapiec-zegarkow=*
Disallow: *?*wielkosc=*
Disallow: *?*wyprzedaz=*
Disallow: *?*wysokosci-cholewek=*
Disallow: *?*wysokosci-stanu=*
Disallow: *?*zapiecia=*

User-agent: facebookexternalhit
Disallow: /

User-agent: FacebookBot
Disallow: /
