User-agent: *
Disallow: /cgi-bin/
Disallow: /*action=*
Disallow: *shopping_cart.html*
Disallow: *=wishlist*
Disallow: *=checkout*
Disallow: *=my_points*
Disallow: *=bank_tokens*
Disallow: *=account_history*
Disallow: *=logoff*
Disallow: *disp_order=*
Disallow: *wp-login*
Disallow: /get_reviews_amp.php
Disallow: /get_questions_amp.php
Disallow: /get_answers_amp.php
Disallow: /save_sp_events.php
Disallow: /banners_statistics.php
Disallow: /check_youtube_video_thumb.php
Disallow: /async_scripts.php
Disallow: /dpu_ajax.php
Disallow: /cdn-cgi/rum
Disallow: /cdn-cgi/
Disallow: /ads.txt
Disallow: /wp-admin/
Disallow: /wp-content/plugins/
Allow: /wp-admin/admin-ajax.php
Allow: /wp-content/uploads/

User-agent: Alexabot
Disallow:/*popup_image&pID*

Sitemap: https://www.pharm24.gr/sitemap.xml
Sitemap: https://www.pharm24.gr/blog/sitemap-news.xml