User-agent: *
Disallow: /cgi-bin/
Disallow: /wp-admin/
Disallow: /index.php
Disallow: /xmlrpc.php
Disallow: /comments/feed/
Disallow: /archives/
Disallow: /preview/
Disallow: /search

User-agent: Mediapartners-Google*
Allow: /

User-agent: Googlebot-Image

Allow: /wp-content/uploads/

User-agent: Googlebot-Mobile
Allow: /

User-agent: Adsbot-Google
Allow: /

Sitemap: https://www.pickandroll.gr/sitemap.xml