User-agent: *
Disallow: /szukaj/*
Disallow: /*zglos-naruszenie.html
Disallow: /*odpowiedz.html
Disallow: /*komentuj.html
Disallow: /*dodaj-watek.html
Disallow: /*watek-odpowiedz.html
Disallow: /*odpowiedz-cytuj.html
Disallow: /*td-naruszenie-zasad.html
Disallow: /paywall/*
Disallow: /?ajax=1&page=*
Disallow: /*?ajax=1&page=*
Disallow: /*?ress=mobile&ajax=*
Disallow: /widget-liveblog-story-results.html*
Disallow: /partials/*
Disallow: /user-session-proxy/*
Disallow: /subskrypcja?
Disallow: /*?utm_aureus=*
Disallow: /__acc/
Disallow: /_cdf/
Disallow: /_variant/
Disallow: /a8f4d8cd95e164917035b64b867a45dd