User-agent: *
Disallow: /after-apply/
Disallow: /business-evaluation/
Disallow: /employee/
Disallow: /employer/
Disallow: /job-alert/
Disallow: /message/
Disallow: /employer-panel/
Disallow: /employee-panel/
Disallow: /web-push/
Disallow: /ocen-kandydatow/
Disallow: /localization/
Disallow: /rekomendowane-oferty/
Disallow: /api/
Disallow: /applying/
Disallow: /apply/
Disallow: /dictionary/
Disallow: /countofferts.js
Disallow: /kandydat/
Disallow: /panel-powiadomien.html
Disallow: /firma/platnosci.html
