User-agent: *
Disallow: /*.pdf$
Disallow: /*.wmv$
Disallow: /*.flv$
Disallow: /*.mpg$
Disallow: /*.avi$
Disallow: /*.inl$
Disallow: /*.doc$
Disallow: /*.xls$
Disallow: /Drukuj/
Disallow: /fb_comment_id=
Disallow: /paywall/*
Disallow: /user-session-proxy/*
Disallow: /njYjD8BNiL/*
Disallow: /__acc/
Disallow: /_cdf/
Disallow: /_variant/
Disallow: /a8f4d8cd95e164917035b64b867a45dd