User-agent: *
Allow: /img/favicon/favicon-96x96.png
Allow: /img/favicon/favicon_96x96.ico
Allow: /img/favicon
Disallow: /img
Disallow: /img/ext
Disallow: /img/main
Disallow: /img/text
Disallow: /img/quiz
Disallow: /img/avatar
Disallow: /img/bistock
Disallow: /app/webroot/img
Disallow: /app/webroot/img/ext
Disallow: /app/webroot/img/main
Disallow: /app/webroot/img/text
Disallow: /app/webroot/img/quiz
Disallow: /app/webroot/img/avatar
Disallow: /app/webroot/img/bigstock
Disallow: /app/webroot/pdf
Disallow: /widget
Disallow: /quiz_test