# robots.txt for https://racingnews365.nl
# Note: This file is automatically generated by Seofy

User-agent: facebookexternalhit
Allow: /

User-agent: *
Allow: /
Disallow: /cpresources/
Disallow: api-simple/
Disallow: narrowcasting/

Sitemap: https://racingnews365.nl/sitemap.xml
User-agent: facebookexternalhit
Allow: /