Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-21.xml.gz
Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-20.xml.gz
Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-19.xml.gz
Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-18.xml.gz
Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-17.xml.gz
Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-16.xml.gz
Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-15.xml.gz
Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-14.xml.gz
Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-13.xml.gz
Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-12.xml.gz
Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-11.xml.gz
Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-10.xml.gz
Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-9.xml.gz
Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-8.xml.gz
Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-7.xml.gz
Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-6.xml.gz
Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-5.xml.gz
Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-4.xml.gz
Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-3.xml.gz
Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-2.xml.gz
Sitemap: https://www.rmf24.pl/sitemap/www.rmf24.pl-siteindex-1.xml.gz
User-agent: *
Disallow: */podglad-wydruku,*
Disallow: *?from=mobile
Disallow: *,nPack,1
Disallow: *,av,1,twitter,1*
Disallow: /szukaj/
Disallow: /szukaj,
Disallow: /wyszukaj/
Disallow: /wyszukaj,
Disallow: /embed-video?
Disallow: /ajax
Disallow: /przeslij-link*
Disallow: /zglos-naduzycie/*
Disallow: /ajax/zglos-naduzycie/*
Disallow: /komentarze/odpowiedz/formularz
Disallow: /komentarze/odpowiedz/wyslij
Disallow: /udostepnij-komentarz
Disallow: /key=*
Disallow: /script
Disallow: /y=*
Disallow: /ad.js*
Disallow: /ocen,*
Disallow: *,th,*
Disallow: *,addCForm,*
Disallow: *,s,*
Disallow: /getVideoInfo
Disallow: /embed-video
Disallow: /logowanie
Disallow: /rejestracja
Disallow: */ankieta
Disallow: */wyniki-ankiety-
Disallow: /pokaz-komentarz,pId,%POST%*
Disallow: /forum/post,pId,%POST_ID%*
Disallow: /newsamp2-
Disallow: /wpisamp2-
Disallow: /przepisamp2-
Disallow: /gwiazdaamp2-
Disallow: /zdjecieamp2
Disallow: /videoamp2
Disallow: /*?*parametr=*
Disallow: /*?*f=*
Disallow: /adc
Disallow: /emotions-api
Disallow: /*spamId=
Disallow: /*,spamId,
Disallow: /*repId=
Disallow: /*,repId,
Disallow: /*sSort=
Disallow: /*,sSort,
Disallow: */api*related-elements/*
Disallow: *,tType,*
Disallow: /?ap*
Disallow: /?la*
Disallow: *?app*
Disallow: *?av=1
Disallow: *,via,*
Disallow: *?utm_source*
Disallow: *?ad

User-agent: Mediapartners-Google
Allow: /

