User-agent: *
Disallow: /portal
Disallow: /wp-admin
Disallow: /author/
Disallow: /wp-includes
Disallow: /wp-content/plugins
Disallow: /wp-content/cache
Disallow: /wp-json/
Disallow: /xmlrpc.php
Disallow: /readme.html
Disallow: /*?
Disallow: /?s=
Disallow: */page/
Disallow: /tags/
Disallow: /private-course/*
Allow: /*.css
Allow: /*.js
Allow: /wp-admin/admin-ajax.php
Allow: /apple-app-site-association
Sitemap: https://rsv.ru/sitemap.xml
