User-agent: *
Disallow: /cgi-bin
Disallow: /wp-admin/
Disallow: /?
Disallow: *?s=
Disallow: *&s=
Disallow: /search
Disallow: /author/
Disallow: */embed$
Disallow: */xmlrpc.php
Disallow: /*?utm=
Disallow: *openstat=
Disallow: /eula
Disallow: /consent-dp

Disallow: /news/
Disallow: /platformy-smartfon/
Disallow: /static/help/html/admin.html
Disallow: /static/help/html/changelog.html
Disallow: /static/help/html/linux.html
Disallow: /reglament/
Disallow: /registracziya/
Disallow: /support-ticket/
Disallow: /docs/stable2.6/install.html
Disallow: /preimushhestva-vse-platformy/
Disallow: /repos/standalone/
Disallow: /resheniya-po-sfere-otvetstvennosti-chastnyj-polzovatel/
Disallow: /sravnenie/
Disallow: /docs/stable2.6/changelog.html
Disallow: /registracziya-partnera/
Disallow: /resheniya-po-potrebnosti-udalennaya-podderzhka/
Disallow: /static/help/html/api.html
Disallow: /registracziya-partnerskoj-sdelki/
Disallow: /zakaz-oblachnoj-versii/
Disallow: /kompaniya-resursy-dokumentacziya/
Disallow: /news/zagolovok/
Disallow: /resheniya-po-sfere-otvetstvennosti-tehpodderzhka/
Disallow: /docs/stable2.6/api.html
Disallow: /resheniya-po-sfere-otvetstvennosti-klient/
Disallow: /resheniya-po-potrebnosti-udalennyj-dostup/
Disallow: /resheniya-po-otrasli-informaczionnye-tehnologii/
Disallow: /soglasie_na_rassilki/
Disallow: /preimushhestva-bezopasnost/
Disallow: /resheniya-po-potrebnosti-udalennoe-sistemnoe-administrirovanie/
Disallow: /resheniya-po-potrebnosti-uem/
Disallow: /news/zagolovok-1/
Disallow: /preimushhestva-prostota/
Disallow: /resheniya-po-potrebnosti-udalennaya-rabota/
Disallow: /preimushhestva-primery-ispolzovaniya/
Disallow: /order/test-success/
Disallow: /kompaniya-o-nas-vakansii/
Disallow: /oblachnoe-reshenie-rudesktop-dlya-domashnego-ispolzovaniya/
Disallow: /vozmozhnosti/
Disallow: /kompaniya-svyazatsya-podderzhka/
Disallow: /category/blog/
Disallow: /docs/stable2.6/search.html
Disallow: /news/zagolovok-2/
Disallow: /kompaniya-partnery-kommercheskie-partnery/
Disallow: /kompaniya-partnery-stat-partnerom/
Disallow: /resheniya-po-otrasli-konsalting/
Disallow: /ostavte-svoyu-zayavku-na-test/
Disallow: /news/zagolovok-4/
Disallow: /order/check-success/
Disallow: /resheniya-po-potrebnosti-podderzhka-mobilnyh-ustrojstv/
Disallow: /kompaniya-o-nas-o-kompanii/
Disallow: /zakaz-lokalnoj-versii/
Disallow: /thanks/server/
Disallow: /funkczii-sovmestnaya-rabota/
Disallow: /kompaniya-partnery-partnery-po-integraczii/
Disallow: /zakaz-uem/
Disallow: /pd/
Disallow: /preimushhestva-proizvoditelnost/
Disallow: /resheniya-po-potrebnosti-oblachnoe-i-lokalnoe-reshenie/
Disallow: /docs/stable2.6/genindex.html
Disallow: /registracziya-partnerskoj-sdelki/success/
Disallow: /registracziya-partnera/success/
Disallow: /resheniya-po-potrebnosti-korporativnoe-reshenie/
Disallow: /kompaniya-resursy-primery-ispolzovaniya/
Disallow: /index.stub.php
Disallow: /news/subscription/
Disallow: /support-success/
Disallow: /kompaniya-partnery-tehnologicheskie-partnery/
Disallow: /kompaniya-svyazatsya-prodazhi/
Disallow: /resheniya-po-otrasli-korporaczii/
Disallow: /otraslevie-resheniya/
Disallow: /resheniya-po-potrebnosti-udalennaya-sovmestnaya-rabota/
Disallow: /order/kp-success/
Disallow: /news/zagolovok-3/
Disallow: /thanks/order/
Disallow: /google_play/
Disallow: /order/pay-success/
Disallow: /kompaniya-o-nas-pressa-o-nas/

Disallow: /prd/success/
Disallow: /order/check-success/

Clean-param: utm
Clean-param: etext
Clean-param: yclid
Clean-param: ref
Clean-param: k50id

Sitemap: https://rudesktop.ru/page-sitemap.xml

Host: https://rudesktop.ru/