User-agent: * 
Allow: /
Sitemap: https://www.santander.pl/sitemap.xml
Disallow: /lp
Disallow: /ws-
Disallow: /tfi/lp
Disallow: /tfi/tools
Disallow: /ipdef
Disallow: /regulation_file_server/time2021022309*
Disallow: /regulation_file_server/time2021022310*
Disallow: /regulation_file_server/time2022022310*
Disallow: /*action=*
Disallow: /*ads.txt$
Disallow: /_fileserver/
Disallow: /_europe-time
Disallow: /app-ads.txt
Disallow: /santander-universidades/aktualnosci
Disallow: /klient-indywidualny/bankowosc-internetowa/bezpieczne-bankowanie/komunikaty