User-agent: *
Disallow: /data/loads/*
Disallow: /*-104/*
Disallow: /1*
Disallow: /immortal/k*
Allow: /*lan=ru*style=2*
Allow: /*lan=en*style=2*
Disallow: /*lan=*style=*
Allow: /*style=2*lan=ru*
Allow: /*style=2*lan=en*
Disallow: /*style=*lan=*
Allow: /stories/ru/2*
Allow: /stories/ru/2/search/*/body.html
Allow: /stories/ru/2/search/top*.html
Disallow: /stories/ru/2/search/*.html
Disallow: /stories/ru/2/*_print.html
Disallow: /stories/ru/2/random*
Disallow: /stories/*
Allow: /music/ru/2*
Disallow: /music/*
Disallow: /*/uk/*
Disallow: /*/download-*
Disallow: /pictures/
Disallow: /i/*
Disallow: /*?*no_js_rsz=*
Disallow: /*?*sfn_stp=*
Disallow: /*?*no_js_rds=*
Disallow: /*?*PHPSESSID=*
Disallow: /*?*start=*
Clean-param: acs&rcs&scta&sctr&sctd&plus&minus&no_js_rds&no_js_rsz&print_a&not_print&lks&sq&sfn_stp&slov&view&view_game_links&hide_game_links&lan&style&alter&foto&foto_full&abc&n&gn&bl&pg&prv&prw&new&que&cpbr&start&PHPSESSID


User-agent: AhrefsBot
Disallow: /
User-agent: Amazonbot
Disallow: /
User-agent: Baiduspider
Disallow: /
User-agent: barkrowler
Disallow: /
User-agent: BLEXBot
Disallow: /
User-agent: Bytespider
Disallow: /
User-agent: CCBot
Disallow: /
User-agent: ClaudeBot
Disallow: /
User-agent: Claude-Web
Disallow: /
User-agent: Cliqzbot
Disallow: /
User-agent: coccocbot
Disallow: /
User-agent: DataForSeoBot
Disallow: /
User-agent: dotbot
Disallow: /
User-agent: GPTBot
Disallow: /
User-agent: ImagesiftBot
Disallow: /
User-agent: Linguee
Disallow: /
User-agent: megaindex
Disallow: /
User-agent: Nimbostratus
Disallow: /
User-agent: oBot
Disallow: /
User-agent: PerplexityBot
Disallow: /
User-agent: PetalBot
Disallow: /
User-agent: proximic
Disallow: /
User-agent: Seekport Crawler
Disallow: /
User-agent: SemrushBot
Disallow: /
User-agent: serpstatbot
Disallow: /
User-agent: SMTBot
Disallow: /
User-agent: SurdotlyBot
Disallow: /
User-agent: Turnitin Robot
Disallow: /
User-agent: YouBot
Disallow: /
