User-agent: *
Disallow: /terms
Disallow: /access
Disallow: /algemene-voorwaarden
Disallow: /contact
Disallow: /privacy
Disallow: /autologin/*
Disallow: /openmessage/*
Disallow: /autolink/*
Disallow: /unsubscribe/*
Disallow: /rapporteer/*
Disallow: /smallimg/*
Disallow: /uploads/*
Disallow: /verifyemail/*
Disallow: /activeren/*
Disallow: /list_unsubscribe/*
Disallow: /open_image/*
Disallow: /ajax/*
Disallow: /datingtips
Disallow: /readmessage/*
Disallow: /unsub/*