User-agent: *
Allow: /
Disallow: /includes/
Disallow: /local/
Disallow: /search/
Disallow: /config/
Disallow: /cgi-bin/
Disallow: /*?*
Disallow: /*.pdf$
Disallow: /*.doc$
Disallow: /*.docx$
Disallow: /*.xls$
Disallow: /*.xlsx$
Disallow: /*.zip$
Disallow: /*.rar$
Allow: /*.js$
Allow: /*.css$
Allow: /uploads/
Allow: /image/
Sitemap: https://sfn-am.ru/sitemap.xml
Clean-param: rclid&ts&erid&target&utm&city&guuid