User-agent: *
Disallow: /*?*
Disallow: /product
Disallow: /_
Disallow: /_/*
Disallow: /student*
Disallow: /oly/*
Disallow: /cms*
Disallow: /articles/material-preview*
Disallow: /articles/study/*
Disallow: /articles/growth/*
Disallow: /articles/relax/*
Disallow: /articles/family/*
Disallow: /articles/news/*
Disallow: /courses-new*
Disallow: /contest*
Disallow: /no-gtm*
Disallow: /free-lesson*
Disallow: /welcome-englishdom-students/start*
Disallow: /404*
Disallow: /*%3Ffbclid
Disallow: /*&etext=2202
Disallow: /articles/old-articles
Disallow: /articles/new-design
Disallow: /tests
Disallow: /programmirovanie-corp
Disallow: /programmirovanie-lesson-blockly
Disallow: /repetitors/id/
Disallow: /distant/olimpiada-4-klass/
Disallow: /repetitors/anglijskij-yazyk/13-let/dlya-uspeshnoj-ucheby-i-karery/russkoyazychnye/pre-intermediate
Disallow: /distant/jobs/rus/
Disallow: /repetitors/details*

Sitemap: https://skysmart.ru/teacher-catalog/filter/sitemap.xml
Sitemap: https://skysmart.ru/assets/sitemaps/skysmart_sitemap.xml
Sitemap: https://skysmart.ru/assets/sitemaps/skysmart_articles_sitemap.xml
Sitemap: https://skysmart.ru/assets/sitemaps/skysmart_articles_media_sitemap.xml
Sitemap: https://skysmart.ru/assets/sitemaps/skysmart_vpr_sitemap.xml
Sitemap: https://skysmart.ru/assets/sitemaps/skysmart_calculators_sitemap.xml
Sitemap: https://skysmart.ru/assets/sitemaps/skysmart_courses_page_sitemap.xml
Sitemap: https://skysmart.ru/assets/sitemaps/sitemap_vpr_pdf.xml
Sitemap: https://skysmart.ru/assets/sitemaps/sitemap-training.xml