User-agent: *
Disallow: /Raport
Disallow: /Zapytanie
Disallow: /oferta-dane.gg
Disallow: /oferta-dane.skype
Disallow: /oferta-dane.telefon
Disallow: /oferta-dane.podobne
Disallow: /oferta-wydruk
Disallow: /location-autocomplete/ajax-get-city-list/
Disallow: /user/login-again
Disallow: /Ax-Get-Offer-Counts
Disallow: /ax-contact-form-submit/
Disallow: /UpdateMap/
Disallow: /channel.html
Disallow: /Offer-List-Locations-Autocompleter/
Disallow: /swf/swfupload.swf
Disallow: /favorites/ajax-add-del
Disallow: /usun-oferte
Disallow: /usun-ogloszenie
Disallow: /wypromuj-oferte/numer
Disallow: /wypromuj-ogloszenie/numer
Disallow: /zaloguj
Disallow: /Aktywuj
Disallow: /Aktywuj_oferte
Disallow: /new-offer-manager/temp-offer-preview
Disallow: /widget/
Disallow: /pobierz-widget/
Disallow: /schowek/
Disallow: /selector.html
Disallow: /cnt.html
Disallow: /oA.html
Disallow: /wp-login.php
Disallow: /oferta-dane.czesci-samochodowe/
Disallow: /Edycja_oferty/ID/
Disallow: /Dodaj_oferty/ID/
Disallow: /Dodaj_oferte/ID/
Disallow: /Podglad_oferty/ID/
Disallow: /HpGetOfferOfTheDay
Disallow: /Edycja_oferty/numer/
Disallow: /usun-oferte/
Disallow: /wypromuj-ogloszenie/numer/
Disallow: /regulamin$
Disallow: /regulamin-nastepny$
Disallow: /regulamin-20190529$
Disallow: /regulamin-20200104$
Disallow: /regulamin-20210816$
Disallow: /regulamin-20211018$
Disallow: /regulamin-20220308$
Disallow: /regulamin-20240416$
Disallow: /webview/regulamin$
Disallow: /webview/regulamin-nastepny$
Disallow: /webview/regulamin-20190529$
Disallow: /webview/regulamin-20200104$
Disallow: /webview/regulamin-20210816$
Disallow: /webview/regulamin-20211018$
Disallow: /webview/regulamin-20220308$
Disallow: /webview/regulamin-20240416$
Disallow: /polityka-prywatnosci
Disallow: /webview/polityka-prywatnosci
Disallow: /zaufani-partnerzy
Disallow: /webview/zaufani-partnerzy
Disallow: /kalkulator-pozyczek/
Disallow: /kalkulator-pozyczek
Disallow: /oferta-partnerska/
Disallow: /enter-process
Disallow: /Twoje-Konwersacje/
Disallow: /Twoje-Konwersacje/zobacz/mdut/
Disallow: /Twoje-Konwersacje/zobacz/ttpt/
Disallow: /logowanie
Disallow: /passb
Disallow: /pro/ajax-bundles
Disallow: /pro/ajax-subscription-box
Disallow: /main-category-url-list/
Disallow: *inp_*
Disallow: *lista-ofert.atom*
Disallow: *vmode=*

User-agent: Abonti
Disallow: /
User-agent: aggregator
Disallow: /
User-agent: asterias
Disallow: /
User-agent: BDCbot
Disallow: /
User-agent: BLEXBot
Disallow: /
User-agent: BuiltBotTough
Disallow: /
User-agent: Bullseye
Disallow: /
User-agent: BunnySlippers
Disallow: /
User-agent: ca-crawler
Disallow: /
User-agent: CCBot
Disallow: /
User-agent: Cegbfeieh
Disallow: /
User-agent: CheeseBot
Disallow: /
User-agent: CherryPicker
Disallow: /
User-agent: CopyRightCheck
Disallow: /
User-agent: cosmos
Disallow: /
User-agent: Crescent
Disallow: /
User-agent: discobot
Disallow: /
User-agent: DittoSpyder
Disallow: /
User-agent: DOC
Disallow: /
User-agent: DotBot
Disallow: /
User-agent: Download Ninja
Disallow: /
User-agent: EasouSpider
Disallow: /
User-agent: EmailCollector
Disallow: /
User-agent: EmailSiphon
Disallow: /
User-agent: EmailWolf
Disallow: /
User-agent: EroCrawler
Disallow: /
User-agent: Exabot
Disallow: /
User-agent: ExtractorPro
Disallow: /
User-agent: Fasterfox
Disallow: /
User-agent: FeedBooster
Disallow: /
User-agent: Foobot
Disallow: /
User-agent: Genieo
Disallow: /
User-agent: grub-client
Disallow: /
User-agent: Harvest
Disallow: /
User-agent: hloader
Disallow: /
User-agent: httplib
Disallow: /
User-agent: HTTrack
Disallow: /
User-agent: humanlinks
Disallow: /
User-agent: ieautodiscovery
Disallow: /
User-agent: InfoNaviRobot
Disallow: /
User-agent: IstellaBot
Disallow: /
User-agent: Java/1.
Disallow: /
User-agent: JennyBot
Disallow: /
User-agent: k2spider
Disallow: /
User-agent: Kenjin Spider
Disallow: /
User-agent: Keyword Density/0.9
Disallow: /
User-agent: larbin
Disallow: /
User-agent: LexiBot
Disallow: /
User-agent: libWeb
Disallow: /
User-agent: libwww
Disallow: /
User-agent: LinkextractorPro
Disallow: /
User-agent: linko
Disallow: /
User-agent: LinkScan/8.1a Unix
Disallow: /
User-agent: LinkWalker
Disallow: /
User-agent: LNSpiderguy
Disallow: /
User-agent: lwp-trivial
Disallow: /
User-agent: magpie
Disallow: /
User-agent: Mata Hari
Disallow: /
User-agent: MaxPointCrawler
Disallow: /
User-agent: MegaIndex
Disallow: /
User-agent: Microsoft URL Control
Disallow: /
User-agent: MIIxpc
Disallow: /
User-agent: Mippin
Disallow: /
User-agent: Missigua Locator
Disallow: /
User-agent: Mister PiX
Disallow: /
User-agent: moget
Disallow: /
User-agent: MSIECrawler
Disallow: /
User-agent: NetAnts
Disallow: /
User-agent: NICErsPRO
Disallow: /
User-agent: Niki-Bot
Disallow: /
User-agent: NPBot
Disallow: /
User-agent: Nutch
Disallow: /
User-agent: Offline Explorer
Disallow: /
User-agent: Openfind
Disallow: /
User-agent: panscient.com
Disallow: /
User-agent: PHP/5.{
Disallow: /
User-agent: ProPowerBot/2.14
Disallow: /
User-agent: ProWebWalker
Disallow: /
User-agent: Python-urllib
Disallow: /
User-agent: QueryN Metasearch
Disallow: /
User-agent: RepoMonkey
Disallow: /
User-agent: RMA
Disallow: /
User-agent: SemrushBot
Disallow: /
User-agent: SeznamBot
Disallow: /
User-agent: SISTRIX
Disallow: /
User-agent: sitecheck.Internetseer.com
Disallow: /
User-agent: SiteSnagger
Disallow: /
User-agent: SnapPreviewBot
Disallow: /
User-agent: Sogou
Disallow: /
User-agent: SpankBot
Disallow: /
User-agent: spanner
Disallow: /
User-agent: spbot
Disallow: /
User-agent: Spinn3r
Disallow: /
User-agent: suzuran
Disallow: /
User-agent: Szukacz/1.4
Disallow: /
User-agent: Teleport
Disallow: /
User-agent: Telesoft
Disallow: /
User-agent: The Intraformant
Disallow: /
User-agent: TheNomad
Disallow: /
User-agent: TightTwatBot
Disallow: /
User-agent: Titan
Disallow: /
User-agent: toCrawl/UrlDispatcher
Disallow: /
User-agent: True_Robot
Disallow: /
User-agent: turingos
Disallow: /
User-agent: TurnitinBot
Disallow: /
User-agent: UbiCrawler
Disallow: /
User-agent: UnisterBot
Disallow: /
User-agent: URLy Warning
Disallow: /
User-agent: VCI
Disallow: /
User-agent: WBSearchBot
Disallow: /
User-agent: Web Downloader/6.9
Disallow: /
User-agent: Web Image Collector
Disallow: /
User-agent: WebAuto
Disallow: /
User-agent: WebBandit
Disallow: /
User-agent: WebCopier
Disallow: /
User-agent: WebEnhancer
Disallow: /
User-agent: WebmasterWorldForumBot
Disallow: /
User-agent: WebReaper
Disallow: /
User-agent: WebSauger
Disallow: /
User-agent: Website Quester
Disallow: /
User-agent: Webster Pro
Disallow: /
User-agent: WebStripper
Disallow: /
User-agent: WebZip
Disallow: /
User-agent: Wotbox
Disallow: /
User-agent: wsr-agent
Disallow: /
User-agent: WWW-Collector-E
Disallow: /
User-agent: Xenu
Disallow: /
User-agent: Zao
Disallow: /
User-agent: Zeus
Disallow: /
User-agent: ZyBORG
Disallow: /
User-agent: coccoc
Disallow: /
User-agent: Incutio
Disallow: /
User-agent: lmspider
Disallow: /
User-agent: memoryBot
Disallow: /
User-agent: SemrushBot
Disallow: /
User-agent: serf
Disallow: /
User-agent: Unknown
Disallow: /
User-agent: uptime files
Disallow: /
User-agent: rogerbot
Disallow: /
User-agent: gigabot
Disallow: /
User-agent: sitebot
Disallow: /
User-agent: LexxeBot
Disallow: /
User-agent: Ezooms
Disallow: /
User-agent: ichiro
Disallow: /
User-agent: Twiceler
Disallow: /
User-agent: Zealbot
Disallow: /
User-agent: Fetch
Disallow: /
User-agent: TeleportPro
Disallow: /
User-agent: wget
Disallow: /
User-agent: ia_archiver
Disallow: /
User-agent: archive.org_bot
Disallow: /
User-agent: ia_archiver-web.archive.org
Disallow: /
