User-agent: *

Disallow: /webtv
Noindex:  /webtv

Disallow: /videos
Noindex:  /videos

Disallow: /Pages
Noindex:  /Pages

Disallow: /tv/netvolution
Noindex:  /tv/netvolution

Disallow: /eidiseis/ellada/476740/thanashs-lalas-synelhfthh-apo-thn-astynomia
Noindex: /eidiseis/ellada/476740/thanashs-lalas-synelhfthh-apo-thn-astynomia

Disallow: /eidiseis/ellada/205113/erotiko_skandalo_me_archimandriti_sygklonizei_tin_limno_
Noindex: /eidiseis/ellada/205113/erotiko_skandalo_me_archimandriti_sygklonizei_tin_limno_

Disallow: /eidiseis/ellada/207884/48chroni_eroteftike_enan_archimandriti_kai_egkateleipse_to_syzygo_kai_ta_paidia_tis
Noindex:  /eidiseis/ellada/207884/48chroni_eroteftike_enan_archimandriti_kai_egkateleipse_to_syzygo_kai_ta_paidia_tis

Disallow:  /eidiseis/athlitika/483189/xrysos-xana-o-andreas-bazaios
Noindex:  /eidiseis/athlitika/483189/xrysos-xana-o-andreas-bazaios

Disallow:  /eidiseis/athlitika/432642/sth-magiorka-o-soymaxer
Noindex:   /eidiseis/athlitika/432642/sth-magiorka-o-soymaxer

Disallow:  /lifestyle/media/488261/masterchef-4-h-audition-toy-filippoy-apo-ta-grebena
Noindex:   /lifestyle/media/488261/masterchef-4-h-audition-toy-filippoy-apo-ta-grebena

Disallow:  /eidiseis/ellada/489720/giatros-dexthke-epithesh-apo-roma-thn-wra-exetashs-sta-megara
Noindex:   /eidiseis/ellada/489720/giatros-dexthke-epithesh-apo-roma-thn-wra-exetashs-sta-megara

Disallow:  /lifestyle/celebrities/439199/xafnikos-xwrismos-gia-ellhna-hthopoio
Noindex:   /lifestyle/celebrities/439199/xafnikos-xwrismos-gia-ellhna-hthopoio

Disallow:  /lifestyle/celebrities/388267/mia-dikhgoros-gia-ton-mano-iwannoy-deite-poia-toy-exei-klepsei-thn-kardia
Noindex:   /lifestyle/celebrities/388267/mia-dikhgoros-gia-ton-mano-iwannoy-deite-poia-toy-exei-klepsei-thn-kardia

Disallow:  /eidiseis/ellada/502095/ellada-korwnoios-xekina-ton-ioynio-o-emboliasmos/amp
Noindex:   /eidiseis/ellada/502095/ellada-korwnoios-xekina-ton-ioynio-o-emboliasmos/amp

Disallow:  /eidiseis/ellada/381717/prosoxh-opoios-gnwrizei-ayto-to-agoraki-na-eidopoihsei-thn-astynomia-anazhtoyntai-oi-goneis-toy
Noindex:   /eidiseis/ellada/381717/prosoxh-opoios-gnwrizei-ayto-to-agoraki-na-eidopoihsei-thn-astynomia-anazhtoyntai-oi-goneis-toy

Disallow:  /eidiseis/ellada/381717/prosoxh-opoios-gnwrizei-ayto-to-agoraki-na-eidopoihsei-thn-astynomia-anazhtoyntai-oi-goneis-toy/amp
Noindex:   /eidiseis/ellada/381717/prosoxh-opoios-gnwrizei-ayto-to-agoraki-na-eidopoihsei-thn-astynomia-anazhtoyntai-oi-goneis-toy/amp

Disallow:  /eidiseis/ellada/212558/afti_einai_i_51chroni_pou_yposchotan_
Noindex:   /eidiseis/ellada/212558/afti_einai_i_51chroni_pou_yposchotan_

Disallow:  /eidiseis/ellada/212558/afti_einai_i_51chroni_pou_yposchotan_/amp
Noindex:   /eidiseis/ellada/212558/afti_einai_i_51chroni_pou_yposchotan_/amp

Disallow:  /eidiseis/athlitika/190554/ellinas_olympionikis_kai_i_proin_syzygos_tou_sta_machairia_gia_to_paidi_tous
Noindex:   /eidiseis/athlitika/190554/ellinas_olympionikis_kai_i_proin_syzygos_tou_sta_machairia_gia_to_paidi_tous

Disallow:  /eidiseis/athlitika/190554/ellinas_olympionikis_kai_i_proin_syzygos_tou_sta_machairia_gia_to_paidi_tous/amp
Noindex:   /eidiseis/athlitika/190554/ellinas_olympionikis_kai_i_proin_syzygos_tou_sta_machairia_gia_to_paidi_tous/amp

Disallow:  /eidiseis/ellada/494420/aytoi-einai-oi-11-syllhfthentes-ths-giafkas-sta-sepolia
Noindex:   /eidiseis/ellada/494420/aytoi-einai-oi-11-syllhfthentes-ths-giafkas-sta-sepolia

Disallow:  /eidiseis/ellada/494420/aytoi-einai-oi-11-syllhfthentes-ths-giafkas-sta-sepolia/amp
Noindex:   /eidiseis/ellada/494420/aytoi-einai-oi-11-syllhfthentes-ths-giafkas-sta-sepolia/amp

Disallow:  /eidiseis/ellada/459174/paidiatros-deite-ton-64xrono-poy-kathgoreitai-gia-aselgeia
Noindex:   /eidiseis/ellada/459174/paidiatros-deite-ton-64xrono-poy-kathgoreitai-gia-aselgeia

Disallow:  /eidiseis/ellada/459174/paidiatros-deite-ton-64xrono-poy-kathgoreitai-gia-aselgeia/amp
Noindex:   /eidiseis/ellada/459174/paidiatros-deite-ton-64xrono-poy-kathgoreitai-gia-aselgeia/amp

Disallow:  /eidiseis/ellada/459004/diwxh-se-bathmo-kakoyrghmatos-se-paidiatro-ths-thhbas-gia-aselgeia
Noindex:   /eidiseis/ellada/459004/diwxh-se-bathmo-kakoyrghmatos-se-paidiatro-ths-thhbas-gia-aselgeia

Disallow:  /eidiseis/ellada/459004/diwxh-se-bathmo-kakoyrghmatos-se-paidiatro-ths-thhbas-gia-aselgeia/amp
Noindex:   /eidiseis/ellada/459004/diwxh-se-bathmo-kakoyrghmatos-se-paidiatro-ths-thhbas-gia-aselgeia/amp

Disallow:  /eidiseis/ellada/459094/ton-dromo-gia-th-fylakh-pairnei-o-paidiatros-ths-thhbas
Noindex:   /eidiseis/ellada/459094/ton-dromo-gia-th-fylakh-pairnei-o-paidiatros-ths-thhbas

Disallow:  /eidiseis/ellada/459094/ton-dromo-gia-th-fylakh-pairnei-o-paidiatros-ths-thhbas/amp
Noindex:   /eidiseis/ellada/459094/ton-dromo-gia-th-fylakh-pairnei-o-paidiatros-ths-thhbas/amp

Disallow: /eidiseis/ellada/460761/neos-kathhghths-fakelakhs-poyloyse-ergasies
Noindex:  /eidiseis/ellada/460761/neos-kathhghths-fakelakhs-poyloyse-ergasies

Disallow: /eidiseis/ellada/460761/neos-kathhghths-fakelakhs-poyloyse-ergasies/amp
Noindex:  /eidiseis/ellada/460761/neos-kathhghths-fakelakhs-poyloyse-ergasies/amp

Disallow: /eidiseis/ellada/469858/kathhghths-fakelakhsapofylakisthke-10-mhnes-meta-th-syllhpsh-toy
Noindex:  /eidiseis/ellada/469858/kathhghths-fakelakhsapofylakisthke-10-mhnes-meta-th-syllhpsh-toy

Disallow: /eidiseis/ellada/469858/kathhghths-fakelakhsapofylakisthke-10-mhnes-meta-th-syllhpsh-toy/amp
Noindex:  /eidiseis/ellada/469858/kathhghths-fakelakhsapofylakisthke-10-mhnes-meta-th-syllhpsh-toy/amp

Disallow: /eidiseis/ellada/437561/sth-fylakh-o-kathhghths-fakelakhs-toy-tei-serrwn
Noindex:  /eidiseis/ellada/437561/sth-fylakh-o-kathhghths-fakelakhs-toy-tei-serrwn

Disallow: /eidiseis/ellada/437561/sth-fylakh-o-kathhghths-fakelakhs-toy-tei-serrwn/amp
Noindex:  /eidiseis/ellada/437561/sth-fylakh-o-kathhghths-fakelakhs-toy-tei-serrwn/amp

Disallow: /eidiseis/ellada/437264/gioyxarisma-ston-kathhghth-fakelakh-se-orkwmosia-twn-tei-serrwn
Noindex:  /eidiseis/ellada/437264/gioyxarisma-ston-kathhghth-fakelakh-se-orkwmosia-twn-tei-serrwn

Disallow: /eidiseis/ellada/437264/gioyxarisma-ston-kathhghth-fakelakh-se-orkwmosia-twn-tei-serrwn/amp
Noindex:  /eidiseis/ellada/437264/gioyxarisma-ston-kathhghth-fakelakh-se-orkwmosia-twn-tei-serrwn/amp

Disallow: /eidiseis/ellada/437228/nea-martyria-foithtrias-gia-ton-kathhghth-fakelakh-sto-tei-serrwn
Noindex:  /eidiseis/ellada/437228/nea-martyria-foithtrias-gia-ton-kathhghth-fakelakh-sto-tei-serrwn

Disallow: /eidiseis/ellada/437228/nea-martyria-foithtrias-gia-ton-kathhghth-fakelakh-sto-tei-serrwn/amp
Noindex:  /eidiseis/ellada/437228/nea-martyria-foithtrias-gia-ton-kathhghth-fakelakh-sto-tei-serrwn/amp

Disallow: /eidiseis/ellada/445781/kathhghths-fakelakhs-gia-fiasko-typoy-rixardoy-mila-o-koygias
Noindex:  /eidiseis/ellada/445781/kathhghths-fakelakhs-gia-fiasko-typoy-rixardoy-mila-o-koygias

Disallow: /eidiseis/ellada/445781/kathhghths-fakelakhs-gia-fiasko-typoy-rixardoy-mila-o-koygias/amp
Noindex:  /eidiseis/ellada/445781/kathhghths-fakelakhs-gia-fiasko-typoy-rixardoy-mila-o-koygias/amp

Disallow: /eidiseis/ellada/437487/oloi-gnwrizan-gia-ton-kathhghth-fakelakh-sto-tei-serrwn
Noindex:  /eidiseis/ellada/437487/oloi-gnwrizan-gia-ton-kathhghth-fakelakh-sto-tei-serrwn

Disallow: /eidiseis/ellada/437487/oloi-gnwrizan-gia-ton-kathhghth-fakelakh-sto-tei-serrwn/amp
Noindex:  /eidiseis/ellada/437487/oloi-gnwrizan-gia-ton-kathhghth-fakelakh-sto-tei-serrwn/amp

Disallow: /eidiseis/ellada/437328/kathhghths-stis-serres-einai-ntroph-osa-legontai-gia-mena
Noindex:  /eidiseis/ellada/437328/kathhghths-stis-serres-einai-ntroph-osa-legontai-gia-mena

Disallow: /eidiseis/ellada/437328/kathhghths-stis-serres-einai-ntroph-osa-legontai-gia-mena/amp
Noindex:  /eidiseis/ellada/437328/kathhghths-stis-serres-einai-ntroph-osa-legontai-gia-mena/amp

Disallow: /video=437343
Noindex:  /video=437343

Disallow: /video=437568
Noindex:  /video=437568

Disallow: /eidiseis/ellada/437343/para-tis-kataggelies-apto-2004-kaneis-de-stamathse-ton-kathhghth/amp
Noindex:  /eidiseis/ellada/437343/para-tis-kataggelies-apto-2004-kaneis-de-stamathse-ton-kathhghth/amp

Disallow: /eidiseis/ellada/437343/para-tis-kataggelies-apto-2004-kaneis-de-stamathse-ton-kathhghth
Noindex:  /eidiseis/ellada/437343/para-tis-kataggelies-apto-2004-kaneis-de-stamathse-ton-kathhghth

Disallow: /video/eidiseis=445781
Noindex:  /video/eidiseis=445781

Disallow:/video=437402
Noindex: /video=437402

Disallow: /eidiseis/ellada/437402/ti-apofasise-h-sygklhtos-toy-tei-serrwn-gia-ton-kathhghth-fakelakh
Noindex:  /eidiseis/ellada/437402/ti-apofasise-h-sygklhtos-toy-tei-serrwn-gia-ton-kathhghth-fakelakh

Disallow: /eidiseis/ellada/437402/ti-apofasise-h-sygklhtos-toy-tei-serrwn-gia-ton-kathhghth-fakelakh/amp
Noindex:  /eidiseis/ellada/437402/ti-apofasise-h-sygklhtos-toy-tei-serrwn-gia-ton-kathhghth-fakelakh/amp

Disallow: /video=437325
Noindex:  /video=437325

Disallow: /eidiseis/ellada/437194/profylakisteos-o-kathhghths-poy-zhtoyse-xrhmata-apo-foithtes/amp
Noindex:  /eidiseis/ellada/437194/profylakisteos-o-kathhghths-poy-zhtoyse-xrhmata-apo-foithtes/amp

Disallow: /eidiseis/ellada/437194/profylakisteos-o-kathhghths-poy-zhtoyse-xrhmata-apo-foithtes
Noindex:  /eidiseis/ellada/437194/profylakisteos-o-kathhghths-poy-zhtoyse-xrhmata-apo-foithtes

Disallow: /eidiseis/ellada/437452/serres-kyklwma-pisw-apo-ton-kathhghth
Noindex:  /eidiseis/ellada/437452/serres-kyklwma-pisw-apo-ton-kathhghth

Disallow: /eidiseis/ellada/437452/serres-kyklwma-pisw-apo-ton-kathhghth/amp
Noindex:  /eidiseis/ellada/437452/serres-kyklwma-pisw-apo-ton-kathhghth/amp

Disallow: /eidiseis/ellada/437325/apokalypseis-foithtrias-gia-ton-kathhghth-stis-serres/amp
Noindex:  /eidiseis/ellada/437325/apokalypseis-foithtrias-gia-ton-kathhghth-stis-serres/amp

Disallow: /eidiseis/ellada/437325/apokalypseis-foithtrias-gia-ton-kathhghth-stis-serres
Noindex:  /eidiseis/ellada/437325/apokalypseis-foithtrias-gia-ton-kathhghth-stis-serres

Disallow: /eidiseis/ellada/437351/apokalyptikes-synomilies-gia-th-drash-toy-kathhghth-stis-serres/amp
Noindex:  /eidiseis/ellada/437351/apokalyptikes-synomilies-gia-th-drash-toy-kathhghth-stis-serres/amp

Disallow: /eidiseis/ellada/437351/apokalyptikes-synomilies-gia-th-drash-toy-kathhghth-stis-serres
Noindex:  /eidiseis/ellada/437351/apokalyptikes-synomilies-gia-th-drash-toy-kathhghth-stis-serres

Disallow: /eidiseis/ellada/437444/kathhghths-se-panepisthmio-ths-athhnas-parenoxlei-foithtries/amp
Noindex:  /eidiseis/ellada/437444/kathhghths-se-panepisthmio-ths-athhnas-parenoxlei-foithtries/amp

Disallow: /eidiseis/ellada/437444/kathhghths-se-panepisthmio-ths-athhnas-parenoxlei-foithtries
Noindex:  /eidiseis/ellada/437444/kathhghths-se-panepisthmio-ths-athhnas-parenoxlei-foithtries

Disallow: /eidiseis/ellada/437809/serres-aytos-einai-o-kathhghths-fakelakhs/amp
Noindex:  /eidiseis/ellada/437809/serres-aytos-einai-o-kathhghths-fakelakhs/amp

Disallow: /eidiseis/ellada/437809/serres-aytos-einai-o-kathhghths-fakelakhs
Noindex:  /eidiseis/ellada/437809/serres-aytos-einai-o-kathhghths-fakelakhs

Disallow: /video=437627
Noindex:  /video=437627

Disallow: /video=437809
Noindex:  /video=437809

Disallow: /video=445781
Noindex:  /video=445781

Disallow: /video/latest=437809
Noindex:  /video/latest=437809

Disallow: /eidiseis/ellada/437516/me-xeiropedes-ston-anakrith-o-kathhghths-fakelakhs
Noindex:  /eidiseis/ellada/437516/me-xeiropedes-ston-anakrith-o-kathhghths-fakelakhs

Disallow: /lifestyle/celebrities/556040/mad-clip-teleytaia-stigmh-h-foyreira-den-mphke-sthn-porche
Noindex:  /lifestyle/celebrities/556040/mad-clip-teleytaia-stigmh-h-foyreira-den-mphke-sthn-porche

Disallow: /lifestyle/celebrities/556040/mad-clip-teleytaia-stigmh-h-foyreira-den-mphke-sthn-porche/amp
Noindex:  /lifestyle/celebrities/556040/mad-clip-teleytaia-stigmh-h-foyreira-den-mphke-sthn-porche/amp

Disallow: /eidiseis/ellada/437516/me-xeiropedes-ston-anakrith-o-kathhghths-fakelakhs/amp
Noindex:  /eidiseis/ellada/437516/me-xeiropedes-ston-anakrith-o-kathhghths-fakelakhs/amp

Disallow: /eidiseis/ellada/516136/xtyphse-26xrono-amea-epeidh-arghse-na-bgei-apo-thn-toyaleta
Noindex:  /eidiseis/ellada/516136/xtyphse-26xrono-amea-epeidh-arghse-na-bgei-apo-thn-toyaleta

Disallow: /eidiseis/ellada/516136/xtyphse-26xrono-amea-epeidh-arghse-na-bgei-apo-thn-toyaleta/amp
Noindex:  /eidiseis/ellada/516136/xtyphse-26xrono-amea-epeidh-arghse-na-bgei-apo-thn-toyaleta/amp

Disallow: /lifestyle/celebrities/170776/h_mimi_ntenisi_diapsevdei_oti_paschei_apo_parkinson
Noindex:  /lifestyle/celebrities/170776/h_mimi_ntenisi_diapsevdei_oti_paschei_apo_parkinson

Disallow: /lifestyle/celebrities/170776/h_mimi_ntenisi_diapsevdei_oti_paschei_apo_parkinson/amp
Noindex:  /lifestyle/celebrities/170776/h_mimi_ntenisi_diapsevdei_oti_paschei_apo_parkinson/amp

Disallow: /lifestyle/celebrities/530927/thanashs-eythymiadhs-osa-egrapse-gia-spyropoylo-kimoylh
Noindex: /lifestyle/celebrities/530927/thanashs-eythymiadhs-osa-egrapse-gia-spyropoylo-kimoylh

Disallow: /lifestyle/celebrities/530805/komnhnoy-hthele-na-me-paei-ws-proagwgos-se-diashmo-hthopoio
Noindex: /lifestyle/celebrities/530805/komnhnoy-hthele-na-me-paei-ws-proagwgos-se-diashmo-hthopoio

Disallow: /lifestyle/celebrities/530798/xrysikoy-h-kyria-doyka-anoixe-ton-dromo
Noindex: /lifestyle/celebrities/530798/xrysikoy-h-kyria-doyka-anoixe-ton-dromo

Disallow: /lifestyle/celebrities/530782/xespase-h-akrita-gia-tis-kataggelies-twn-hmerwn
Noindex: /lifestyle/celebrities/530782/xespase-h-akrita-gia-tis-kataggelies-twn-hmerwn

Disallow: /lifestyle/celebrities/530774/aggelikh-lamprh-oi-psyxologika-arrwstoi-na-pane-spitia-toys
Noindex: /lifestyle/celebrities/530774/aggelikh-lamprh-oi-psyxologika-arrwstoi-na-pane-spitia-toys

Disallow: /lifestyle/celebrities/530749/nees-kataggelies-gia-sexoyalikh-parenoxlhsh-apo-skhnotheth
Noindex: /lifestyle/celebrities/530749/nees-kataggelies-gia-sexoyalikh-parenoxlhsh-apo-skhnotheth

Disallow: /lifestyle/celebrities/530704/ferentinos-oi-pio-polloi-fobhthhkan-na-sthrixoyn-th-sofia
Noindex: /lifestyle/celebrities/530704/ferentinos-oi-pio-polloi-fobhthhkan-na-sthrixoyn-th-sofia

Disallow: /lifestyle/celebrities/530673/giannhs-mpezos-den-einai-olos-o-xwros-kolasthrio
Noindex: /lifestyle/celebrities/530673/giannhs-mpezos-den-einai-olos-o-xwros-kolasthrio

Disallow: /lifestyle/celebrities/530670/katerina-tsabaloy-sthrizei-anoixta-mpotsh-lamprh-mixala
Noindex: /lifestyle/celebrities/530670/katerina-tsabaloy-sthrizei-anoixta-mpotsh-lamprh-mixala

Disallow: /lifestyle/celebrities/530656/kapoytzidhs-sergoylopoylos-sthrizoyn-anoixta-mpotsh-lamprh
Noindex: /lifestyle/celebrities/530656/kapoytzidhs-sergoylopoylos-sthrizoyn-anoixta-mpotsh-lamprh

Disallow: /lifestyle/celebrities/530856/bana-mparmpa-h-thesh-poy-phre-dhmosia-gia-ton-giwrgo-kimoylh
Noindex: /lifestyle/celebrities/530856/bana-mparmpa-h-thesh-poy-phre-dhmosia-gia-ton-giwrgo-kimoylh

Disallow: /lifestyle/celebrities/530645/kwstas-spyropoylos-skandalo-gia-sexoyalikh-parenoxlhsh
Noindex: /lifestyle/celebrities/530645/kwstas-spyropoylos-skandalo-gia-sexoyalikh-parenoxlhsh

Disallow: /lifestyle/media/530825/marios-athanasioy-phre-thesh-yper-ths-lamprh
Noindex: /lifestyle/media/530825/marios-athanasioy-phre-thesh-yper-ths-lamprh

Disallow: /lifestyle/celebrities/530920/o-starobas-yper-toy-spyropoyloy-kai-an-den-egine
Noindex: /lifestyle/celebrities/530920/o-starobas-yper-toy-spyropoyloy-kai-an-den-egine

Disallow: /lifestyle/celebrities/530864/spyropoylos-apagoreyei-thn-anafora-toy-onomatos-toy
Noindex: /lifestyle/celebrities/530864/spyropoylos-apagoreyei-thn-anafora-toy-onomatos-toy

Disallow: /lifestyle/celebrities/530829/arzogloy-de-ta-pisteyw-ayta-gia-ton-kwsta-spyropoylo
Noindex: /lifestyle/celebrities/530829/arzogloy-de-ta-pisteyw-ayta-gia-ton-kwsta-spyropoylo

Disallow: /lifestyle/celebrities/530784/h-antidrash-toy-mpoyrdoymh-gia-ton-spyropoylo
Noindex: /lifestyle/celebrities/530784/h-antidrash-toy-mpoyrdoymh-gia-ton-spyropoylo

Disallow: /lifestyle/celebrities/530756/spyropoylos-h-moytafh-pairnei-thesh-stis-kataggelies
Noindex: /lifestyle/celebrities/530756/spyropoylos-h-moytafh-pairnei-thesh-stis-kataggelies

Disallow: /lifestyle/celebrities/530722/alles-dyo-kataggelies-kata-toy-kwsta-spyropoyloy
Noindex: /lifestyle/celebrities/530722/alles-dyo-kataggelies-kata-toy-kwsta-spyropoyloy

Disallow: /lifestyle/celebrities/530693/spyropoylos-zhta-syggnwmh-h-apanthsh-toy-dikhgoroy-toy
Noindex: /lifestyle/celebrities/530693/spyropoylos-zhta-syggnwmh-h-apanthsh-toy-dikhgoroy-toy

Disallow: /lifestyle/celebrities/530683/h-xristina-sampanikoy-kataggelei-ton-kwsta-spyropoylo
Noindex: /lifestyle/celebrities/530683/h-xristina-sampanikoy-kataggelei-ton-kwsta-spyropoylo

Disallow: /lifestyle/celebrities/530740/o-eythymhs-zhsakhs-katakeraynwnei-ton-kwsta-spyropoylo
Noindex: /lifestyle/celebrities/530740/o-eythymhs-zhsakhs-katakeraynwnei-ton-kwsta-spyropoylo

Disallow: /lifestyle/celebrities/530731/elisabet-moytafh-h-dhmosia-sthrixh-ths-sth-loykia-mixala
Noindex: /lifestyle/celebrities/530731/elisabet-moytafh-h-dhmosia-sthrixh-ths-sth-loykia-mixala

Disallow: /lifestyle/media/530801/nea-kataggelia-apo-hthopoio-kata-toy-kwsta-spyropoyloy
Noindex: /lifestyle/media/530801/nea-kataggelia-apo-hthopoio-kata-toy-kwsta-spyropoyloy

Disallow: /lifestyle/media/530748/stamatopoylos-nea-stoixeia-gia-tis-kataggelies-ths-mpotsh
Noindex: /lifestyle/media/530748/stamatopoylos-nea-stoixeia-gia-tis-kataggelies-ths-mpotsh


Disallow: /lifestyle/celebrities/530927/thanashs-eythymiadhs-osa-egrapse-gia-spyropoylo-kimoylh/amp
Noindex: /lifestyle/celebrities/530927/thanashs-eythymiadhs-osa-egrapse-gia-spyropoylo-kimoylh/amp

Disallow: /lifestyle/celebrities/530805/komnhnoy-hthele-na-me-paei-ws-proagwgos-se-diashmo-hthopoio/amp
Noindex: /lifestyle/celebrities/530805/komnhnoy-hthele-na-me-paei-ws-proagwgos-se-diashmo-hthopoio/amp

Disallow: /lifestyle/celebrities/530798/xrysikoy-h-kyria-doyka-anoixe-ton-dromo/amp
Noindex: /lifestyle/celebrities/530798/xrysikoy-h-kyria-doyka-anoixe-ton-dromo/amp

Disallow: /lifestyle/celebrities/530782/xespase-h-akrita-gia-tis-kataggelies-twn-hmerwn/amp
Noindex: /lifestyle/celebrities/530782/xespase-h-akrita-gia-tis-kataggelies-twn-hmerwn/amp

Disallow: /lifestyle/celebrities/530774/aggelikh-lamprh-oi-psyxologika-arrwstoi-na-pane-spitia-toys/amp
Noindex: /lifestyle/celebrities/530774/aggelikh-lamprh-oi-psyxologika-arrwstoi-na-pane-spitia-toys/amp

Disallow: /lifestyle/celebrities/530749/nees-kataggelies-gia-sexoyalikh-parenoxlhsh-apo-skhnotheth/amp
Noindex: /lifestyle/celebrities/530749/nees-kataggelies-gia-sexoyalikh-parenoxlhsh-apo-skhnotheth/amp

Disallow: /lifestyle/celebrities/530704/ferentinos-oi-pio-polloi-fobhthhkan-na-sthrixoyn-th-sofia/amp
Noindex: /lifestyle/celebrities/530704/ferentinos-oi-pio-polloi-fobhthhkan-na-sthrixoyn-th-sofia/amp

Disallow: /lifestyle/celebrities/530673/giannhs-mpezos-den-einai-olos-o-xwros-kolasthrio/amp
Noindex: /lifestyle/celebrities/530673/giannhs-mpezos-den-einai-olos-o-xwros-kolasthrio/amp

Disallow: /lifestyle/celebrities/530670/katerina-tsabaloy-sthrizei-anoixta-mpotsh-lamprh-mixala/amp
Noindex: /lifestyle/celebrities/530670/katerina-tsabaloy-sthrizei-anoixta-mpotsh-lamprh-mixala/amp

Disallow: /lifestyle/celebrities/530656/kapoytzidhs-sergoylopoylos-sthrizoyn-anoixta-mpotsh-lamprh/amp
Noindex: /lifestyle/celebrities/530656/kapoytzidhs-sergoylopoylos-sthrizoyn-anoixta-mpotsh-lamprh/amp

Disallow: /lifestyle/celebrities/530856/bana-mparmpa-h-thesh-poy-phre-dhmosia-gia-ton-giwrgo-kimoylh/amp
Noindex: /lifestyle/celebrities/530856/bana-mparmpa-h-thesh-poy-phre-dhmosia-gia-ton-giwrgo-kimoylh/amp

Disallow: /lifestyle/celebrities/530645/kwstas-spyropoylos-skandalo-gia-sexoyalikh-parenoxlhsh/amp
Noindex: /lifestyle/celebrities/530645/kwstas-spyropoylos-skandalo-gia-sexoyalikh-parenoxlhsh/amp

Disallow: /lifestyle/media/530825/marios-athanasioy-phre-thesh-yper-ths-lamprh/amp
Noindex: /lifestyle/media/530825/marios-athanasioy-phre-thesh-yper-ths-lamprh/amp

Disallow: /lifestyle/celebrities/530920/o-starobas-yper-toy-spyropoyloy-kai-an-den-egine/amp
Noindex: /lifestyle/celebrities/530920/o-starobas-yper-toy-spyropoyloy-kai-an-den-egine/amp

Disallow: /lifestyle/celebrities/530864/spyropoylos-apagoreyei-thn-anafora-toy-onomatos-toy/amp
Noindex: /lifestyle/celebrities/530864/spyropoylos-apagoreyei-thn-anafora-toy-onomatos-toy/amp

Disallow: /lifestyle/celebrities/530829/arzogloy-de-ta-pisteyw-ayta-gia-ton-kwsta-spyropoylo/amp
Noindex: /lifestyle/celebrities/530829/arzogloy-de-ta-pisteyw-ayta-gia-ton-kwsta-spyropoylo/amp

Disallow: /lifestyle/celebrities/530784/h-antidrash-toy-mpoyrdoymh-gia-ton-spyropoylo/amp
Noindex: /lifestyle/celebrities/530784/h-antidrash-toy-mpoyrdoymh-gia-ton-spyropoylo/amp

Disallow: /lifestyle/celebrities/530756/spyropoylos-h-moytafh-pairnei-thesh-stis-kataggelies/amp
Noindex: /lifestyle/celebrities/530756/spyropoylos-h-moytafh-pairnei-thesh-stis-kataggelies/amp

Disallow: /lifestyle/celebrities/530722/alles-dyo-kataggelies-kata-toy-kwsta-spyropoyloy/amp
Noindex: /lifestyle/celebrities/530722/alles-dyo-kataggelies-kata-toy-kwsta-spyropoyloy/amp

Disallow: /lifestyle/celebrities/530693/spyropoylos-zhta-syggnwmh-h-apanthsh-toy-dikhgoroy-toy/amp
Noindex: /lifestyle/celebrities/530693/spyropoylos-zhta-syggnwmh-h-apanthsh-toy-dikhgoroy-toy/amp

Disallow: /lifestyle/celebrities/530683/h-xristina-sampanikoy-kataggelei-ton-kwsta-spyropoylo/amp
Noindex: /lifestyle/celebrities/530683/h-xristina-sampanikoy-kataggelei-ton-kwsta-spyropoylo/amp

Disallow: /lifestyle/celebrities/530740/o-eythymhs-zhsakhs-katakeraynwnei-ton-kwsta-spyropoylo/amp
Noindex: /lifestyle/celebrities/530740/o-eythymhs-zhsakhs-katakeraynwnei-ton-kwsta-spyropoylo/amp

Disallow: /lifestyle/celebrities/530731/elisabet-moytafh-h-dhmosia-sthrixh-ths-sth-loykia-mixala/amp
Noindex: /lifestyle/celebrities/530731/elisabet-moytafh-h-dhmosia-sthrixh-ths-sth-loykia-mixala/amp

Disallow: /lifestyle/media/530801/nea-kataggelia-apo-hthopoio-kata-toy-kwsta-spyropoyloy/amp
Noindex: /lifestyle/media/530801/nea-kataggelia-apo-hthopoio-kata-toy-kwsta-spyropoyloy/amp

Disallow: /lifestyle/media/530748/stamatopoylos-nea-stoixeia-gia-tis-kataggelies-ths-mpotsh/amp
Noindex: /lifestyle/media/530748/stamatopoylos-nea-stoixeia-gia-tis-kataggelies-ths-mpotsh/amp

Disallow: /eidiseis/ellada/591715/dhmhtrhs-lignadhs-enoxos-mono-gia-2-biasmoys
Noindex: /eidiseis/ellada/591715/dhmhtrhs-lignadhs-enoxos-mono-gia-2-biasmoys

Disallow: /eidiseis/ellada/591715/dhmhtrhs-lignadhs-enoxos-mono-gia-2-biasmoys/amp
Noindex: /eidiseis/ellada/591715/dhmhtrhs-lignadhs-enoxos-mono-gia-2-biasmoys/amp

Sitemap: https://www.star.gr/sitemaps/google-news.xml
Sitemap: https://www.star.gr/sitemaps/articles/articles.xml
Sitemap: https://www.star.gr/sitemaps/tags/tags.xml
Sitemap: https://www.star.gr/sitemaps/videos/videos.xml
Sitemap: https://www.star.gr/sitemaps/categories.xml
Sitemap: https://www.star.gr/sitemaps/sections.xml
