User-agent: SemrushBot
Disallow: /

User-agent: SemrushBot-SA
Disallow: /

User-agent: *
Disallow: */tag/*
Disallow: */tag/*?page=*
Disallow: /admin/*

Sitemap: https://sud.ua/google_news_sitemap/sitemap.news_google.xml
Sitemap: https://sud.ua/google_news_sitemap/sitemap.news_google_ru.xml

Sitemap: https://sud.ua/sitemap.news_0_uk.xml
Sitemap: https://sud.ua/sitemap.news_0.xml
Sitemap: https://sud.ua/sitemap.news_1.xml
Sitemap: https://sud.ua/sitemap.news_2.xml
Sitemap: https://sud.ua/sitemap.news_3.xml
Sitemap: https://sud.ua/sitemap.news_4.xml
Sitemap: https://sud.ua/sitemap.news_5.xml
Sitemap: https://sud.ua/sitemap.news_6.xml

Sitemap: https://sud.ua/sitemap.news_7.xml
Sitemap: https://sud.ua/sitemap.news_8.xml

Sitemap https://sud.ua/sitemap.news_1_uk.xml
Sitemap https://sud.ua/sitemap.news_2_uk.xml

Sitemap https://sud.ua/sitemap.tags_and_other.xml
