User-agent: *

Disallow: /lp/box/catalog_2015.pdf
Disallow: /*?*
Disallow: *marketer*
Disallow: /*utm_keyword*
Disallow: *arc_year*
Disallow: /*yagla*
Disallow: /*escaped_fragment*
Disallow: /*base/search*
Disallow: /base/account/
Disallow: /*biznes_obrazovanie_test*
Disallow: /*education-form*
Disallow: /*lands*
Disallow: /en/
Disallow: */in_synergy
Disallow: /lander/
Disallow: /manager/
Disallow: *redir-setuniq=*
Disallow: /sbs-*
Disallow: /connectors/
Disallow: /ajax_footer
Disallow: /about/distance
Disallow: /about/faculties_old/
Disallow: */blog/
Disallow: /giver
Disallow: /job/eksport_vakansij
Disallow: /about/istoriya/2013/
Disallow: /assets/components/minishop2/action.php
Disallow: /assets/template/svg/
Disallow: /aspir/general/upload/new/*
Disallow: /about/partners
Disallow: *field-of-study*
Disallow: /search
Disallow: *~~*
Disallow: *rsd=*
Disallow: *testyi*
Disallow: *attachment_id*
Disallow: *timetable*
Disallow: /students/library/links
Disallow: /lp/insight
Disallow: /lp/mirrors*
Disallow: /press/gallery/album*
Disallow: /in_synergy*
Disallow: /pwa/
Disallow: *sa=X*
Disallow: *type-of-program*
Disallow: *nsukey*
Disallow: *graccount*
Disallow: *h1=*
Disallow: *level=*
Disallow: *name=*
Disallow: *lp/new/*
Disallow: *Bamp*
Disallow: *date=autodate*
Disallow: *token=*
Disallow: *forgot_password*
Disallow: *result=*
Disallow: *click_id*
Disallow: *mergelead*
Disallow: *caption*
Disallow: /about/education_articles/video/*
Disallow: /lp/_chunk/
Disallow: /new/
Disallow: /official_documents
Disallow: /schedule
Disallow: *.docx
Disallow: *.xlsx
Disallow: /export_teachers
Disallow: *.doc
Disallow: *.DOC
Disallow: *.xls
Disallow: *.XLS
Disallow: *.ppt
Disallow: *.PPT
Disallow: */gallery/*
Disallow: */thanks/
Disallow: */result/
Disallow: /promo/
Disallow: */success
Disallow: /students/pay_education/success
Allow: /press/blog/
Allow: /about/blog/
Allow: *.jpeg
Allow: *.png
Allow: /about/education_articles/?page=*
Allow: /about/education_articles/ege/?page=*
Allow: /about/education_articles/kolledzh/?page=*
Allow: /about/education_articles/vyishka/?page=*
Allow: /about/education_articles/speczialitet?page=*
Allow: /about/education_articles/vtoroe_vyisshee/?page=*
Allow: /about/education_articles/aspirantura?page=*
Allow: /about/education_articles/zaochnoe_obrazovanie/?page=*
Allow: /about/education_articles/distanczionnoe_obrazovanie/?page=*
Allow: /about/education_articles/magistratura/?page=*
Allow: /about/education_articles/speczialnosti/?page=*
Allow: /about/education_articles/speczialnosti/obrazovanie_po_fakultetam/?page=*
Allow: /about/education_articles/kursyi/?page=*
Allow: /about/education_articles/pomoshh/?page=*
Allow: /about/education_articles/pomoshh/studentam/?page=*
Allow: /about/education_articles/pomoshh/abiturientam/?page=*
Allow: /about/education_articles/student_i_armiya/?page=*
Allow: /about/education_articles/mediczina/?page=*
Allow: /about/education_articles/student_i_armiya/?page=*
Allow: /about/education_articles/raznoe/?page=*
Allow: /about/education_articles/raznoe/dopolnitelnoe_obrazovanie?page=*
Allow: /about/education_articles/raznoe/pro_perevod?page=*
Allow: /about/education_articles/raznoe/vechernee_obrazovanie?page=*
Allow: /about/education_articles/raznoe/perepodgotovka/?page=*
Allow: /about/education_articles/raznoe/kod_budushhego/?page=*
Allow: /about/education_articles/raznoe/novosti_obrazovaniya/?page=*
Allow: /about/education_articles/video/?page=*
Allow: /edu/news/ege?ege-page=*
Allow: /edu/news/oge?oge-page=*
Allow: /rss_ya_academy.rss
Allow: /rss_ya_edu_1.rss
Allow: /rss_ya_edu_2.rss


Sitemap: https://synergy.ru/sitemap.xml