# Robots.txt file for www.taniaksiazka.pl, taniaksiazka.pl

User-Agent: *
Disallow: /admin/
Disallow: /physio/
Disallow: /phsync/
Disallow: /cache/
Disallow: /tmp/
Disallow: /includes/
Disallow: /address_book_process.php
Disallow: /account.php
Disallow: /account_edit.php
Disallow: /account_edit_process.php
Disallow: /account_history.php
Disallow: /account_history_info.php
Disallow: /address_book.php
Disallow: /advanced_search.php
Disallow: /advanced_search_result.php
Disallow: /checkout.php
Disallow: /checkout_address.php
Disallow: /checkout_confirmation.php
Disallow: /checkout_payment.php
Disallow: /checkout_process.php
Disallow: /checkout_success.php
Disallow: /contact_us.php
Disallow: /cookie_usage.php
Disallow: /create_account.php
Disallow: /create_account_process.php
Disallow: /create_account_success.php
Disallow: /login.php
Disallow: /logoff.php
Disallow: /password_forgotten.php
Disallow: /popup_search_help.php
Disallow: /shopping_cart.php
Disallow: /tell_a_friend.php
Disallow: /redirect.php
Disallow: /product_tags.php
Disallow: /DaneAdresowe
Disallow: /Podsumowanie
Disallow: /Success
Disallow: /Wyloguj
Disallow: /Konto
Disallow: /HistoriaZamowien
Disallow: /KsiazkaAdresowa
Disallow: /WarunkiZakupow/Artykul-Regulamin
Disallow: /polityka-prywatnosci-a-332.html
Disallow: /Szukaj/*
Disallow: /*?Theme=
Disallow: /*/Ilosc-
Disallow: /inpost/v1/izi/render/button
Disallow: /InfoUrl.php/
Disallow: /*/mode-produktywmagazynie/
Disallow: /AddToCart/*
Disallow: /Schowek/*
Disallow: /*?params*=*
Disallow: /revive/* 
Disallow: /Koszyk
Disallow: /blog/wp-content/uploads/
Disallow: /blog/wp-admin/
Disallow: /blog/wp-login.php
Disallow: /blog/wp-includes/
Disallow: /blog/wp-content/plugins/
Disallow: /ProductVariants/
Disallow: /s/Sent* 
Disallow: /s/?q=
Disallow: /s/*/Sent*
Disallow: /Szukaj/Sent*
Disallow: /SearchParamsAjax/ 
Disallow: /AjaxAutocomplete/
Disallow: /inpost/

Disallow: /panel-*

Sitemap: https://www.taniaksiazka.pl/sitemap_sitemap.xml

User-agent: GPTBot
Allow: /
User-agent: CCBot
Allow: /
User-agent: ClaudeBot
Allow: /
User-agent: PerplexityBot
Allow: /
User-agent: Google-Extended
Allow: /
User-Agent: .*Twiceler.*
Disallow: /
User-Agent: .*trovitBot.*
Disallow: /
User-Agent: .*AhrefsBot.*
Disallow: /
User-Agent: .*VoilaBot BETA 1.2.*
Disallow: /
User-Agent: .*libwww-perl/5.805.*
Disallow: /
User-Agent: .*Java/1.5.0_11.*
Disallow: /
User-Agent: .*Sogou web spider/3.0.*
Disallow: /
User-Agent: .*psbot.*
Disallow: /
User-Agent: .*Exabot.*
Disallow: /
User-Agent: .*Charlotte/1.0b.*
Disallow: /
User-Agent: .*boitho.com-dc.*
Disallow: /
User-Agent: .*ajSitemap.*
Disallow: /
User-Agent: .*bot/1.0.*
Disallow: /
User-Agent: .*panscient.com.*
Disallow: /
User-Agent: .*Java/1.6.0_11.*
Disallow: /
User-Agent: .*WebDataCentreBot/1.0.*
Disallow: /
User-Agent: .*Java.*
Disallow: /
User-Agent: .*SapphireWebCrawler.*
Disallow: /
User-Agent: .*Yandex.*
Disallow: /
User-Agent: .*Baiduspider.*
Disallow: /
User-Agent: .*Rankivabot.*
Disallow: /
User-Agent: .*DBLBot/1.0.*
Disallow: /
User-Agent: "^Black Hole"
Disallow: /
User-Agent: "^Titan"
Disallow: /
User-Agent: "^WebStripper"
Disallow: /  
User-Agent: "^NetMechanic"
Disallow: /
User-Agent: "^CherryPicker"
Disallow: /
User-Agent: "^EmailCollector"
Disallow: /
User-Agent: "^EmailSiphon"
Disallow: /  
User-Agent: "^WebBandit"
Disallow: /
User-Agent: "^EmailWolf"
Disallow: /
User-Agent: "^ExtractorPro"
Disallow: /  
User-Agent: "^CopyRightCheck"
Disallow: /
User-Agent: "^Crescent"
Disallow: /
User-Agent: "^Wget"
Disallow: /  
User-Agent: "^SiteSnagger"
Disallow: /
User-Agent: "^ProWebWalker"
Disallow: /
User-Agent: "^CheeseBot"
Disallow: /  
User-Agent: "^Teleport"
Disallow: /
User-Agent: "^TeleportPro"
Disallow: /
User-Agent: "^MIIxpc"
Disallow: /  
User-Agent: "^Telesoft"
Disallow: /
User-Agent: "^Website Quester"
Disallow: /
User-Agent: "^WebZip"
Disallow: /  
User-Agent: "^moget/2.1"
Disallow: /
User-Agent: "^WebZip/4.0"
Disallow: /
User-Agent: "^WebSauger"
Disallow: /  
User-Agent: "^WebCopier"
Disallow: /
User-Agent: "^NetAnts"
Disallow: /
User-Agent: "^Mister PiX"
Disallow: /  
User-Agent: "^WebAuto"
Disallow: /
User-Agent: "^TheNomad"
Disallow: /
User-Agent: "^WWW-Collector-E"
Disallow: /  
User-Agent: "^RMA"
Disallow: /
User-Agent: "^libWeb/clsHTTP"
Disallow: /
User-Agent: "^asterias"
Disallow: /  
User-Agent: "^httplib"
Disallow: /
User-Agent: "^turingos"
Disallow: /
User-Agent: "^spanner"
Disallow: /  
User-Agent: "^InfoNaviRobot"
Disallow: /
User-Agent: "^Harvest/1.5"
Disallow: /
User-Agent: "^Bullseye/1.0"
Disallow: /  
User-Agent: "^Mozilla/4.0 (compatible; BullsEye;   Windows 95)"
Disallow: /
User-Agent: "^Crescent Internet ToolPak   HTTP OLE Control v.1.0"
Disallow: /
User-Agent: "^CherryPickerSE/1.0"
Disallow: /
User-Agent: "^CherryPicker /1.0"
Disallow: /  
User-Agent: "^WebBandit/3.50"
Disallow: /
User-Agent: "^NICErsPRO"
Disallow: /
User-Agent: "^Microsoft URL   Control - 5.01.4511"
Disallow: /
User-Agent: "^DittoSpyder"
Disallow: /
User-Agent: "^Foobot"
Disallow: /
User-Agent: "^WebmasterWorldForumBot"
Disallow: /
User-Agent: "^SpankBot"
Disallow: /
User-Agent: "^BotALot"
Disallow: /  
User-Agent: "^lwp-trivial/1.34"
Disallow: /  
User-Agent: "^lwp-trivial"
Disallow: /
User-Agent: "^Wget/1.6"
Disallow: /
User-Agent: "^BunnySlippers"
Disallow: /  
User-Agent: "^Microsoft URL Control - 6.00.8169"
Disallow: /  
User-Agent: "^URLy Warning"
Disallow: /
User-Agent: "^Wget/1.5.3"
Disallow: /
User-Agent: "^LinkWalker"
Disallow: /  
User-Agent: "^cosmos"
Disallow: /
User-Agent: "^moget"
Disallow: /
User-Agent: "^hloader"
Disallow: /  
User-Agent: "^humanlinks"
Disallow: /
User-Agent: "^LinkextractorPro"
Disallow: /
User-Agent: "^Offline   Explorer"
Disallow: /
User-Agent: "^Mata Hari"
Disallow: /  
User-Agent: "^LexiBot"
Disallow: /
User-Agent: "^Web Image Collector"
Disallow: /
User-Agent: "^The   Intraformant"
Disallow: /
User-Agent: "^True_Robot/1.0"
Disallow: /  
User-Agent: "^True_Robot"
Disallow: /
User-Agent: "^BlowFish/1.0"
Disallow: /
User-Agent: "^JennyBot"
Disallow: /  
User-Agent: "^MIIxpc/4.2"
Disallow: /
User-Agent: "^BuiltBotTough"
Disallow: /
User-Agent: "^ProPowerBot/2.14"
Disallow: /
User-Agent: "^BackDoorBot/1.0"
Disallow: /  
User-Agent: "^toCrawl/UrlDispatcher"
Disallow: /  
User-Agent: "^WebEnhancer"
Disallow: /
User-Agent: "^TightTwatBot"
Disallow: /
User-Agent: "^suzuran"
Disallow: /  
User-Agent: "^VCI WebViewer VCI WebViewer Win32"
Disallow: /  
User-Agent: "^VCI"
Disallow: /
User-Agent: "^Szukacz/1.4"
Disallow: /
User-Agent: "^QueryN Metasearch"
Disallow: /  
User-Agent: "^Openfind data gathere"
Disallow: /  
User-Agent: "^Openfind"
Disallow: /
User-Agent: "^Xenu's Link Sleuth 1.1c"
Disallow: /
User-Agent: "^Xenu's"
Disallow: /
User-Agent: "^Zeus"
Disallow: /
User-Agent: "^RepoMonkey Bait & Tackle/v1.01"
Disallow: /
User-Agent: "^RepoMonkey"
Disallow: /
User-Agent: "^Zeus 32297   Webster Pro V2.9 Win32"
Disallow: /
User-Agent: "^Webster Pro"
Disallow: /  
User-Agent: "^EroCrawler"
Disallow: /
User-Agent: "^LinkScan/8.1a Unix"
Disallow: /
User-Agent: "^Keyword   Density/0.9"
Disallow: /
User-Agent: "^Kenjin Spider"
Disallow: /  
User-Agent: "^Cegbfeieh"
Disallow: /
User-agent: facebookexternalhit
Allow: /