User-agent: *
Disallow: /files10/
Disallow: /files20/
Disallow: /sfiles/
Disallow: /unsecure/
Disallow: /files40/
Disallow: /tlanding/
Disallow: /edit/
Disallow: /settings/
Disallow: /user_topics/
Disallow: /fresh/password/
Disallow: /public/inbox/
Host: https://trashbox.ru
Sitemap: https://trashbox.ru/sitemap.xml
Sitemap: https://trashbox.ru/sitemap_news.xml
Clean-param: _gl&_ga&edit_topic&amp_lite&sort&author
