User-Agent: *
Disallow: /sess/
Disallow: /shared/
Disallow: /prasa/
Disallow: /zamowienia_publiczne/files
Disallow: /wyszukiwarka
Disallow: /regulamin
Disallow: /tvp-world/
Allow: /
Sitemap: https://www.tvp.pl/shared/feed/google_news.php
Sitemap: https://www.tvp.pl/sitemap
Sitemap: https://www.tvp.pl/sitemap-full_index.xml