User-agent: *
Disallow: /*?*
Disallow: /*&*
Disallow: */amp/*
Disallow: */redirect/*
Disallow: /offer/
Disallow: /*/*/*/*
Disallow: /old/
Disallow: /old-site/
Disallow: /new/
Disallow: */partners/office/
Disallow: /?key=
Disallow: /qrequest_iframe/demo/
Disallow: /_ad_min_24/
Disallow: /advertiser_office/
Disallow: /lk/
Disallow: /tinymce/
Disallow: /get_activity_type_list/
Disallow: /mfi_iframe_v101/
Disallow: /mfi_iframe_v102/
Disallow: /lp_partners_advertisers/
Disallow: /consumer-loans/
Disallow: /partners2
Disallow: /partners1
Disallow: /authors/test
Disallow: */null/*
Disallow: /l/*
Disallow: */api/v1/payment_table
Disallow: /mfi_iframe_v101
Disallow: /mfi_iframe_v102
Disallow: /ref_v1
Disallow: /ref_v2
Disallow: /ref_cancel_subscription/
Disallow: /*/*.woff2
Disallow: */rezajmy/*
Disallow: */recredit/*
Disallow: */reipoteka/*
Disallow: */recreditcard/*
Disallow: */redebitcard/*
Disallow: */reavtocredit/*
Disallow: */rerefinance/*
Disallow: */remsb/*
Disallow: /kurs/*
Disallow: /*page=2*
Allow: *?page=*
Disallow: /banki/330-moskovskij-kreditnyij-bank
Disallow: /banki/332-promsvyazbank
Disallow: /banki/332-promsvyazbank/kreditnye-karty/karta-dvojnoj-keshbehk
Disallow: /banki/346-rosbank
Disallow: /banki/346-rosbank/kreditnye-karty/karta-visa-mozhnovsyo
Disallow: /banki/48-tinkoff/debetovye-karty/karta-tinkoff-black-rik-i-morti
Disallow: /banki/48-tinkoff/debetovye-karty/tinkoff-black-ex/debetovaya-karta-tinkoff-black-obzor
Disallow: /banki/48-tinkoff/kreditnye-karty
Disallow: /banki/48-tinkoff/kreditnye-karty/card-tinkoff-drive
Disallow: /banki/48-tinkoff/kreditnye-karty/karta-yandeks-pro-ot-tinkoff-banka
Disallow: /banki/563-mts-bank/kreditnye-karty/karta-mts-dengi-weekend
Disallow: /banki/563-mts-bank/kreditnye-karty/karta-mts-dengi-zero
Disallow: /banki/563-mts-bank/kreditnye-karty/karta-universalnaya-mts-cashback
Disallow: /banki/563-mts-bank/kreditnye-karty/mts-bank-kreditnye-karty
Disallow: /banki/563-mts-bank/kredity/mts-kredit-nalichnymi
Disallow: /banki/563-mts-bank/refinance/refinansirovanie-kredita-v-mts-banke
Disallow: /banki/597-russkij-standart
Disallow: /banki/65-sovkombank/avtokredity/sovkombank-avtokredit1kredit-na-avtomobili-s-probegom
Disallow: /banki/65-sovkombank/kreditnye-karty
Disallow: /banki/65-sovkombank/kredity/media/open/6/7/83/783023f449dda53882420110bfb89fea.png
Disallow: /banki/65-sovkombank/kredity/media/open/7/2/fd/2fd63b09cce101300d20a8242481d3af.png
Disallow: /banki/ak-bars-bank/kreditnye-karty/kreditnaya-karta-115-dnej
Disallow: /banki/alfa-bank/debetovye-karty
Disallow: /banki/alfa-bank/debetovye-karty/alfa-karta-s-preimushchestvami
Disallow: /banki/alfa-bank/debetovye-karty/karta-aeroflot-world
Disallow: /banki/alfa-bank/debetovye-karty/karta-pyatyorochka
Disallow: /banki/alfa-bank/ipoteka
Disallow: /banki/alfa-bank/kreditnye-karty
Disallow: /banki/alfa-bank/kreditnye-karty/karta-100-dnej-bez-procentov_alph
Disallow: /banki/alfa-bank/kreditnye-karty/karta-365-dnej-bez-procentov_alph/obzor
Disallow: /banki/alfa-bank/kreditnye-karty/karta-aeroflot-bonus-platinum
Disallow: /banki/alfa-bank/kredity/media/open/7/2/fd/2fd63b09cce101300d20a8242481d3af.png
Disallow: /banki/aziatsko-tihookeanskij-bank
Disallow: /banki/aziatsko-tihookeanskij-bank/debetovye-karty/karta-kehshbehk-mastercard
Disallow: /banki/bank-fk-otkryitie
Disallow: /banki/bank-fk-otkryitie/debetovye-karty/karta-opencard-mir
Disallow: /banki/bank-fk-otkryitie/kreditnye-karty/karta-vse-chto-nado
Disallow: /banki/bank-vostochnyij-ekspress
Disallow: /banki/bank-zenit/kreditnye-karty
Disallow: /banki/bank-zenit/kreditnye-karty/media/open/0/4/f4/4f41c2c7c3c640aad60f1087fb26c6f3.webp
Disallow: /banki/bank-zenit/kreditnye-karty/media/open/0/6/df/6df3ba5b362a8b05fe78e4dc0ff6d994.webp
Disallow: /banki/bank-zenit/kreditnye-karty/media/open/7/e/e7/ee7940a99a506ff9e1f1af7c9687ce9c.webp
Disallow: /banki/bks-investitsionnyij-bank
Disallow: /banki/gazprombank/debetovye-karty/umnaya-karta-visa-gold-s-keshbehkom-ili-milyami
Disallow: /banki/gazprombank/kreditnye-karty/gazprombank-kreditnaya-karta-udobnaya-karta
Disallow: /banki/gazprombank/kreditnye-karty/karta-avtodrajv-platinum-credit
Disallow: /banki/gazprombank/kredity/gpb-kredit-nalichnymi
Disallow: /banki/houm-kredit/debetovye-karty/karta-polza
Disallow: /banki/houm-kredit/debetovye-karty/karta-polza-old/debetovaya-karta-polza-obzor
Disallow: /banki/houm-kredit/kreditnye-karty
Disallow: /banki/houm-kredit/kreditnye-karty/karta-rassrochki-svobodaa
Disallow: /banki/houm-kredit/kreditnye-karty/kreditnaya-karta-polza-ot-houm-kredit-banka
Disallow: /banki/houm-kredit/kredity
Disallow: /banki/houm-kredit/kredity/hcfb-kredit-nalichnymi
Disallow: /banki/houm-kredit/kredity/houm-kredit-bank-kredit-nalichnymi
Disallow: /banki/kredit-evropa-bank/kreditnye-karty/kredit-europa-bank-kreditnaya-karta-credit-card-plus
Disallow: /banki/kredit-evropa-bank/kreditnye-karty/kredit-evropa-bank-kreditnaya-karta-urban-
Disallow: /banki/kuban-kredit
Disallow: /banki/loko-bank
Disallow: /banki/loko-bank/kreditnye-karty/loko-bank-kreditnaya-karta-lokojam
Disallow: /banki/oao-sberbank/avtokredity
Disallow: /banki/oao-sberbank/debetovye-karty
Disallow: /banki/oao-sberbank/debetovye-karty/karta-molodezhnaya-s-dizajnom-na-vybor-visa-classic
Disallow: /banki/oao-sberbank/debetovye-karty/karta-molodyozhnaya-mastercard-standard11
Disallow: /banki/oao-sberbank/debetovye-karty/karta-sberkarta-mastercard-standard
Disallow: /banki/oao-sberbank/debetovye-karty/karta-sberkids
Disallow: /banki/oao-sberbank/ipoteka
Disallow: /banki/oao-sberbank/kredity
Disallow: /banki/pochta-bank/kredity/pochta-kredit-nalichnymi
Disallow: /banki/rajffajzenbank
Disallow: /banki/rajffajzenbank/debetovye-karty/karta-cashback
Disallow: /banki/rajffajzenbank/kreditnye-karty/rajffajzen-bank-kreditnaya-karta-110-dney
Disallow: /banki/rajffajzenbank/kreditnye-karty/rajffajzen-bank-kreditnaya-karta-110-dney/obzor-kreditnoj-karty-rajffajzenbank-110-dnej
Disallow: /banki/rosgosstrakh
Disallow: /banki/rosgosstrakh/kreditnye-karty/rgs-bank-kreditnaya-karta-dorozhnaya
Disallow: /banki/rosselhozbank
Disallow: /banki/uralsib/kreditnye-karty/media/open/0/4/f4/4f41c2c7c3c640aad60f1087fb26c6f3.webp
Disallow: /banki/uralsib/kreditnye-karty/media/open/0/6/df/6df3ba5b362a8b05fe78e4dc0ff6d994.webp
Disallow: /banki/vtb/debetovye-karty/karta-multikarta-vtb
Disallow: /banki/vtb/kreditnye-karty
Disallow: /banki/vtb/kreditnye-karty/karta-vozmozhnostej
Disallow: /banki/vtb/kredity/vtb-kredit-nalichnyimii
Disallow: /banki/yunikredit
Disallow: /banki/yunikredit/debetovye-karty/yunikredit-bank-debetovaya-avtokarta
Disallow: /media/open/1/6/de/6de34fa44bd251c46175f9617e303b22.png 
Disallow: /mfo/150-zajmer/mikrozajmy
Disallow: /mfo/234-kredito24/mikrozajmy/media/open/0/3/73/373c76ba3fcfb8c852963c392e0f61e9.png
Disallow: /mfo/234-kredito24/mikrozajmy/media/open/0/3/84/3844d176b319a602cdef86ff466a27fd.jpg
Disallow: /mfo/234-kredito24/mikrozajmy/media/open/1/5/35/535eaa544c55ca5ec1cd7df25296b834.png
Disallow: /mfo/234-kredito24/mikrozajmy/media/open/1/5/58/558777702dacf786c5313a6e25cdc254.png
Disallow: /mfo/234-kredito24/mikrozajmy/media/open/1/e/57/e57c558488233bd2f36c22ea91c9fba1.png
Disallow: /mfo/234-kredito24/mikrozajmy/media/open/3/2/b3/2b3a1b570c2abac48f7d72309fc07338.jpg
Disallow: /mfo/234-kredito24/mikrozajmy/media/open/3/4/f7/4f701715ee9a97e84711e83891db69e4.png
Disallow: /mfo/234-kredito24/mikrozajmy/media/open/5/e/e8/ee8b671df615f4e663a74b95890d20da.png
Disallow: /mfo/234-kredito24/mikrozajmy/media/open/6/6/7d/67d4c07e4cef9ee3461fb637d8283f16.png
Disallow: /mfo/234-kredito24/mikrozajmy/media/open/6/a/b4/ab47bf872cb64d710554b8384153ef07.png
Disallow: /mfo/234-kredito24/mikrozajmy/media/open/7/0/f5/0f550b8e63f865e84e6b3997a25dcd3e.png
Disallow: /mfo/234-kredito24/mikrozajmy/media/open/7/d/84/d84872cb010697efa7c14f6328d97fc0.png
Disallow: /mfo/44-viva-dengi/mikrozajmy/viva-dengi-Copy-2005094
Disallow: /mfo/61-dengi-srazu/mikrozajmy/media/open/0/3/73/373c76ba3fcfb8c852963c392e0f61e9.png
Disallow: /mfo/61-dengi-srazu/mikrozajmy/media/open/0/3/84/3844d176b319a602cdef86ff466a27fd.jpg
Disallow: /mfo/61-dengi-srazu/mikrozajmy/media/open/1/5/35/535eaa544c55ca5ec1cd7df25296b834.png
Disallow: /mfo/61-dengi-srazu/mikrozajmy/media/open/1/5/58/558777702dacf786c5313a6e25cdc254.png
Disallow: /mfo/61-dengi-srazu/mikrozajmy/media/open/1/e/57/e57c558488233bd2f36c22ea91c9fba1.png
Disallow: /mfo/61-dengi-srazu/mikrozajmy/media/open/3/2/b3/2b3a1b570c2abac48f7d72309fc07338.jpg
Disallow: /mfo/61-dengi-srazu/mikrozajmy/media/open/6/6/7d/67d4c07e4cef9ee3461fb637d8283f16.png
Disallow: /mfo/61-dengi-srazu/mikrozajmy/media/open/7/0/f5/0f550b8e63f865e84e6b3997a25dcd3e.png
Disallow: /mfo/61-dengi-srazu/mikrozajmy/media/open/7/d/84/d84872cb010697efa7c14f6328d97fc0.png
Disallow: /mfo/9-chestnoe-slovo/mikrozajmy/dengi-v-chestnoe-slovo
Disallow: /mfo/boostra/mikrozajmy/boostra-Copy-2005151
Disallow: /mfo/bunny-money/mikrozajmy/bunny-money
Disallow: /mfo/cashiro/mikrozajmy/cashiro
Disallow: /mfo/Fin5/mikrozajmy/fin5
Disallow: /mfo/kekas/mikrozajmy/kekasru
Disallow: /mfo/skelamoney/mikrozajmy
Disallow: /mfo/skelamoney/mikrozajmy/media/open/0/3/73/373c76ba3fcfb8c852963c392e0f61e9.png
Disallow: /mfo/skelamoney/mikrozajmy/media/open/6/6/7d/67d4c07e4cef9ee3461fb637d8283f16.png
Disallow: /mfo/smsfinans/mikrozajmy
Disallow: /mfo/zaimrub/mikrozajmy/media/open/0/3/73/373c76ba3fcfb8c852963c392e0f61e9.png
Disallow: /mfo/zaimrub/mikrozajmy/media/open/1/5/35/535eaa544c55ca5ec1cd7df25296b834.png
Disallow: /mfo/zaimrub/mikrozajmy/media/open/1/5/58/558777702dacf786c5313a6e25cdc254.png
Disallow: /mfo/zaimrub/mikrozajmy/media/open/3/2/b3/2b3a1b570c2abac48f7d72309fc07338.jpg
Disallow: /mfo/zaimrub/mikrozajmy/media/open/6/6/7d/67d4c07e4cef9ee3461fb637d8283f16.png
Disallow: /mfo/zaimrub/mikrozajmy/media/open/7/d/84/d84872cb010697efa7c14f6328d97fc0.png
Disallow: /mfo/zanimatelnye-finansy/mikrozajmy/zanimatelnie-finansy
Disallow: /offer/redirect/12e8i7k56hth/?sub_id=
Disallow: /offer/redirect/1udyd53zp04ue/?sub_id=
Disallow: /offer/redirect/21ip1ywy6x3x0/?source_type=4&finmarket_position=1&split_tests=money_immediately,without_button_money_immediately
Disallow: /offer/redirect/23zj5v8zg0z3f/?sub_id=
Disallow: /offer/redirect/2nnh0mm33kxgr/?sub_id=
Disallow: /offer/redirect/2vlyhkg6oj6pg/?source_type=4&finmarket_position=15&split_tests=money_immediately,without_button_money_immediately
Disallow: /offer/redirect/3va1zx3ppvc34/?sub_id=
Disallow: /offer/redirect/4xfqi056hfoe/?source_type=4&finmarket_position=22&split_tests=money_immediately,without_button_money_immediately
Disallow: /offer/redirect/c7kteejygmse/?sub_id=
Disallow: /private/avtokredity/na-novyj-avtomobi
Disallow: /private/kreditnye-karty/momentalnye/moskva
Disallow: /private/mikrozajmy/bez-kreditnoj-istorii/sankt-peterburg
Disallow: /private/mikrozajmy/moskva
Disallow: /private/mikrozajmy/na-kartu-bez-proverki-kreditnoj-istorii
Disallow: /services/bankrotstvo
Disallow: /services/credit-calculator/kreditnye-karty
Disallow: /services/fraud-monitoring
Disallow: /services/polnaya-kreditnaya-istoriya
Disallow: /services/rejting-finansovogo-zdorovya
Sitemap: https://unicom24.ru/sitemap.xml

Clean-param: utm_campaign&utm_medium&utm_source&utm_content&utm_term&gclid&utm_placement&loan_period&loan_rate&loan_sum&receipt_types&page&partner&sub_id1&sub_id2&sub_id3&sub_id4&yclid&key&gb&term&rate&sum&loan_type&mfi_id&reviews_rating&first_loan_without_percents&prolongation_possibility&is_pledge&deferred_payment&period&property_type_ids&in_top&last_job_experience&benefit_period&max_service_auto&have_remaining_percent&have_cashback&insurance&invi&convert&page


User-agent: LinkpadBot
Disallow: /

User-agent: SemrushBot
Disallow: /