User-agent: *
Allow: /
Disallow: /search
Disallow: *?date=*

Sitemap: https://unn.ua/sitemap/uk-google-news.xml
Sitemap: https://unn.ua/sitemap/en-google-news.xml
Sitemap: https://unn.ua/sitemap/ru-google-news.xml
Sitemap: https://unn.ua/sitemap/uk-categories.xml
Sitemap: https://unn.ua/sitemap/en-categories.xml
Sitemap: https://unn.ua/sitemap/ru-categories.xml
Sitemap: https://unn.ua/sitemap/uk-tags.xml
Sitemap: https://unn.ua/sitemap/en-tags.xml
Sitemap: https://unn.ua/sitemap/ru-tags.xml