User-Agent: *
Crawl-delay: 10
Disallow: /auth/
Disallow: /astma/
Disallow: /personal/
Disallow: /personal/cart/
Disallow: /upload/
Disallow: /search/
Disallow: /cron/
Disallow: /include/
Disallow: /login/
Disallow: /*/search/
Disallow: /*/slide_show/
Disallow: /*/gallery/*order=*
Disallow: /*?print=
Disallow: /*&print=
Disallow: /*register=
Disallow: /*forgot_password=
Disallow: /*change_password=
Disallow: /*login=
Disallow: /*/?login=*
Disallow: /*logout=
Disallow: /*/?logout=*
Disallow: /*auth=
Disallow: /*?action=
Disallow: /*action=ADD_TO_COMPARE_LIST
Disallow: /*action=DELETE_FROM_COMPARE_LIST
Disallow: /*action=ADD2BASKET
Disallow: /*action=BUY
Disallow: /*backurl=*
Disallow: /*BACKURL=*
Disallow: /*back_url=*
Disallow: /*BACK_URL=*
Disallow: /*back_url_admin=*
Disallow: /*print_course=Y
Disallow: /*COURSE_ID=
Disallow: /*?COURSE_ID=
Disallow: /*PAGE_NAME=user_post
Disallow: /*PAGE_NAME=detail_slide_show
Disallow: /*PAGE_NAME=search
Disallow: /*PAGEN_1=
Disallow: /*SHOWALL
Disallow: /*show_all=
Disallow: /*/?search=*
Disallow: /*/?view=*
Disallow: /*/?sort=*
Disallow: *link_n.php*
Disallow: /bonus/
Disallow: /catalog/lekarstva-i-bady/zheludochno-kishechnye-preparaty/50/
Disallow: /catalog/lekarstva-i-bady/zdorovoe-pitanie-/5/
Disallow: /catalog/dlya-krasoty-i-gigieny/ukhod-za-litsom-2446/4/
Disallow: /catalog/lekarstva-i-bady/zdorovye-veny-gemorroy/oblepikhovoe-maslo-suppoz-rekt-0-5g-1065750/
Disallow: /catalog/lekarstva-i-bady/lekarstva-pri-infektsionnykh-zabolevaniyakh/plakvenil-tab-p-o-200mg-6017162/
Disallow: /catalog/dlya-krasoty-i-gigieny/ukhod-za-litsom-2446/15/
Disallow: /catalog/sistema-infuzion-dlya-pereliv-rastvorov-odnokrat-prim-122375/
Disallow: /catalog/intimnye-tovary-3267/sredstva-dlya-lecheniya-molochnitsy/flukonazol-kaps-0-15g-1148444/
Disallow: /catalog/lekarstva-i-bady/obezbolivayushchie/10/
Disallow: /catalog/lekarstva-i-bady/muzhskoe-zdorove/prostamol-uno-kaps-320mg-60156537/
Disallow: /catalog/lekarstva-i-bady/lekarstva-dlya-lecheniya-pochek/lekarstva-pri-vospalitelnykh-zabolevaniyakh-pochek-i-mochevyvodyashchikh-putey/protsistal-kaps-0-36-30-bad145281/
Disallow: /catalog/lekarstva-i-bady/lekarstva-dlya-lecheniya-pochek/protsistal-kaps-0-36-30-bad145281/
Disallow: /catalog/intimnye-tovary-3267/dlya-povysheniya-potentsii/viagra-tab-p-ob-100mg-17244/
Disallow: /catalog/intimnye-tovary-3267/dlya-povysheniya-potentsii/viagra-tab-p-ob-100mg-1153748/
Disallow: /catalog/lekarstva-i-bady/preparaty-dlya-sistemnogo-vozdeystviya/kaltsiya-khlorid-r-r-d-inekts-v-v-10-10ml-10-amp-154246/
Disallow: /catalog/lekarstva-i-bady/preparaty-dlya-sistemnogo-vozdeystviya/kaltsiya-khlorid-r-r-d-inekts-v-v-10-10ml-10-amp-418/
Disallow: /catalog/lekarstva-i-bady/zhenskoe-zdorove/metiluratsil-suppoz-rekt-0-5g-10/
Disallow: /catalog/lekarstva-i-bady/zhenskoe-zdorove/metiluratsil-suppoz-rekt-0-5g-1088735/
Disallow: /catalog/mama-i-malysh/kosmetika-dlya-beremennykh-i-kormyashchikh-mam/9-mesyatsev-krem-d-profilaktiki-i-korrektsii-rastyazhek-150ml106283/
Disallow: /catalog/mama-i-malysh/kosmetika-dlya-beremennykh-i-kormyashchikh-mam/9-mesyatsev-krem-d-profilaktiki-i-korrektsii-rastyazhek-150ml80629/
Disallow: /catalog/lekarstva-i-bady/lekarstva-ot-prostudy/150/
Disallow: /catalog/dlya-krasoty-i-gigieny/ukhod-za-volosami-2488/150/
Disallow: /catalog/dlya-krasoty-i-gigieny/ukhod-za-polostyu-rta-2526/75/
Disallow: /catalog/mama-i-malysh/detskaya-kosmetika-2951/75/
Disallow: /catalog/lekarstva-i-bady/zdorovye-veny-gemorroy/75/
Disallow: /catalog/lekarstva-i-bady/raznoe-931/50/
Disallow: /catalog/dlya-krasoty-i-gigieny/ukhod-za-litsom-2446/50/
Disallow: /catalog/lekarstva-i-bady/vitaminy-i-mikroelementy/50/
Disallow: /catalog/lekarstva-i-bady/lekarstvennye-travy/ukrop-plody-50g45326/
Disallow: /catalog/lekarstva-i-bady/lekarstvennye-travy/ukrop-plody-50g4650/
Disallow: /catalog/intimnye-tovary-3267/dlya-povysheniya-libido/laveron-d-zhenshchin-tab-250mg-30109889/
Disallow: /catalog/intimnye-tovary-3267/dlya-povysheniya-libido/laveron-d-zhenshchin-tab-250mg-30/
Disallow: /catalog/mama-i-malysh/detskaya-gigiena-2879/vlazhnye-salfetki/64/
Disallow: /catalog/lekarstva-i-bady/preparaty-dlya-sistemnogo-vozdeystviya/tiosulfat-natriya-r-r-dlya-v-v-inekts-30-10ml-10-amp-10280/
Disallow: /catalog/intimnye-tovary-3267/ot-zabolevaniy-peredayushchikhsya-polovym-putem/metronidazol-tab-0-25g-2028637/
Disallow: /catalog/lekarstva-i-bady/lekarstva-pri-gormonalnykh-narusheniyakh/500-60/
Disallow: /catalog/lekarstva-i-bady/muzhskoe-zdorove/lekarstva-ot-adenomy-predstatelnoy-zhelezy/tamsulozin-retard-tab-p-o-prolong-0-4-mg-30147397/
Disallow: /catalog/lekarstva-i-bady/muzhskoe-zdorove/tamsulozin-kaps-s-modif-vysv-0-4mg-30151817/
Disallow: /catalog/lekarstva-i-bady/vitaminy-i-mikroelementy/monokomponentnye-vitaminy-i-mikroelementy/vitaminy-s-kaltsiem/kaltsiy-d3-forte-tab-zhevat-500mg-120-49567/
Disallow: /city/
Disallow: /essentiale/
Disallow: /3f01ebc18e4cb2f471fc3964c098e7b3
Disallow: /3f01ebc18e4cb2f471fc3964c098e7b3/
Disallow: /3f01ebc18e4cb2f471fc3964c098e7b3/pass/
Disallow: /3f01ebc18e4cb2f471fc3964c098e7b3/pass
Disallow: /law
Disallow: /law/
Disallow: /law/*
Disallow: /magazin/
Disallow: /autotest/*
Disallow: /feedback/
Disallow: /privacy-policy/terms-of-courier-delivery.php
Disallow: *tel:*
Disallow: /product/zhillette*
Disallow: /payment/
Disallow: /shop/
Allow: /*.js
Allow: /*.css

User-agent: Yandex
Disallow: /auth/
Disallow: /astma/
Disallow: /personal/
Disallow: /personal/cart/
Disallow: /upload/
Disallow: /search/
Disallow: /cron/
Disallow: /include/
Disallow: /login/
Disallow: /*/search/
Disallow: /*/slide_show/
Disallow: /*/gallery/*order=*
Disallow: /*?print=
Disallow: /*&print=
Disallow: /*register=
Disallow: /*forgot_password=
Disallow: /*change_password=
Disallow: /*login=
Disallow: /*/?login=*
Disallow: /*logout=
Disallow: /*/?logout=*
Disallow: /*auth=
Disallow: /*?action=
Disallow: /*action=ADD_TO_COMPARE_LIST
Disallow: /*action=DELETE_FROM_COMPARE_LIST
Disallow: /*action=ADD2BASKET
Disallow: /*action=BUY
Disallow: /*backurl=*
Disallow: /*BACKURL=*
Disallow: /*back_url=*
Disallow: /*BACK_URL=*
Disallow: /*back_url_admin=*
Disallow: /*print_course=Y
Disallow: /*COURSE_ID=
Disallow: /*?COURSE_ID=
Disallow: /*PAGE_NAME=user_post
Disallow: /*PAGE_NAME=detail_slide_show
Disallow: /*PAGE_NAME=search
Disallow: /*SHOWALL
Disallow: /*show_all=
Disallow: /*/?search=*
Disallow: /*/?view=*
Disallow: /*/?page_count=*
Disallow: /*/?sort=*
Disallow: *link_n.php*
Disallow: /bonus/
Disallow: /catalog/lekarstva-i-bady/zheludochno-kishechnye-preparaty/50/
Disallow: /catalog/lekarstva-i-bady/zdorovoe-pitanie-/5/
Disallow: /catalog/dlya-krasoty-i-gigieny/ukhod-za-litsom-2446/4/
Disallow: /catalog/lekarstva-i-bady/zdorovye-veny-gemorroy/oblepikhovoe-maslo-suppoz-rekt-0-5g-1065750/
Disallow: /catalog/lekarstva-i-bady/lekarstva-pri-infektsionnykh-zabolevaniyakh/plakvenil-tab-p-o-200mg-6017162/
Disallow: /catalog/dlya-krasoty-i-gigieny/ukhod-za-litsom-2446/15/
Disallow: /catalog/sistema-infuzion-dlya-pereliv-rastvorov-odnokrat-prim-122375/
Disallow: /catalog/intimnye-tovary-3267/sredstva-dlya-lecheniya-molochnitsy/flukonazol-kaps-0-15g-1148444/
Disallow: /catalog/lekarstva-i-bady/obezbolivayushchie/10/
Disallow: /catalog/lekarstva-i-bady/muzhskoe-zdorove/prostamol-uno-kaps-320mg-60156537/
Disallow: /catalog/lekarstva-i-bady/lekarstva-dlya-lecheniya-pochek/lekarstva-pri-vospalitelnykh-zabolevaniyakh-pochek-i-mochevyvodyashchikh-putey/protsistal-kaps-0-36-30-bad145281/
Disallow: /catalog/lekarstva-i-bady/lekarstva-dlya-lecheniya-pochek/protsistal-kaps-0-36-30-bad145281/
Disallow: /catalog/intimnye-tovary-3267/dlya-povysheniya-potentsii/viagra-tab-p-ob-100mg-17244/
Disallow: /catalog/intimnye-tovary-3267/dlya-povysheniya-potentsii/viagra-tab-p-ob-100mg-1153748/
Disallow: /catalog/lekarstva-i-bady/preparaty-dlya-sistemnogo-vozdeystviya/kaltsiya-khlorid-r-r-d-inekts-v-v-10-10ml-10-amp-154246/
Disallow: /catalog/lekarstva-i-bady/preparaty-dlya-sistemnogo-vozdeystviya/kaltsiya-khlorid-r-r-d-inekts-v-v-10-10ml-10-amp-418/
Disallow: /catalog/lekarstva-i-bady/zhenskoe-zdorove/metiluratsil-suppoz-rekt-0-5g-10/
Disallow: /catalog/lekarstva-i-bady/zhenskoe-zdorove/metiluratsil-suppoz-rekt-0-5g-1088735/
Disallow: /catalog/mama-i-malysh/kosmetika-dlya-beremennykh-i-kormyashchikh-mam/9-mesyatsev-krem-d-profilaktiki-i-korrektsii-rastyazhek-150ml106283/
Disallow: /catalog/mama-i-malysh/kosmetika-dlya-beremennykh-i-kormyashchikh-mam/9-mesyatsev-krem-d-profilaktiki-i-korrektsii-rastyazhek-150ml80629/
Disallow: /catalog/lekarstva-i-bady/lekarstva-ot-prostudy/150/
Disallow: /catalog/dlya-krasoty-i-gigieny/ukhod-za-volosami-2488/150/
Disallow: /catalog/dlya-krasoty-i-gigieny/ukhod-za-polostyu-rta-2526/75/
Disallow: /catalog/mama-i-malysh/detskaya-kosmetika-2951/75/
Disallow: /catalog/lekarstva-i-bady/zdorovye-veny-gemorroy/75/
Disallow: /catalog/lekarstva-i-bady/raznoe-931/50/
Disallow: /catalog/dlya-krasoty-i-gigieny/ukhod-za-litsom-2446/50/
Disallow: /catalog/lekarstva-i-bady/vitaminy-i-mikroelementy/50/
Disallow: /catalog/lekarstva-i-bady/lekarstvennye-travy/ukrop-plody-50g45326/
Disallow: /catalog/lekarstva-i-bady/lekarstvennye-travy/ukrop-plody-50g4650/
Disallow: /catalog/intimnye-tovary-3267/dlya-povysheniya-libido/laveron-d-zhenshchin-tab-250mg-30109889/
Disallow: /catalog/intimnye-tovary-3267/dlya-povysheniya-libido/laveron-d-zhenshchin-tab-250mg-30/
Disallow: /catalog/mama-i-malysh/detskaya-gigiena-2879/vlazhnye-salfetki/64/
Disallow: /catalog/lekarstva-i-bady/preparaty-dlya-sistemnogo-vozdeystviya/tiosulfat-natriya-r-r-dlya-v-v-inekts-30-10ml-10-amp-10280/
Disallow: /catalog/intimnye-tovary-3267/ot-zabolevaniy-peredayushchikhsya-polovym-putem/metronidazol-tab-0-25g-2028637/
Disallow: /catalog/lekarstva-i-bady/lekarstva-pri-gormonalnykh-narusheniyakh/500-60/
Disallow: /catalog/lekarstva-i-bady/muzhskoe-zdorove/lekarstva-ot-adenomy-predstatelnoy-zhelezy/tamsulozin-retard-tab-p-o-prolong-0-4-mg-30147397/
Disallow: /catalog/lekarstva-i-bady/muzhskoe-zdorove/tamsulozin-kaps-s-modif-vysv-0-4mg-30151817/
Disallow: /catalog/lekarstva-i-bady/vitaminy-i-mikroelementy/monokomponentnye-vitaminy-i-mikroelementy/vitaminy-s-kaltsiem/kaltsiy-d3-forte-tab-zhevat-500mg-120-49567/
Disallow: /city/
Disallow: /essentiale/
Disallow: /3f01ebc18e4cb2f471fc3964c098e7b3
Disallow: /3f01ebc18e4cb2f471fc3964c098e7b3/
Disallow: /3f01ebc18e4cb2f471fc3964c098e7b3/pass/
Disallow: /3f01ebc18e4cb2f471fc3964c098e7b3/pass
Disallow: /law
Disallow: /law/
Disallow: /law/*
Disallow: /magazin/
Disallow: /autotest/*
Disallow: /feedback/
Disallow: /categoriya/
Disallow: /magazin/
Disallow: /privacy-policy/terms-of-courier-delivery.php
Disallow: /product/zhillette*
Disallow: /payment/
Disallow: /shop/
Clean-param: from&gclid&sortBy&sortDesc&count&priceMin&priceMax&Search&page&utm&utm_source&utm_medium&utm_campaign&utm_term&utm_referrer&MinPrice&MaxPrice&k50id&inStock&RegionId&Delivery&Rating&PriceWithDelivery&roistat&roistat_referrer&roistat_pos /
Clean-param: q&ORDER_ID&origin&mindbox-click-id&mindbox-message-key&standalone&CONFIRMATION_TOKEN&erid&max&min&props&direction&row&sort&text&fbclid&brands&experiment&gamma&email&etext&device_id&cityCode&tagCode&page_count&frm&target&lang / 
Clean-param: referrer&PAGEN_1 /
Clean-param: sectionCode&fmode&keyno&l10n&la&mime&sign&tld&tm&url&PAGEN_2&tab&sid&brandCode&ved&uuid&sso_failed&group&fa821dba_ipp_key&fa821dba_ipp_uid&sa&SessionID&access_token&PageID&ServerID&type&clid&hl&ulrChangedByIncomingUtm /
Clean-param: gamma&min&max&m-message-key-id&TSPD_101_R0&tspd_101_r0&ylcyd&ycilyd&yyclyyd&yclyyd&ycylid&ycyid&yycleed&sectioncode&brandcode&pagecode&hideFilters&_ym_debug&night_mode&___________&__________&_________&________&_______&______&_____&____&___&m-message-click-id&utm_reqid&c2VjcmV0cGFyYW1ldGVyISExMTE_hm&set_filter&SECTION_ID&arrFilter_pf&arrFilter_ff%5BNAME%5D&arrFilter_pf%5Bmaker%5D&tag&yadordid&yadclid&clear_cache&source&id&pm_source&pm_block&pm_position&region&region_name&search_term_string&p&hcb
Clean-param: page_count&subSect&landingCode&yclyd&bitrix_include_areas&amp;ysclid&attachment_id

User-Agent: Googlebot
Disallow: /auth/
Disallow: /astma/
Disallow: /personal/
Disallow: /personal/cart/
Disallow: /upload/
Disallow: /search/
Disallow: /cron/
Disallow: /include/
Disallow: /login/
Disallow: /*/search/
Disallow: /*/slide_show/
Disallow: /*/gallery/*order=*
Disallow: /*?print=
Disallow: /*&print=
Disallow: /*register=
Disallow: /*forgot_password=
Disallow: /*change_password=
Disallow: /*login=
Disallow: /*/?login=*
Disallow: /*logout=
Disallow: /*/?logout=*
Disallow: /*auth=
Disallow: /*?action=
Disallow: /*action=ADD_TO_COMPARE_LIST
Disallow: /*action=DELETE_FROM_COMPARE_LIST
Disallow: /*action=ADD2BASKET
Disallow: /*action=BUY
Disallow: /*backurl=*
Disallow: /*BACKURL=*
Disallow: /*back_url=*
Disallow: /*BACK_URL=*
Disallow: /*back_url_admin=*
Disallow: /*print_course=Y
Disallow: /*COURSE_ID=
Disallow: /*?COURSE_ID=
Disallow: /*PAGE_NAME=user_post
Disallow: /*PAGE_NAME=detail_slide_show
Disallow: /*PAGE_NAME=search
Disallow: /*PAGEN_1=
Disallow: /*SHOWALL
Disallow: /*show_all=
Disallow: /*/?search=*
Disallow: /*/?view=*
Disallow: /*/?sort=*
Disallow: *link_n.php*
Disallow: /bonus/
Disallow: /catalog/lekarstva-i-bady/zheludochno-kishechnye-preparaty/50/
Disallow: /catalog/lekarstva-i-bady/zdorovoe-pitanie-/5/
Disallow: /catalog/dlya-krasoty-i-gigieny/ukhod-za-litsom-2446/4/
Disallow: /catalog/lekarstva-i-bady/zdorovye-veny-gemorroy/oblepikhovoe-maslo-suppoz-rekt-0-5g-1065750/
Disallow: /catalog/lekarstva-i-bady/lekarstva-pri-infektsionnykh-zabolevaniyakh/plakvenil-tab-p-o-200mg-6017162/
Disallow: /catalog/dlya-krasoty-i-gigieny/ukhod-za-litsom-2446/15/
Disallow: /catalog/sistema-infuzion-dlya-pereliv-rastvorov-odnokrat-prim-122375/
Disallow: /catalog/intimnye-tovary-3267/sredstva-dlya-lecheniya-molochnitsy/flukonazol-kaps-0-15g-1148444/
Disallow: /catalog/lekarstva-i-bady/obezbolivayushchie/10/
Disallow: /catalog/lekarstva-i-bady/muzhskoe-zdorove/prostamol-uno-kaps-320mg-60156537/
Disallow: /catalog/lekarstva-i-bady/lekarstva-dlya-lecheniya-pochek/lekarstva-pri-vospalitelnykh-zabolevaniyakh-pochek-i-mochevyvodyashchikh-putey/protsistal-kaps-0-36-30-bad145281/
Disallow: /catalog/lekarstva-i-bady/lekarstva-dlya-lecheniya-pochek/protsistal-kaps-0-36-30-bad145281/
Disallow: /catalog/intimnye-tovary-3267/dlya-povysheniya-potentsii/viagra-tab-p-ob-100mg-17244/
Disallow: /catalog/intimnye-tovary-3267/dlya-povysheniya-potentsii/viagra-tab-p-ob-100mg-1153748/
Disallow: /catalog/lekarstva-i-bady/preparaty-dlya-sistemnogo-vozdeystviya/kaltsiya-khlorid-r-r-d-inekts-v-v-10-10ml-10-amp-154246/
Disallow: /catalog/lekarstva-i-bady/preparaty-dlya-sistemnogo-vozdeystviya/kaltsiya-khlorid-r-r-d-inekts-v-v-10-10ml-10-amp-418/
Disallow: /catalog/lekarstva-i-bady/zhenskoe-zdorove/metiluratsil-suppoz-rekt-0-5g-10/
Disallow: /catalog/lekarstva-i-bady/zhenskoe-zdorove/metiluratsil-suppoz-rekt-0-5g-1088735/
Disallow: /catalog/mama-i-malysh/kosmetika-dlya-beremennykh-i-kormyashchikh-mam/9-mesyatsev-krem-d-profilaktiki-i-korrektsii-rastyazhek-150ml106283/
Disallow: /catalog/mama-i-malysh/kosmetika-dlya-beremennykh-i-kormyashchikh-mam/9-mesyatsev-krem-d-profilaktiki-i-korrektsii-rastyazhek-150ml80629/
Disallow: /catalog/lekarstva-i-bady/lekarstva-ot-prostudy/150/
Disallow: /catalog/dlya-krasoty-i-gigieny/ukhod-za-volosami-2488/150/
Disallow: /catalog/dlya-krasoty-i-gigieny/ukhod-za-polostyu-rta-2526/75/
Disallow: /catalog/mama-i-malysh/detskaya-kosmetika-2951/75/
Disallow: /catalog/lekarstva-i-bady/zdorovye-veny-gemorroy/75/
Disallow: /catalog/lekarstva-i-bady/raznoe-931/50/
Disallow: /catalog/dlya-krasoty-i-gigieny/ukhod-za-litsom-2446/50/
Disallow: /catalog/lekarstva-i-bady/vitaminy-i-mikroelementy/50/
Disallow: /catalog/lekarstva-i-bady/lekarstvennye-travy/ukrop-plody-50g45326/
Disallow: /catalog/lekarstva-i-bady/lekarstvennye-travy/ukrop-plody-50g4650/
Disallow: /catalog/intimnye-tovary-3267/dlya-povysheniya-libido/laveron-d-zhenshchin-tab-250mg-30109889/
Disallow: /catalog/intimnye-tovary-3267/dlya-povysheniya-libido/laveron-d-zhenshchin-tab-250mg-30/
Disallow: /catalog/mama-i-malysh/detskaya-gigiena-2879/vlazhnye-salfetki/64/
Disallow: /catalog/lekarstva-i-bady/preparaty-dlya-sistemnogo-vozdeystviya/tiosulfat-natriya-r-r-dlya-v-v-inekts-30-10ml-10-amp-10280/
Disallow: /catalog/intimnye-tovary-3267/ot-zabolevaniy-peredayushchikhsya-polovym-putem/metronidazol-tab-0-25g-2028637/
Disallow: /catalog/lekarstva-i-bady/lekarstva-pri-gormonalnykh-narusheniyakh/500-60/
Disallow: /catalog/lekarstva-i-bady/muzhskoe-zdorove/lekarstva-ot-adenomy-predstatelnoy-zhelezy/tamsulozin-retard-tab-p-o-prolong-0-4-mg-30147397/
Disallow: /catalog/lekarstva-i-bady/muzhskoe-zdorove/tamsulozin-kaps-s-modif-vysv-0-4mg-30151817/
Disallow: /catalog/lekarstva-i-bady/vitaminy-i-mikroelementy/monokomponentnye-vitaminy-i-mikroelementy/vitaminy-s-kaltsiem/kaltsiy-d3-forte-tab-zhevat-500mg-120-49567/
Disallow: /city/
Disallow: /essentiale/
Disallow: /3f01ebc18e4cb2f471fc3964c098e7b3
Disallow: /3f01ebc18e4cb2f471fc3964c098e7b3/
Disallow: /3f01ebc18e4cb2f471fc3964c098e7b3/pass/
Disallow: /3f01ebc18e4cb2f471fc3964c098e7b3/pass
Disallow: /law
Disallow: /law/
Disallow: /law/*
Disallow: /autotest/*
Disallow: /feedback/
Disallow: /privacy-policy/terms-of-courier-delivery.php
Disallow: *tel:*
Disallow: /product/zhillette*
Disallow: /payment/
Disallow: /shop/
Allow: /*.js
Allow: /*.css

Sitemap: https://vitaexpress.ru/sitemap.xml
