User-agent: *
Disallow: /preview/*
Disallow: /fashion-shows/
Disallow: */articulos/*/articulos/*
Disallow: /videos/*
Disallow: /galeria-de-fotos/
Disallow: /blogs
Disallow: /especiales/vogue_business/
Disallow: /search/index/
Disallow: *?image=
Disallow: */image/
Disallow: /*?redirectURL=
Disallow: /*{{url}}
Disallow: /*%7B%7Burl%7D%7D
Disallow: /*{{section}}
Disallow: /*%7B%7Bsection%7D%7D
Disallow: /product/
Disallow: /user-context?referrer
Disallow: /services.min.js?_=
Disallow: /com.condenast/yv8*

User-agent: Google-InspectionTool
Allow: /

User-agent: Google-Extended
User-agent: Google-CloudVertexBot
User-agent: GoogleOther
User-agent: Applebot-Extended
User-agent: Amazonbot
User-agent: meta-webindexer
User-agent: meta-externalagent
User-agent: meta-externalfetcher
User-agent: ClaudeBot
User-agent: Claude-SearchBot
User-agent: Claude-User
User-agent: PerplexityBot
User-agent: Perplexity-User
User-agent: cohere-training-data-crawler
User-agent: cohere-ai
User-agent: CCBot
User-agent: PanguBot
User-agent: PetalBot
User-agent: Bytespider
User-agent: Diffbot
User-agent: DuckAssistBot
User-agent: MistralAI-User
User-agent: Timpibot
User-agent: Webzio
User-agent: Webzio-Extended
User-agent: archive.org_bot
User-agent: ia_archiver
User-agent: ia_archiver-web.archive.org
User-agent: heritrix
Disallow: /

Sitemap: https://www.vogue.es/sitemap.xml
Sitemap: https://www.vogue.es/feed/articulos/sitemap-google-news
Sitemap: https://www.vogue.es/feed/galerias/sitemap-google-news
Sitemap: https://www.vogue.es/feed/rss
Sitemap: https://www.vogue.es/feed/news/sitemap-google-news
Sitemap: https://www.vogue.es/categories-sitemap.xml
Sitemap: https://www.vogue.es/contributors-sitemap.xml
Sitemap: https://www.vogue.es/branded-sitemap.xml
Sitemap: https://www.vogue.es/bundles-sitemap.xml
Sitemap: https://www.vogue.es/sitemap-archive-1.xml