User-agent: *
Disallow: /*,*/
Disallow: /rezerwacja/
Disallow: /swf/
Disallow: /ad/
Disallow: /zapytanie/
Disallow: /mytui/
Disallow: /blankwt
Disallow: /ed/
Disallow: /forum/member/
Disallow: /kreacje/
Disallow: /ajax/
Disallow: /*ogolne-warunki-uczestnictwa.pdf$
Disallow: /boksy/
Disallow: /umowa/
Disallow: /google-search-box*
Disallow: /*.json
Disallow: /*?recommendedOffers
Disallow: /*?recentlyViewed
Disallow: /facebook/
Disallow: /hoteldata/
Disallow: /forum/settings/profile
Disallow: /jsError.html
Disallow: /oferty/*?*
Disallow: /partner/
Disallow: /*?bez-*
Disallow: /*,bez-*
Disallow: /*za-wszystkic*
Disallow: /*-malejac*
Disallow: /*-rosnac*
Disallow: /*,od-*
Disallow: /*,do-*
Disallow: /*?od-*
Disallow: /*?do-*
Disallow: /*?ocen$
Disallow: /platnosc/
Disallow: /schowek.html
Disallow: /forum/core/
Disallow: /forum/filedata/
Disallow: /forum/album/
Disallow: /forum/*?p=*
Disallow: /lastminute/*europa-h*
Disallow: /wczasy/*europa-h*
Disallow: /narty/*europa-h*
Disallow: /udostepnione.htm*
Disallow: /bony-turystyczne/zamowienie.html
Disallow: /franczyza/zapytaj.html
Disallow: /wp-pilot/
Disallow: /opinie-ocen/
Disallow: /ulubione.html
Disallow: /*?statid*
Disallow: /*przecena*
Disallow: /*?*najwczesniej*

Allow: /wczasy/?bez-paszportu
Allow: /wczasy/?str-*bez-paszportu
Allow: /wczasy/?bez-testu-na-covid-19
Allow: /wczasy/?bez-testow-dla-zaszczepionych
