User-agent:*
#Disallow:/text/textview/*
Disallow:/edu/exn/*
Disallow:/edu/ex/*
#Disallow:/error/*
#Disallow:/dark/*
Disallow:/ooops/*
Disallow:/sentence/*
Disallow:/user/*
Disallow:/word/somethingfound/*
#Disallow:/word/romb_en_ru/*
Disallow:/phrase/*
Disallow:/wordtech/*
Disallow:/extranslation/*
Disallow:/openscripts/*
Disallow:/out_door.php*
Disallow:/out_door2.php
Disallow:/out_door_song.php*
Disallow:/dic/correctionfromuser*
Host:https://wooordhunt.ru
