User-Agent: *
Disallow: /doc/*.PDF
Disallow: /dog/*.PDF
Disallow: /Doc/*.PDF
Disallow: /Dog/*.PDF
Disallow: /doc/*.pdf
Disallow: /dog/*.pdf
Disallow: /Doc/*.pdf
Disallow: /Dog/*.pdf
Disallow: /Dog/*.nsf 
Disallow: /Dog/*.NSF 
Disallow: /rcp/listas/ 
Disallow: /dxfp/ 
Disallow: /video-en-directo/
Disallow: /video-en-directo
Disallow: /documents/non-indexar/
Disallow: /documents/ficheiros/
Sitemap: https://www.xunta.gal/sitemap.xml