User-Agent: *
Disallow: /cgi-bin
Disallow: /basket
Disallow: /bitrix/
Disallow: *bitrix_*=
Disallow: /local/
Disallow: /test/
Disallow: /*index.php$
Disallow: /auth
Disallow: /personal/
Disallow: /*order
Disallow: *register=
Disallow: *forgot_password=
Disallow: *change_password=
Disallow: /*login=
Disallow: *logout=
Disallow: */search/
Disallow: *display=
Disallow: *linerow=
Disallow: *year=
Disallow: *action=
Disallow: *alfaction=
Disallow: *print=
Disallow: *?new=Y
Disallow: *?edit=
Disallow: *?preview=
Disallow: *backurl=
Disallow: *back_url=
Disallow: *back_url_admin=
Disallow: *captcha
Disallow: *?FILTER*=
Disallow: *?arrFilter*
Disallow: *set_filter=
Disallow: *oid=*
Disallow: *?ei=
Disallow: *id=
Disallow: *?p=
Disallow: *?q=
Disallow: *?tags=
Disallow: *brand=
Disallow: *clear_cache*
Disallow: *element_id=
Disallow: *different=
Disallow: *price_from=
Disallow: *price_to=
Disallow: /*type=
Disallow: *property_width=
Disallow: *property_height=
Disallow: *property_dia=
Disallow: *property_opening_count=
Disallow: *property_price[*]=
Disallow: *s_last=
Disallow: *section_id=
Disallow: *section[*]=
Disallow: /*show_
Disallow: *showall=
Disallow: *show_all=
Disallow: *showby=
Disallow: /*add_to_*
Disallow: *sort=
Disallow: *?action_ccr=
Disallow: *sphrase_id=
Disallow: *etext=
Disallow: *utm*=
Disallow: *openstat=
Disallow: *from=
Disallow: *gclid=
Disallow: *yclid=
Disallow: */apply/
Disallow: */feed
Disallow: */rss
Disallow: *orderby=
Disallow: *taxonomy=
Disallow: *private=
Disallow: */amp
Disallow: *amp=
Allow: /search/map.php
Allow: */upload/
Allow: /bitrix/*.js
Allow: /local/*.js
Allow: /bitrix/*.css
Allow: /local/*.jpg
Allow: /local/*.jpeg
Allow: /local/*.png
Allow: /local/*.gif
Allow: /local/*.webp
Allow: /local/*.svg
Allow: /local/*.pdf
Allow: /local/*.ttf
Allow: /local/*.woff
Allow: /articles
Allow: /company
Allow: /contacts
Allow: /gallery
Allow: /images
Allow: /projects
Allow: /services
Allow: /sitemap
Sitemap: https://www.yito.ru/sitemap.xml
Sitemap: http://www.yito.ru/sitemap.xml

User-Agent: Yandex
Disallow: /cgi-bin
Disallow: /basket
Disallow: /bitrix/
Disallow: *bitrix_*=
Disallow: /local/
Disallow: /test/
Disallow: /*index.php$
Disallow: /auth
Disallow: /personal/
Disallow: /*order
Disallow: *register=
Disallow: *forgot_password=
Disallow: *change_password=
Disallow: /*login=
Disallow: *logout=
Disallow: */search/
Disallow: *display=
Disallow: *linerow=
Disallow: *year=
Disallow: *action=
Disallow: *alfaction=
Disallow: *print=
Disallow: *?new=Y
Disallow: *?edit=
Disallow: *?preview=
Disallow: *backurl=
Disallow: *back_url=
Disallow: *back_url_admin=
Disallow: *captcha
Disallow: *?FILTER*=
Disallow: *?arrFilter*
Disallow: *set_filter=
Disallow: *oid=*
Disallow: *?ei=
Disallow: *id=
Disallow: *?p=
Disallow: *?q=
Disallow: *?tags=
Disallow: *brand=
Disallow: *clear_cache*
Disallow: *element_id=
Disallow: *different=
Disallow: *price_from=
Disallow: *price_to=
Disallow: /*type=
Disallow: *property_width=
Disallow: *property_height=
Disallow: *property_dia=
Disallow: *property_opening_count=
Disallow: *property_price[*]=
Disallow: *s_last=
Disallow: *section_id=
Disallow: *section[*]=
Disallow: /*show_
Disallow: *showall=
Disallow: *show_all=
Disallow: *showby=
Disallow: /*add_to_*
Disallow: *sort=
Disallow: *?action_ccr=
Disallow: *sphrase_id=
Disallow: *etext=
Disallow: *utm*=
Disallow: *openstat=
Disallow: *from=
Disallow: *gclid=
Disallow: *yclid=
Disallow: */apply/
Disallow: */feed
Disallow: */rss
Disallow: *orderby=
Disallow: *taxonomy=
Disallow: *private=
Disallow: */amp
Disallow: *amp=
Allow: /search/map.php
Allow: */upload/
Allow: /bitrix/*.js
Allow: /local/*.js
Allow: /bitrix/*.css
Allow: /local/*.jpg
Allow: /local/*.jpeg
Allow: /local/*.png
Allow: /local/*.gif
Allow: /local/*.webp
Allow: /local/*.svg
Allow: /local/*.pdf
Allow: /local/*.ttf
Allow: /local/*.woff
Allow: /articles
Allow: /company
Allow: /contacts
Allow: /gallery
Allow: /images
Allow: /projects
Allow: /services
Allow: /sitemap

User-Agent: YandexBot
Disallow: /cgi-bin
Disallow: /basket
Disallow: /bitrix/
Disallow: *bitrix_*=
Disallow: /local/
Disallow: /test/
Disallow: /*index.php$
Disallow: /auth
Disallow: /personal/
Disallow: /*order
Disallow: *register=
Disallow: *forgot_password=
Disallow: *change_password=
Disallow: /*login=
Disallow: *logout=
Disallow: */search/
Disallow: *display=
Disallow: *linerow=
Disallow: *year=
Disallow: *action=
Disallow: *alfaction=
Disallow: *print=
Disallow: *?new=Y
Disallow: *?edit=
Disallow: *?preview=
Disallow: *backurl=
Disallow: *back_url=
Disallow: *back_url_admin=
Disallow: *captcha
Disallow: *?FILTER*=
Disallow: *?arrFilter*
Disallow: *set_filter=
Disallow: *oid=*
Disallow: *?ei=
Disallow: *id=
Disallow: *?p=
Disallow: *?q=
Disallow: *?tags=
Disallow: *brand=
Disallow: *clear_cache*
Disallow: *element_id=
Disallow: *different=
Disallow: *price_from=
Disallow: *price_to=
Disallow: /*type=
Disallow: *property_width=
Disallow: *property_height=
Disallow: *property_dia=
Disallow: *property_opening_count=
Disallow: *property_price[*]=
Disallow: *s_last=
Disallow: *section_id=
Disallow: *section[*]=
Disallow: /*show_
Disallow: *showall=
Disallow: *show_all=
Disallow: *showby=
Disallow: /*add_to_*
Disallow: *sort=
Disallow: *?action_ccr=
Disallow: *sphrase_id=
Disallow: *etext=
Disallow: *utm*=
Disallow: *openstat=
Disallow: *from=
Disallow: *gclid=
Disallow: *yclid=
Disallow: */apply/
Disallow: */feed
Disallow: */rss
Disallow: *orderby=
Disallow: *taxonomy=
Disallow: *private=
Disallow: */amp
Disallow: *amp=
Allow: /search/map.php
Allow: */upload/
Allow: /bitrix/*.js
Allow: /local/*.js
Allow: /bitrix/*.css
Allow: /local/*.jpg
Allow: /local/*.jpeg
Allow: /local/*.png
Allow: /local/*.gif
Allow: /local/*.webp
Allow: /local/*.svg
Allow: /local/*.pdf
Allow: /local/*.ttf
Allow: /local/*.woff
Allow: /articles
Allow: /company
Allow: /contacts
Allow: /gallery
Allow: /images
Allow: /projects
Allow: /services
Allow: /sitemap

User-Agent: YandexMedia
Disallow: /cgi-bin
Disallow: /basket
Disallow: /bitrix/
Disallow: *bitrix_*=
Disallow: /local/
Disallow: /test/
Disallow: /*index.php$
Disallow: /auth
Disallow: /personal/
Disallow: /*order
Disallow: *register=
Disallow: *forgot_password=
Disallow: *change_password=
Disallow: /*login=
Disallow: *logout=
Disallow: */search/
Disallow: *display=
Disallow: *linerow=
Disallow: *year=
Disallow: *action=
Disallow: *alfaction=
Disallow: *print=
Disallow: *?new=Y
Disallow: *?edit=
Disallow: *?preview=
Disallow: *backurl=
Disallow: *back_url=
Disallow: *back_url_admin=
Disallow: *captcha
Disallow: *?FILTER*=
Disallow: *?arrFilter*
Disallow: *set_filter=
Disallow: *oid=*
Disallow: *?ei=
Disallow: *id=
Disallow: *?p=
Disallow: *?q=
Disallow: *?tags=
Disallow: *brand=
Disallow: *clear_cache*
Disallow: *element_id=
Disallow: *different=
Disallow: *price_from=
Disallow: *price_to=
Disallow: /*type=
Disallow: *property_width=
Disallow: *property_height=
Disallow: *property_dia=
Disallow: *property_opening_count=
Disallow: *property_price[*]=
Disallow: *s_last=
Disallow: *section_id=
Disallow: *section[*]=
Disallow: /*show_
Disallow: *showall=
Disallow: *show_all=
Disallow: *showby=
Disallow: /*add_to_*
Disallow: *sort=
Disallow: *?action_ccr=
Disallow: *sphrase_id=
Disallow: *etext=
Disallow: *utm*=
Disallow: *openstat=
Disallow: *from=
Disallow: *gclid=
Disallow: *yclid=
Disallow: */apply/
Disallow: */feed
Disallow: */rss
Disallow: *orderby=
Disallow: *taxonomy=
Disallow: *private=
Disallow: */amp
Disallow: *amp=
Allow: /search/map.php
Allow: */upload/
Allow: /bitrix/*.js
Allow: /local/*.js
Allow: /bitrix/*.css
Allow: /local/*.jpg
Allow: /local/*.jpeg
Allow: /local/*.png
Allow: /local/*.gif
Allow: /local/*.webp
Allow: /local/*.svg
Allow: /local/*.pdf
Allow: /local/*.ttf
Allow: /local/*.woff
Allow: /articles
Allow: /company
Allow: /contacts
Allow: /gallery
Allow: /images
Allow: /projects
Allow: /services
Allow: /sitemap

User-Agent: YandexImages
Disallow: /cgi-bin
Disallow: /basket
Disallow: /bitrix/
Disallow: *bitrix_*=
Disallow: /local/
Disallow: /test/
Disallow: /*index.php$
Disallow: /auth
Disallow: /personal/
Disallow: /*order
Disallow: *register=
Disallow: *forgot_password=
Disallow: *change_password=
Disallow: /*login=
Disallow: *logout=
Disallow: */search/
Disallow: *display=
Disallow: *linerow=
Disallow: *year=
Disallow: *action=
Disallow: *alfaction=
Disallow: *print=
Disallow: *?new=Y
Disallow: *?edit=
Disallow: *?preview=
Disallow: *backurl=
Disallow: *back_url=
Disallow: *back_url_admin=
Disallow: *captcha
Disallow: *?FILTER*=
Disallow: *?arrFilter*
Disallow: *set_filter=
Disallow: *oid=*
Disallow: *?ei=
Disallow: *id=
Disallow: *?p=
Disallow: *?q=
Disallow: *?tags=
Disallow: *brand=
Disallow: *clear_cache*
Disallow: *element_id=
Disallow: *different=
Disallow: *price_from=
Disallow: *price_to=
Disallow: /*type=
Disallow: *property_width=
Disallow: *property_height=
Disallow: *property_dia=
Disallow: *property_opening_count=
Disallow: *property_price[*]=
Disallow: *s_last=
Disallow: *section_id=
Disallow: *section[*]=
Disallow: /*show_
Disallow: *showall=
Disallow: *show_all=
Disallow: *showby=
Disallow: /*add_to_*
Disallow: *sort=
Disallow: *?action_ccr=
Disallow: *sphrase_id=
Disallow: *etext=
Disallow: *utm*=
Disallow: *openstat=
Disallow: *from=
Disallow: *gclid=
Disallow: *yclid=
Disallow: */apply/
Disallow: */feed
Disallow: */rss
Disallow: *orderby=
Disallow: *taxonomy=
Disallow: *private=
Disallow: */amp
Disallow: *amp=
Allow: /search/map.php
Allow: */upload/
Allow: /bitrix/*.js
Allow: /local/*.js
Allow: /bitrix/*.css
Allow: /local/*.jpg
Allow: /local/*.jpeg
Allow: /local/*.png
Allow: /local/*.gif
Allow: /local/*.webp
Allow: /local/*.svg
Allow: /local/*.pdf
Allow: /local/*.ttf
Allow: /local/*.woff
Allow: /articles
Allow: /company
Allow: /contacts
Allow: /gallery
Allow: /images
Allow: /projects
Allow: /services
Allow: /sitemap

User-Agent: YandexBlogs
Disallow: /cgi-bin
Disallow: /basket
Disallow: /bitrix/
Disallow: *bitrix_*=
Disallow: /local/
Disallow: /test/
Disallow: /*index.php$
Disallow: /auth
Disallow: /personal/
Disallow: /*order
Disallow: *register=
Disallow: *forgot_password=
Disallow: *change_password=
Disallow: /*login=
Disallow: *logout=
Disallow: */search/
Disallow: *display=
Disallow: *linerow=
Disallow: *year=
Disallow: *action=
Disallow: *alfaction=
Disallow: *print=
Disallow: *?new=Y
Disallow: *?edit=
Disallow: *?preview=
Disallow: *backurl=
Disallow: *back_url=
Disallow: *back_url_admin=
Disallow: *captcha
Disallow: *?FILTER*=
Disallow: *?arrFilter*
Disallow: *set_filter=
Disallow: *oid=*
Disallow: *?ei=
Disallow: *id=
Disallow: *?p=
Disallow: *?q=
Disallow: *?tags=
Disallow: *brand=
Disallow: *clear_cache*
Disallow: *element_id=
Disallow: *different=
Disallow: *price_from=
Disallow: *price_to=
Disallow: /*type=
Disallow: *property_width=
Disallow: *property_height=
Disallow: *property_dia=
Disallow: *property_opening_count=
Disallow: *property_price[*]=
Disallow: *s_last=
Disallow: *section_id=
Disallow: *section[*]=
Disallow: /*show_
Disallow: *showall=
Disallow: *show_all=
Disallow: *showby=
Disallow: /*add_to_*
Disallow: *sort=
Disallow: *?action_ccr=
Disallow: *sphrase_id=
Disallow: *etext=
Disallow: *utm*=
Disallow: *openstat=
Disallow: *from=
Disallow: *gclid=
Disallow: *yclid=
Disallow: */apply/
Disallow: */feed
Disallow: */rss
Disallow: *orderby=
Disallow: *taxonomy=
Disallow: *private=
Disallow: */amp
Disallow: *amp=
Allow: /search/map.php
Allow: */upload/
Allow: /bitrix/*.js
Allow: /local/*.js
Allow: /bitrix/*.css
Allow: /local/*.jpg
Allow: /local/*.jpeg
Allow: /local/*.png
Allow: /local/*.gif
Allow: /local/*.webp
Allow: /local/*.svg
Allow: /local/*.pdf
Allow: /local/*.ttf
Allow: /local/*.woff
Allow: /articles
Allow: /company
Allow: /contacts
Allow: /gallery
Allow: /images
Allow: /projects
Allow: /services
Allow: /sitemap

User-Agent: YandexNews
Disallow: /cgi-bin
Disallow: /basket
Disallow: /bitrix/
Disallow: *bitrix_*=
Disallow: /local/
Disallow: /test/
Disallow: /*index.php$
Disallow: /auth
Disallow: /personal/
Disallow: /*order
Disallow: *register=
Disallow: *forgot_password=
Disallow: *change_password=
Disallow: /*login=
Disallow: *logout=
Disallow: */search/
Disallow: *display=
Disallow: *linerow=
Disallow: *year=
Disallow: *action=
Disallow: *alfaction=
Disallow: *print=
Disallow: *?new=Y
Disallow: *?edit=
Disallow: *?preview=
Disallow: *backurl=
Disallow: *back_url=
Disallow: *back_url_admin=
Disallow: *captcha
Disallow: *?FILTER*=
Disallow: *?arrFilter*
Disallow: *set_filter=
Disallow: *oid=*
Disallow: *?ei=
Disallow: *id=
Disallow: *?p=
Disallow: *?q=
Disallow: *?tags=
Disallow: *brand=
Disallow: *clear_cache*
Disallow: *element_id=
Disallow: *different=
Disallow: *price_from=
Disallow: *price_to=
Disallow: /*type=
Disallow: *property_width=
Disallow: *property_height=
Disallow: *property_dia=
Disallow: *property_opening_count=
Disallow: *property_price[*]=
Disallow: *s_last=
Disallow: *section_id=
Disallow: *section[*]=
Disallow: /*show_
Disallow: *showall=
Disallow: *show_all=
Disallow: *showby=
Disallow: /*add_to_*
Disallow: *sort=
Disallow: *?action_ccr=
Disallow: *sphrase_id=
Disallow: *etext=
Disallow: *utm*=
Disallow: *openstat=
Disallow: *from=
Disallow: *gclid=
Disallow: *yclid=
Disallow: */apply/
Disallow: */feed
Disallow: */rss
Disallow: *orderby=
Disallow: *taxonomy=
Disallow: *private=
Disallow: */amp
Disallow: *amp=
Allow: /search/map.php
Allow: */upload/
Allow: /bitrix/*.js
Allow: /local/*.js
Allow: /bitrix/*.css
Allow: /local/*.jpg
Allow: /local/*.jpeg
Allow: /local/*.png
Allow: /local/*.gif
Allow: /local/*.webp
Allow: /local/*.svg
Allow: /local/*.pdf
Allow: /local/*.ttf
Allow: /local/*.woff
Allow: /articles
Allow: /company
Allow: /contacts
Allow: /gallery
Allow: /images
Allow: /projects
Allow: /services
Allow: /sitemap

User-Agent: YandexMetrika
Disallow: /cgi-bin
Disallow: /basket
Disallow: /bitrix/
Disallow: *bitrix_*=
Disallow: /local/
Disallow: /test/
Disallow: /*index.php$
Disallow: /auth
Disallow: /personal/
Disallow: /*order
Disallow: *register=
Disallow: *forgot_password=
Disallow: *change_password=
Disallow: /*login=
Disallow: *logout=
Disallow: */search/
Disallow: *display=
Disallow: *linerow=
Disallow: *year=
Disallow: *action=
Disallow: *alfaction=
Disallow: *print=
Disallow: *?new=Y
Disallow: *?edit=
Disallow: *?preview=
Disallow: *backurl=
Disallow: *back_url=
Disallow: *back_url_admin=
Disallow: *captcha
Disallow: *?FILTER*=
Disallow: *?arrFilter*
Disallow: *set_filter=
Disallow: *oid=*
Disallow: *?ei=
Disallow: *id=
Disallow: *?p=
Disallow: *?q=
Disallow: *?tags=
Disallow: *brand=
Disallow: *clear_cache*
Disallow: *element_id=
Disallow: *different=
Disallow: *price_from=
Disallow: *price_to=
Disallow: /*type=
Disallow: *property_width=
Disallow: *property_height=
Disallow: *property_dia=
Disallow: *property_opening_count=
Disallow: *property_price[*]=
Disallow: *s_last=
Disallow: *section_id=
Disallow: *section[*]=
Disallow: /*show_
Disallow: *showall=
Disallow: *show_all=
Disallow: *showby=
Disallow: /*add_to_*
Disallow: *sort=
Disallow: *?action_ccr=
Disallow: *sphrase_id=
Disallow: *etext=
Disallow: *utm*=
Disallow: *openstat=
Disallow: *from=
Disallow: *gclid=
Disallow: *yclid=
Disallow: */apply/
Disallow: */feed
Disallow: */rss
Disallow: *orderby=
Disallow: *taxonomy=
Disallow: *private=
Disallow: */amp
Disallow: *amp=
Allow: /search/map.php
Allow: */upload/
Allow: /bitrix/*.js
Allow: /local/*.js
Allow: /bitrix/*.css
Allow: /local/*.jpg
Allow: /local/*.jpeg
Allow: /local/*.png
Allow: /local/*.gif
Allow: /local/*.webp
Allow: /local/*.svg
Allow: /local/*.pdf
Allow: /local/*.ttf
Allow: /local/*.woff
Allow: /articles
Allow: /company
Allow: /contacts
Allow: /gallery
Allow: /images
Allow: /projects
Allow: /services
Allow: /sitemap

User-Agent: YandexMarket
Disallow: /cgi-bin
Disallow: /basket
Disallow: /bitrix/
Disallow: *bitrix_*=
Disallow: /local/
Disallow: /test/
Disallow: /*index.php$
Disallow: /auth
Disallow: /personal/
Disallow: /*order
Disallow: *register=
Disallow: *forgot_password=
Disallow: *change_password=
Disallow: /*login=
Disallow: *logout=
Disallow: */search/
Disallow: *display=
Disallow: *linerow=
Disallow: *year=
Disallow: *action=
Disallow: *alfaction=
Disallow: *print=
Disallow: *?new=Y
Disallow: *?edit=
Disallow: *?preview=
Disallow: *backurl=
Disallow: *back_url=
Disallow: *back_url_admin=
Disallow: *captcha
Disallow: *?FILTER*=
Disallow: *?arrFilter*
Disallow: *set_filter=
Disallow: *oid=*
Disallow: *?ei=
Disallow: *id=
Disallow: *?p=
Disallow: *?q=
Disallow: *?tags=
Disallow: *brand=
Disallow: *clear_cache*
Disallow: *element_id=
Disallow: *different=
Disallow: *price_from=
Disallow: *price_to=
Disallow: /*type=
Disallow: *property_width=
Disallow: *property_height=
Disallow: *property_dia=
Disallow: *property_opening_count=
Disallow: *property_price[*]=
Disallow: *s_last=
Disallow: *section_id=
Disallow: *section[*]=
Disallow: /*show_
Disallow: *showall=
Disallow: *show_all=
Disallow: *showby=
Disallow: /*add_to_*
Disallow: *sort=
Disallow: *?action_ccr=
Disallow: *sphrase_id=
Disallow: *etext=
Disallow: *utm*=
Disallow: *openstat=
Disallow: *from=
Disallow: *gclid=
Disallow: *yclid=
Disallow: */apply/
Disallow: */feed
Disallow: */rss
Disallow: *orderby=
Disallow: *taxonomy=
Disallow: *private=
Disallow: */amp
Disallow: *amp=
Allow: /search/map.php
Allow: */upload/
Allow: /bitrix/*.js
Allow: /local/*.js
Allow: /bitrix/*.css
Allow: /local/*.jpg
Allow: /local/*.jpeg
Allow: /local/*.png
Allow: /local/*.gif
Allow: /local/*.webp
Allow: /local/*.svg
Allow: /local/*.pdf
Allow: /local/*.ttf
Allow: /local/*.woff
Allow: /articles
Allow: /company
Allow: /contacts
Allow: /gallery
Allow: /images
Allow: /projects
Allow: /services
Allow: /sitemap

User-Agent: Googlebot
Disallow: /cgi-bin
Disallow: /basket
Disallow: /bitrix/
Disallow: *bitrix_*=
Disallow: /local/
Disallow: /test/
Disallow: /*index.php$
Disallow: /auth
Disallow: /personal/=
Disallow: /*order
Disallow: *register=
Disallow: *forgot_password=
Disallow: *change_password=
Disallow: /*login=
Disallow: *logout=
Disallow: */search/
Disallow: *display=
Disallow: *linerow=
Disallow: *year=
Disallow: *action=
Disallow: *alfaction=
Disallow: *print=
Disallow: *?new=Y
Disallow: *?edit=
Disallow: *?preview=
Disallow: *backurl=
Disallow: *back_url=
Disallow: *back_url_admin=
Disallow: *captcha
Disallow: *?FILTER*=
Disallow: *?arrFilter*
Disallow: *set_filter=
Disallow: *oid=*
Disallow: *?ei=
Disallow: *id=
Disallow: *?p=
Disallow: *?q=
Disallow: *?tags=
Disallow: *brand=
Disallow: *clear_cache*
Disallow: *element_id=
Disallow: *different=
Disallow: *price_from=
Disallow: *price_to=
Disallow: /*type=
Disallow: *property_width=
Disallow: *property_height=
Disallow: *property_dia=
Disallow: *property_opening_count=
Disallow: *property_price[*]=
Disallow: *s_last=
Disallow: *section_id=
Disallow: *section[*]=
Disallow: /*show_
Disallow: *showall=
Disallow: *show_all=
Disallow: *showby=
Disallow: /*add_to_*
Disallow: *sort=
Disallow: *?action_ccr=
Disallow: *sphrase_id=
Disallow: *etext=
Disallow: *utm*=
Disallow: *openstat=
Disallow: *from=
Disallow: *gclid=
Disallow: *yclid=
Disallow: */apply/
Disallow: */feed
Disallow: */rss
Disallow: *orderby=
Disallow: *taxonomy=
Disallow: *private=
Allow: /search/map.php
Allow: */upload/
Allow: /bitrix/*.js
Allow: /local/*.js
Allow: /bitrix/*.css
Allow: /local/*.jpg
Allow: /local/*.jpeg
Allow: /local/*.png
Allow: /local/*.gif
Allow: /local/*.webp
Allow: /local/*.svg
Allow: /local/*.pdf
Allow: /local/*.ttf
Allow: /local/*.woff
Allow: /articles
Allow: /company
Allow: /contacts
Allow: /gallery
Allow: /images
Allow: /projects
Allow: /services
Allow: /sitemap

User-Agent: Googlebot-News
Disallow: /cgi-bin
Disallow: /basket
Disallow: /bitrix/
Disallow: *bitrix_*=
Disallow: /local/
Disallow: /test/
Disallow: /*index.php$
Disallow: /auth
Disallow: /personal/=
Disallow: /*order
Disallow: *register=
Disallow: *forgot_password=
Disallow: *change_password=
Disallow: /*login=
Disallow: *logout=
Disallow: */search/
Disallow: *display=
Disallow: *linerow=
Disallow: *year=
Disallow: *action=
Disallow: *alfaction=
Disallow: *print=
Disallow: *?new=Y
Disallow: *?edit=
Disallow: *?preview=
Disallow: *backurl=
Disallow: *back_url=
Disallow: *back_url_admin=
Disallow: *captcha
Disallow: *?FILTER*=
Disallow: *?arrFilter*
Disallow: *set_filter=
Disallow: *oid=*
Disallow: *?ei=
Disallow: *id=
Disallow: *?p=
Disallow: *?q=
Disallow: *?tags=
Disallow: *brand=
Disallow: *clear_cache*
Disallow: *element_id=
Disallow: *different=
Disallow: *price_from=
Disallow: *price_to=
Disallow: /*type=
Disallow: *property_width=
Disallow: *property_height=
Disallow: *property_dia=
Disallow: *property_opening_count=
Disallow: *property_price[*]=
Disallow: *s_last=
Disallow: *section_id=
Disallow: *section[*]=
Disallow: /*show_
Disallow: *showall=
Disallow: *show_all=
Disallow: *showby=
Disallow: /*add_to_*
Disallow: *sort=
Disallow: *?action_ccr=
Disallow: *sphrase_id=
Disallow: *etext=
Disallow: *utm*=
Disallow: *openstat=
Disallow: *from=
Disallow: *gclid=
Disallow: *yclid=
Disallow: */apply/
Disallow: */feed
Disallow: */rss
Disallow: *orderby=
Disallow: *taxonomy=
Disallow: *private=
Allow: */upload/
Allow: /bitrix/*.js
Allow: /local/*.js
Allow: /bitrix/*.css
Allow: /local/*.jpg
Allow: /local/*.jpeg
Allow: /local/*.png
Allow: /local/*.gif
Allow: /local/*.webp
Allow: /local/*.svg
Allow: /local/*.pdf
Allow: /local/*.ttf
Allow: /local/*.woff
Allow: /articles
Allow: /company
Allow: /contacts
Allow: /gallery
Allow: /images
Allow: /projects
Allow: /services
Allow: /sitemap

User-Agent: Googlebot-Image
Disallow: /cgi-bin
Disallow: /basket
Disallow: /bitrix/
Disallow: *bitrix_*=
Disallow: /local/
Disallow: /test/
Disallow: /*index.php$
Disallow: /auth
Disallow: /personal/=
Disallow: /*order
Disallow: *register=
Disallow: *forgot_password=
Disallow: *change_password=
Disallow: /*login=
Disallow: *logout=
Disallow: */search/
Disallow: *display=
Disallow: *linerow=
Disallow: *year=
Disallow: *action=
Disallow: *alfaction=
Disallow: *print=
Disallow: *?new=Y
Disallow: *?edit=
Disallow: *?preview=
Disallow: *backurl=
Disallow: *back_url=
Disallow: *back_url_admin=
Disallow: *captcha
Disallow: *?FILTER*=
Disallow: *?arrFilter*
Disallow: *set_filter=
Disallow: *oid=*
Disallow: *?ei=
Disallow: *id=
Disallow: *?p=
Disallow: *?q=
Disallow: *?tags=
Disallow: *brand=
Disallow: *clear_cache*
Disallow: *element_id=
Disallow: *different=
Disallow: *price_from=
Disallow: *price_to=
Disallow: /*type=
Disallow: *property_width=
Disallow: *property_height=
Disallow: *property_dia=
Disallow: *property_opening_count=
Disallow: *property_price[*]=
Disallow: *s_last=
Disallow: *section_id=
Disallow: *section[*]=
Disallow: /*show_
Disallow: *showall=
Disallow: *show_all=
Disallow: *showby=
Disallow: /*add_to_*
Disallow: *sort=
Disallow: *?action_ccr=
Disallow: *sphrase_id=
Disallow: *etext=
Disallow: *utm*=
Disallow: *openstat=
Disallow: *from=
Disallow: *gclid=
Disallow: *yclid=
Disallow: */apply/
Disallow: */feed
Disallow: */rss
Disallow: *orderby=
Disallow: *taxonomy=
Disallow: *private=
Allow: */upload/
Allow: /bitrix/*.js
Allow: /local/*.js
Allow: /bitrix/*.css
Allow: /local/*.jpg
Allow: /local/*.jpeg
Allow: /local/*.png
Allow: /local/*.gif
Allow: /local/*.webp
Allow: /local/*.svg
Allow: /local/*.pdf
Allow: /local/*.ttf
Allow: /local/*.woff
Allow: /articles
Allow: /company
Allow: /contacts
Allow: /gallery
Allow: /images
Allow: /projects
Allow: /services
Allow: /sitemap

User-Agent: Googlebot-Video
Disallow: /cgi-bin
Disallow: /basket
Disallow: /bitrix/
Disallow: *bitrix_*=
Disallow: /local/
Disallow: /test/
Disallow: /*index.php$
Disallow: /auth
Disallow: /personal/=
Disallow: /*order
Disallow: *register=
Disallow: *forgot_password=
Disallow: *change_password=
Disallow: /*login=
Disallow: *logout=
Disallow: */search/
Disallow: *display=
Disallow: *linerow=
Disallow: *year=
Disallow: *action=
Disallow: *alfaction=
Disallow: *print=
Disallow: *?new=Y
Disallow: *?edit=
Disallow: *?preview=
Disallow: *backurl=
Disallow: *back_url=
Disallow: *back_url_admin=
Disallow: *captcha
Disallow: *?FILTER*=
Disallow: *?arrFilter*
Disallow: *set_filter=
Disallow: *oid=*
Disallow: *?ei=
Disallow: *id=
Disallow: *?p=
Disallow: *?q=
Disallow: *?tags=
Disallow: *brand=
Disallow: *clear_cache*
Disallow: *element_id=
Disallow: *different=
Disallow: *price_from=
Disallow: *price_to=
Disallow: /*type=
Disallow: *property_width=
Disallow: *property_height=
Disallow: *property_dia=
Disallow: *property_opening_count=
Disallow: *property_price[*]=
Disallow: *s_last=
Disallow: *section_id=
Disallow: *section[*]=
Disallow: /*show_
Disallow: *showall=
Disallow: *show_all=
Disallow: *showby=
Disallow: /*add_to_*
Disallow: *sort=
Disallow: *?action_ccr=
Disallow: *sphrase_id=
Disallow: *etext=
Disallow: *utm*=
Disallow: *openstat=
Disallow: *from=
Disallow: *gclid=
Disallow: *yclid=
Disallow: */apply/
Disallow: */feed
Disallow: */rss
Disallow: *orderby=
Disallow: *taxonomy=
Disallow: *private=
Allow: */upload/
Allow: /bitrix/*.js
Allow: /local/*.js
Allow: /bitrix/*.css
Allow: /local/*.jpg
Allow: /local/*.jpeg
Allow: /local/*.png
Allow: /local/*.gif
Allow: /local/*.webp
Allow: /local/*.svg
Allow: /local/*.pdf
Allow: /local/*.ttf
Allow: /local/*.woff
Allow: /articles
Allow: /company
Allow: /contacts
Allow: /gallery
Allow: /images
Allow: /projects
Allow: /services
Allow: /sitemap

User-Agent: Googlebot-Mobile
Disallow: /cgi-bin
Disallow: /basket
Disallow: /bitrix/
Disallow: *bitrix_*=
Disallow: /local/
Disallow: /test/
Disallow: /*index.php$
Disallow: /auth
Disallow: /personal/=
Disallow: /*order
Disallow: *register=
Disallow: *forgot_password=
Disallow: *change_password=
Disallow: /*login=
Disallow: *logout=
Disallow: */search/
Disallow: *display=
Disallow: *linerow=
Disallow: *year=
Disallow: *action=
Disallow: *alfaction=
Disallow: *print=
Disallow: *?new=Y
Disallow: *?edit=
Disallow: *?preview=
Disallow: *backurl=
Disallow: *back_url=
Disallow: *back_url_admin=
Disallow: *captcha
Disallow: *?FILTER*=
Disallow: *?arrFilter*
Disallow: *set_filter=
Disallow: *oid=*
Disallow: *?ei=
Disallow: *id=
Disallow: *?p=
Disallow: *?q=
Disallow: *?tags=
Disallow: *brand=
Disallow: *clear_cache*
Disallow: *element_id=
Disallow: *different=
Disallow: *price_from=
Disallow: *price_to=
Disallow: /*type=
Disallow: *property_width=
Disallow: *property_height=
Disallow: *property_dia=
Disallow: *property_opening_count=
Disallow: *property_price[*]=
Disallow: *s_last=
Disallow: *section_id=
Disallow: *section[*]=
Disallow: /*show_
Disallow: *showall=
Disallow: *show_all=
Disallow: *showby=
Disallow: /*add_to_*
Disallow: *sort=
Disallow: *?action_ccr=
Disallow: *sphrase_id=
Disallow: *etext=
Disallow: *utm*=
Disallow: *openstat=
Disallow: *from=
Disallow: *gclid=
Disallow: *yclid=
Disallow: */apply/
Disallow: */feed
Disallow: */rss
Disallow: *orderby=
Disallow: *taxonomy=
Disallow: *private=
Allow: */upload/
Allow: /bitrix/*.js
Allow: /local/*.js
Allow: /bitrix/*.css
Allow: /local/*.jpg
Allow: /local/*.jpeg
Allow: /local/*.png
Allow: /local/*.gif
Allow: /local/*.webp
Allow: /local/*.svg
Allow: /local/*.pdf
Allow: /local/*.ttf
Allow: /local/*.woff
Allow: /articles
Allow: /company
Allow: /contacts
Allow: /gallery
Allow: /images
Allow: /projects
Allow: /services
Allow: /sitemap

User-Agent: ChatGPT-User
Disallow: /cgi-bin
Disallow: /basket
Disallow: /bitrix/
Disallow: *bitrix_*=
Disallow: /local/
Disallow: /test/
Disallow: /*index.php$
Disallow: /auth
Disallow: /personal/=
Disallow: /*order
Disallow: *register=
Disallow: *forgot_password=
Disallow: *change_password=
Disallow: /*login=
Disallow: *logout=
Disallow: */search/
Disallow: *display=
Disallow: *linerow=
Disallow: *year=
Disallow: *action=
Disallow: *alfaction=
Disallow: *print=
Disallow: *?new=Y
Disallow: *?edit=
Disallow: *?preview=
Disallow: *backurl=
Disallow: *back_url=
Disallow: *back_url_admin=
Disallow: *captcha
Disallow: *?FILTER*=
Disallow: *?arrFilter*
Disallow: *set_filter=
Disallow: *oid=*
Disallow: *?ei=
Disallow: *id=
Disallow: *?p=
Disallow: *?q=
Disallow: *?tags=
Disallow: *brand=
Disallow: *clear_cache*
Disallow: *element_id=
Disallow: *different=
Disallow: *price_from=
Disallow: *price_to=
Disallow: /*type=
Disallow: *property_width=
Disallow: *property_height=
Disallow: *property_dia=
Disallow: *property_opening_count=
Disallow: *property_price[*]=
Disallow: *s_last=
Disallow: *section_id=
Disallow: *section[*]=
Disallow: /*show_
Disallow: *showall=
Disallow: *show_all=
Disallow: *showby=
Disallow: /*add_to_*
Disallow: *sort=
Disallow: *?action_ccr=
Disallow: *sphrase_id=
Disallow: *etext=
Disallow: *utm*=
Disallow: *openstat=
Disallow: *from=
Disallow: *gclid=
Disallow: *yclid=
Disallow: */apply/
Disallow: */feed
Disallow: */rss
Disallow: *orderby=
Disallow: *taxonomy=
Disallow: *private=
Allow: */upload/
Allow: /bitrix/*.js
Allow: /local/*.js
Allow: /bitrix/*.css
Allow: /local/*.jpg
Allow: /local/*.jpeg
Allow: /local/*.png
Allow: /local/*.gif
Allow: /local/*.webp
Allow: /local/*.svg
Allow: /local/*.pdf
Allow: /local/*.ttf
Allow: /local/*.woff
Allow: /articles
Allow: /company
Allow: /contacts
Allow: /gallery
Allow: /images
Allow: /projects
Allow: /services
Allow: /sitemap

User-Agent: PerplexityBot/1.0
Disallow: /cgi-bin
Disallow: /basket
Disallow: /bitrix/
Disallow: *bitrix_*=
Disallow: /local/
Disallow: /test/
Disallow: /*index.php$
Disallow: /auth
Disallow: /personal/=
Disallow: /*order
Disallow: *register=
Disallow: *forgot_password=
Disallow: *change_password=
Disallow: /*login=
Disallow: *logout=
Disallow: */search/
Disallow: *display=
Disallow: *linerow=
Disallow: *year=
Disallow: *action=
Disallow: *alfaction=
Disallow: *print=
Disallow: *?new=Y
Disallow: *?edit=
Disallow: *?preview=
Disallow: *backurl=
Disallow: *back_url=
Disallow: *back_url_admin=
Disallow: *captcha
Disallow: *?FILTER*=
Disallow: *?arrFilter*
Disallow: *set_filter=
Disallow: *oid=*
Disallow: *?ei=
Disallow: *id=
Disallow: *?p=
Disallow: *?q=
Disallow: *?tags=
Disallow: *brand=
Disallow: *clear_cache*
Disallow: *element_id=
Disallow: *different=
Disallow: *price_from=
Disallow: *price_to=
Disallow: /*type=
Disallow: *property_width=
Disallow: *property_height=
Disallow: *property_dia=
Disallow: *property_opening_count=
Disallow: *property_price[*]=
Disallow: *s_last=
Disallow: *section_id=
Disallow: *section[*]=
Disallow: /*show_
Disallow: *showall=
Disallow: *show_all=
Disallow: *showby=
Disallow: /*add_to_*
Disallow: *sort=
Disallow: *?action_ccr=
Disallow: *sphrase_id=
Disallow: *etext=
Disallow: *utm*=
Disallow: *openstat=
Disallow: *from=
Disallow: *gclid=
Disallow: *yclid=
Disallow: */apply/
Disallow: */feed
Disallow: */rss
Disallow: *orderby=
Disallow: *taxonomy=
Disallow: *private=
Allow: */upload/
Allow: /bitrix/*.js
Allow: /local/*.js
Allow: /bitrix/*.css
Allow: /local/*.jpg
Allow: /local/*.jpeg
Allow: /local/*.png
Allow: /local/*.gif
Allow: /local/*.webp
Allow: /local/*.svg
Allow: /local/*.pdf
Allow: /local/*.ttf
Allow: /local/*.woff
Allow: /articles
Allow: /company
Allow: /contacts
Allow: /gallery
Allow: /images
Allow: /projects
Allow: /services
Allow: /sitemap

User-Agent: Perplexity-User/1.0
Disallow: /cgi-bin
Disallow: /basket
Disallow: /bitrix/
Disallow: *bitrix_*=
Disallow: /local/
Disallow: /test/
Disallow: /*index.php$
Disallow: /auth
Disallow: /personal/=
Disallow: /*order
Disallow: *register=
Disallow: *forgot_password=
Disallow: *change_password=
Disallow: /*login=
Disallow: *logout=
Disallow: */search/
Disallow: *display=
Disallow: *linerow=
Disallow: *year=
Disallow: *action=
Disallow: *alfaction=
Disallow: *print=
Disallow: *?new=Y
Disallow: *?edit=
Disallow: *?preview=
Disallow: *backurl=
Disallow: *back_url=
Disallow: *back_url_admin=
Disallow: *captcha
Disallow: *?FILTER*=
Disallow: *?arrFilter*
Disallow: *set_filter=
Disallow: *oid=*
Disallow: *?ei=
Disallow: *id=
Disallow: *?p=
Disallow: *?q=
Disallow: *?tags=
Disallow: *brand=
Disallow: *clear_cache*
Disallow: *element_id=
Disallow: *different=
Disallow: *price_from=
Disallow: *price_to=
Disallow: /*type=
Disallow: *property_width=
Disallow: *property_height=
Disallow: *property_dia=
Disallow: *property_opening_count=
Disallow: *property_price[*]=
Disallow: *s_last=
Disallow: *section_id=
Disallow: *section[*]=
Disallow: /*show_
Disallow: *showall=
Disallow: *show_all=
Disallow: *showby=
Disallow: /*add_to_*
Disallow: *sort=
Disallow: *?action_ccr=
Disallow: *sphrase_id=
Disallow: *etext=
Disallow: *utm*=
Disallow: *openstat=
Disallow: *from=
Disallow: *gclid=
Disallow: *yclid=
Disallow: */apply/
Disallow: */feed
Disallow: */rss
Disallow: *orderby=
Disallow: *taxonomy=
Disallow: *private=
Allow: */upload/
Allow: /bitrix/*.js
Allow: /local/*.js
Allow: /bitrix/*.css
Allow: /local/*.jpg
Allow: /local/*.jpeg
Allow: /local/*.png
Allow: /local/*.gif
Allow: /local/*.webp
Allow: /local/*.svg
Allow: /local/*.pdf
Allow: /local/*.ttf
Allow: /local/*.woff
Allow: /articles
Allow: /company
Allow: /contacts
Allow: /gallery
Allow: /images
Allow: /projects
Allow: /services
Allow: /sitemap

User-Agent: Googlebot-Extended
Disallow: /cgi-bin
Disallow: /basket
Disallow: /bitrix/
Disallow: *bitrix_*=
Disallow: /local/
Disallow: /test/
Disallow: /*index.php$
Disallow: /auth
Disallow: /personal/=
Disallow: /*order
Disallow: *register=
Disallow: *forgot_password=
Disallow: *change_password=
Disallow: /*login=
Disallow: *logout=
Disallow: */search/
Disallow: *display=
Disallow: *linerow=
Disallow: *year=
Disallow: *action=
Disallow: *alfaction=
Disallow: *print=
Disallow: *?new=Y
Disallow: *?edit=
Disallow: *?preview=
Disallow: *backurl=
Disallow: *back_url=
Disallow: *back_url_admin=
Disallow: *captcha
Disallow: *?FILTER*=
Disallow: *?arrFilter*
Disallow: *set_filter=
Disallow: *oid=*
Disallow: *?ei=
Disallow: *id=
Disallow: *?p=
Disallow: *?q=
Disallow: *?tags=
Disallow: *brand=
Disallow: *clear_cache*
Disallow: *element_id=
Disallow: *different=
Disallow: *price_from=
Disallow: *price_to=
Disallow: /*type=
Disallow: *property_width=
Disallow: *property_height=
Disallow: *property_dia=
Disallow: *property_opening_count=
Disallow: *property_price[*]=
Disallow: *s_last=
Disallow: *section_id=
Disallow: *section[*]=
Disallow: /*show_
Disallow: *showall=
Disallow: *show_all=
Disallow: *showby=
Disallow: /*add_to_*
Disallow: *sort=
Disallow: *?action_ccr=
Disallow: *sphrase_id=
Disallow: *etext=
Disallow: *utm*=
Disallow: *openstat=
Disallow: *from=
Disallow: *gclid=
Disallow: *yclid=
Disallow: */apply/
Disallow: */feed
Disallow: */rss
Disallow: *orderby=
Disallow: *taxonomy=
Disallow: *private=
Allow: */upload/
Allow: /bitrix/*.js
Allow: /local/*.js
Allow: /bitrix/*.css
Allow: /local/*.jpg
Allow: /local/*.jpeg
Allow: /local/*.png
Allow: /local/*.gif
Allow: /local/*.webp
Allow: /local/*.svg
Allow: /local/*.pdf
Allow: /local/*.ttf
Allow: /local/*.woff
Allow: /articles
Allow: /company
Allow: /contacts
Allow: /gallery
Allow: /images
Allow: /projects
Allow: /services
Allow: /sitemap
