Sitemap: https://www.yupiii.gr/sitemap/allnews
Sitemap: https://www.yupiii.gr/sitemap/googlenews
Sitemap: https://www.yupiii.gr/sitemap/categories
User-agent: *
Disallow: 
#Disallow: /Api/*
#Disallow: /api/*
#Disallow: /Search*
#Disallow: /search*
Disallow: /Newsletter*
Disallow: /newsletter*
Disallow: /webtv/videofeed*

User-agent: msnbot
Crawl-delay: 120


#Block ChatGPT etc.
User-agent: GPTBot
Disallow: /
User-agent: CCBot
Disallow: /