User-agent: *
Disallow: /manager/
Disallow: /assets/components/
Disallow: /core/
Disallow: /connectors/
Disallow: /index.php
Disallow: *?
Host: zdohrana.ru
Sitemap: http://zdohrana.ru/sitemap.xml